### ISSUE TITLE
Complex query, like in ParseLambda_Complex_2, internal could only be used once

### ISSUE THREAD

**Issue by jogibear9988** [zzzprojects/System.Linq.Dynamic.Core#110]
If you do a complex query like this, and want to use the same internal like the "x" in `Where(x=>`  only once, because we add the "x" to the internals dictionary, but never remove or overwrite it.

I think we should increase a Level of the internal with a OpenParam, and Decrease it with CloseParam, and when the level is lower then "0" we remove it

**Comment by StefH** [comment]
Can you provide a detailed example on this issue please ?

Do you mean something like:
`.Where(x => x.Value > 0 && x.Value < 10);`

**Comment by jogibear9988** [comment]
No, smth like:

      .Where(x => x.Value > 0).Where(x => x.Value < 10);

or

   .Where(x => x.Value > 0).Any(x => x.Value < 10);
