### ISSUE TITLE
Question: Is it possible to do case-insensitive search

### ISSUE THREAD

**Issue by rajeshmuraleedharan** [zzzprojects/System.Linq.Dynamic.Core#128]
I would like to do case-insensitive search with startswith,endwith and Contains. Please let me know this is possible or not.

**Comment by StefH** [comment]
This is related to your SQL-server settings ?

**Comment by mhosman** [comment]
@rajeshmuraleedharan When you install SQL Server you must specify de collation. CI is for case insensitive and AI is for accent insensitive. Anyway, It could be great to make request in CI, AI, CS, AS "on demand".

**Comment by jogibear9988** [comment]
I think, you should able house: title.Contains("string", StringComparison.OrdinalIgnoreCase);  if it works is a question of your linq adapter

**Comment by StefH** [comment]
@jogibear9988 This will not work for this library I think.

**Comment by SolidWhiteSven** [comment]
Sadly it doesn't work, the part "StringComparison" is treated as a property and you get an error saying, that the property or field 'StringComparison' exists in the currently used type.
However, you can use the string value of the enum, described in the [Enum Type Support](https://github.com/StefH/System.Linq.Dynamic.Core/wiki/Dynamic-Expressions#enum-type-support) Section.

`users.Where("GivenName.Contains(\"sa\", \"OrdinalIgnoreCase\")");`

Works perfectly for me :-)

**Comment by wilari932** [comment]
How do you do a case sensitive search with this  library ???
Query.Where($"{dataPropertie.Name}.ToString().Trim().ToLower(\"\\@0\")", cols.Values.ToStringNullSafe().Trim().ToLower()).OrderBy(dataPropertie.Name).ToList();
I tried something like this but is not working i
Message = "No applicable method 'ToLower' exists in type 'String'"

**Comment by zspitz** [comment]
@rajeshmuraleedharan With #450, `StringComparison` is now supported, so the following should work:
```
users.Where("GivenName.Contains(\"sa\", StringComparison.OrdinalIgnoreCase)");
```
---
@wilari932 How would you write a case-insensitive search using standard expression trees? If this would work:
```
var cols1 = cols.Values?.ToString().Trim();
Query = Query.Where(x => x.Contains(cols1, StringComparison.OrdinalIgnoreCase));
```
then the following should also work:
```
var cols1 = cols.Values?.ToString().Trim();
Query = Query.Where("Contains(@0, StringComparison.OrdinalIgnoreCase)", cols1);
```

**Comment by khmurach** [comment]
> users.Where("GivenName.Contains(\"sa\", StringComparison.OrdinalIgnoreCase)");

Still does not work for me in 1.2.6

**Comment by zspitz** [comment]
@khmurach How are you escaping the quotation marks?

**Comment by khmurach** [comment]
> @khmurach How are you escaping the quotation marks? Also, is this being run against a database or other Queryable provider?

Yes

**Comment by zspitz** [comment]
@khmurach So the case-sensitivity may very well be determined by the database/provider.

What happens if you write a compiler-generated expression tree:
```csharp
var lst = users.Where(user => user.GivenName.Contains("sa", StringComparison.OrdinalIgnoreCase").ToList();
```

**Comment by zspitz** [comment]
@khmurach It works for me:
![image](https://user-images.githubusercontent.com/312166/101278669-b46c1800-37c5-11eb-8bb3-7bae51eac13b.png)
Which framework are you targeting?

**Comment by khmurach** [comment]
@zspitz I have generic method so there is no properties to use in standard Where(x=>x.Name.Contains("value")).

`IQueryable<T> ApplyFilter(IQueryable<T> dataAll, object filter)`

This line works fine:
`dataQueryable = dataQueryable.Where("{0}.ToLower().Contains(@0)".FormatWith(item.Key), item.Value.ToString().ToLower());`
But I would like to get rid of ToLower()

**Comment by khmurach** [comment]
> @khmurach This works for me:
> 
> ```cs
> var lst = new List<User>();
> var qry = lst.AsQueryable().Where("GivenName.Contains(\"sa\", StringComparison.OrdinalIgnoreCase)");
> 
> public class User {
>     public string? GivenName { get; set; }
> }
> ```
> 
> Visualizing `qry.Expression`:
> ![image](https://user-images.githubusercontent.com/312166/101278669-b46c1800-37c5-11eb-8bb3-7bae51eac13b.png)
> Which framework are you targeting?

targetFramework="net451"

**Comment by zspitz** [comment]
@khmurach It seems that .NET Framework 4.5.1 doesn't support this overload of `Contains`:
![image](https://user-images.githubusercontent.com/312166/101278798-8affbc00-37c6-11eb-870d-eaf8565a16b3.png)
How would you do this with a strongly-typed query?

N.B. The `filter` you are passing into `ApplyFilter` could also be generic:
```csharp
IQueryable<T> ApplyFilter(IQueryable<T> dataAll, Func<T, bool> filter) {

}
```
and then you would have strong-typing on the filter itself. Although I don't quite see what it gives you over the standard `.Where`.

**Comment by khmurach** [comment]
Even in this simplified example, first two queries works fine but the last one throws error:
```
var items = new List<ListItem>() { new ListItem { Title = "John" }, new ListItem { Title = "Adam" }, new ListItem { Title = "john" } };
// works fine
var result1 = items.AsQueryable().Where("Title.ToLower().Contains(\"jo\")").ToList();
// works fine
var result2 = items.AsQueryable().Where(x => x.Title.Contains("jo", StringComparison.OrdinalIgnoreCase)).ToList();
// throws exception
var result3 = items.AsQueryable().Where("Title.Contains(\"jo\", StringComparison.OrdinalIgnoreCase)").ToList();
```

**Comment by khmurach** [comment]
I'm using 
`object filter`
in 
`IQueryable<T> ApplyFilter(IQueryable<T> dataAll, object filter)`
to be able to use any object (projection) as a filter and to use reflection to scan props and values and apply them as a filter to List<T>:

```
var usersCache = _repository.GetAll<User>();
var filter1 = new User{ FirstName = "jo", LastName = "wes" };
var filter2 = new UserQuery{ Name = "jo" };
var result1 = ApplyFilter(usersCache, filter1);
var result2 = ApplyFilter(usersCache, filter2);
```

**Comment by ButtiBBQ** [comment]
Any updates on how to do an case invariant search?

**Comment by StefH** [comment]
Closing..

**Comment by ahdung** [comment]
> Sadly it doesn't work, the part "StringComparison" is treated as a property and you get an error saying, that the property or field 'StringComparison' exists in the currently used type.遗憾的是，它不起作用，“StringComparison”部分被视为属性，并会报错，提示属性或字段“StringComparison”存在于当前使用的类型中。 However, you can use the string value of the enum, described in the [Enum Type Support](https://github.com/StefH/System.Linq.Dynamic.Core/wiki/Dynamic-Expressions#enum-type-support) Section.但是，您可以使用枚举的字符串值，这在枚举类型支持部分中进行了描述。
> 
> `users.Where("GivenName.Contains(\"sa\", \"OrdinalIgnoreCase\")");`
> 
> Works perfectly for me :-)

xxx.Contains("a", "OrdinalIgnoreCase") not work correct, still case senstive.

**Comment by ahdung** [comment]
> [@khmurach](https://github.com/khmurach) This works for me:
> 
> var lst = new List<User>();
> var qry = lst.AsQueryable().Where("GivenName.Contains(\"sa\", StringComparison.OrdinalIgnoreCase)");
> 
> public class User {
>     public string? GivenName { get; set; }
> }
> Visualizing `qry.Expression`: ![image](https://user-images.githubusercontent.com/312166/101278669-b46c1800-37c5-11eb-8bb3-7bae51eac13b.png) Which framework are you targeting?

What your version? current version `1.7.2` is not good, seems ignored `OrdinalIgnoreCase`
