### ISSUE TITLE
Cyclic types support in DynamicClassFactory

### ISSUE THREAD

**Issue by matt-psaltis** [zzzprojects/System.Linq.Dynamic.Core#256]
To model many-to-many relationships, I would like to submit a PR which introduces:

* DynamicClassDefinition. Allows for customisable namespaces, names and base classes
* A DynamicLateBoundProperty. This is similar to DynamicProperty however it allows multiple DynamicClassDefinition objects to be constructed simultaneously. This allows the Clr Types to be built with cyclic properties.

Is this something that you would be open to?

Example models:
``` c#
public class Post
{
	public int PostId { get; set; }
	public string Title { get; set; }
	public string Content { get; set; }

	public List<PostTag> PostTags { get; set; }
}

public class Tag
{
	public string TagId { get; set; }

	public List<PostTag> PostTags { get; set; }
}

public class PostTag
{
	public int PostId { get; set; }
	public Post Post { get; set; }

	public string TagId { get; set; }
	public Tag Tag { get; set; }
}
```

Example signatures:
``` c#
public class DynamicLateBoundProperty : DynamicPropertyBase
{
	public DynamicLateBoundProperty(string name, Func<DynamicClassDefinition> definition);

	public DynamicLateBoundProperty(string name, Func<Type> typeResolver);
}

public class DynamicClassDefinition
{
	public DynamicClassDefinition([NotNull] List<DynamicPropertyBase> properties, string @namespace = null, string name = null, Type baseType = null, bool createParameterCtor = true);
}
```

Usage:
``` c#
var @namespace="Test.Namespace1";
var postTagDefinition = new DynamicClassDefinition(postTagProps, @namespace, "PostTag");
var postDefinition = new DynamicClassDefinition(postProps, @namespace, "Post");
var tagDefinition = new DynamicClassDefinition(tagProps, @namespace, "Tag");

postTagProps.AddRange(new List<DynamicPropertyBase>
{
	new DynamicProperty("PostTagId", typeof(long)),
	new DynamicProperty("PostId", typeof(long)),
	new DynamicProperty("TagId", typeof(long)),
	new DynamicLateBoundProperty("Post", () => postDefinition),
	new DynamicLateBoundProperty("Tag", () => tagDefinition)
});

postProps.AddRange(new List<DynamicPropertyBase>
{
	new DynamicProperty("PostId", typeof(long)),
	new DynamicProperty("Title", typeof(string)),
	new DynamicLateBoundProperty("PostTags",
		() => typeof(ICollection<>).MakeGenericType(postTagDefinition.ResolveType()))
});

tagProps.AddRange(new List<DynamicPropertyBase>
{
	new DynamicProperty("TagId", typeof(long)),
	new DynamicProperty("Name", typeof(string)),
	new DynamicLateBoundProperty("PostTags",
		() => typeof(ICollection<>).MakeGenericType(postTagDefinition.ResolveType()))
});

DynamicClassFactory.CreateTypes(new[] {postTagDefinition, postDefinition, tagDefinition});
```

**Comment by StefH** [comment]
How would this be used in a real scenario?

**Comment by SaltyDH** [comment]
In my specific use case, its a runtime generated dynamic model, driven by user configuration so specific scenarios are more generalised into their base structure.

We have two such scenarios: 

1. Model many to many relationships using two one to many relationships through the lookup entity/relationship in the middle. An example given above in the Post->PostTag->Tag example.
2. Parent/Child POCO objects where the Parent object has a collection-of-children property and the children have a property to access their parent.

As DynamicClassFactory stands at present, I cannot construct types of this nature.

Does that help at all to clarify?

**Comment by StefH** [comment]
You can start a PR, just make sure unit tests are also created.

**Comment by StefH** [comment]
Hello @matt-psaltis, is this still relevant for you? Or can I close this issue?
