### ISSUE TITLE
how to set the certain type when use select or groupby

### ISSUE THREAD

**Issue by pjkpjpk** [zzzprojects/System.Linq.Dynamic.Core#257]
Hi All,
   Could somebody  tell me what the means about operators such as 'T.m,T()' and how to use them.
   Whether I can set the certain type when use select or groupby.
   Like this:
   1. persons.where("Age>@0",25).select("new type1(age,name)"); 
   2. persons.groupby('new type1(age,sex)","it");
   
Thanks very much! Please give me some examples or suggestions.

**Comment by StefH** [comment]
@pjkpjpk

Calling the `new` operator to create a new type is possible, just use this code:
``` c#
var queryable = new List<string>() { "name1", "name2" }.AsQueryable();
var projectedData = queryable.Select<Example.NestedDto>(config, $"new {typeof(Example.NestedDto).FullName}(~ as Name)");
```

Maybe if the type is not an anonymous and not a default type, use :
``` c#
var config = new ParsingConfig { AllowNewToEvaluateAnyType = true };
var queryable = new List<string>() { "name1", "name2" }.AsQueryable();
var projectedData = queryable.Select<Example.NestedDto>(config, $"new {typeof(Example.NestedDto).FullName}(~ as Name)");
```

See also https://github.com/StefH/System.Linq.Dynamic.Core/blob/5e24989dd174307985892a084fd7abb7f2c74122/test/System.Linq.Dynamic.Core.Tests/QueryableTests.Select.cs#L269

And see also some tests here:
https://github.com/StefH/System.Linq.Dynamic.Core/blob/5863256c11e32b100c917d133c54bda4afae4d8a/test/System.Linq.Dynamic.Core.Tests/ComplexTests.cs

**Comment by StefH** [comment]
@pjkpjpk Does this answer your question?

**Comment by JonathanMagnan** [comment]
Hello,

I will close this issue as it seems @StefH answered it.

If you still have the issue and can reproduce it in a standalone project, we will be happy to re-open and investigate it.

Best Regards,
 
Jon
 
---
 
**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)
 
**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
