### ISSUE TITLE
Respect EnumMemberAttribute value when converting enums

### ISSUE THREAD

**Issue by alexweav** [zzzprojects/System.Linq.Dynamic.Core#280]
The query language's enum type conversion currently ignores [EnumMemberAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.enummemberattribute?view=netcore-2.2l) values, if they are present.

For instance, given an enum:

```
public enum TestEnum
{
    [EnumMember(Value = "MY_VALUE")]
    MyValue
}
```

Currently, the value can be accessed via `"MyValue"` case insensitively, e.g. `myField == "myvalue"`.

However, the enum can not be accessed via its `EnumMemberAttribute` value - `myField == "MY_VALUE"` does not work.

Do we want to support the `EnumMemberAttribute` value when converting enum values? If so, I would be willing to provide a PR.

**Comment by StefH** [comment]
You can try to make a PR.

**Comment by JonathanMagnan** [comment]
Hello,

I will close this issue, I'm not sure if a pull has been provided or not.

If no pull has been provided, we will be happy to merge it 

Best Regards,
 
Jon
 
---
 
**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)
 
**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
