### ISSUE TITLE
String(Null) raises Ambiguous error

### ISSUE THREAD

**Issue by rockResolve** [zzzprojects/System.Linq.Dynamic.Core#284]
When Selecting String(Null) I get the "Ambiguous invocation of 'String' constructor" error.
This seems pointless as any matching constructor should work.

I need the String cast because I Concat this with a query with another and the Concat insists on matching types.

How can I get a Select to return a null string from a literal null?

**Comment by StefH** [comment]
Use
``` c#
qry.Select("string(\"null\")")
```

**Comment by rockResolve** [comment]
Oops, my final question should have been not have mentioned "literal", but rather
How do I select a string with a null value

I need it to be null to force it to the bottom when sorted with concatenated rows.

**Comment by rockResolve** [comment]
Further info ...

It seems String(null) is not valid C#

`var x = new System.String(null)`
throws error CS0121: The call is ambiguous between the following methods or properties: 'string.String(char*)' and 'string.String(sbyte*)'

FYI I was using String(null) successfully in the old https://github.com/kahanu/System.Linq.Dynamic

**Comment by rockResolve** [comment]
Further info

String(null) was working in the old https://github.com/kahanu/System.Linq.Dynamic
ExpressionParser.FindBestMethod returned 0 which triggered GenerateConversion

**Comment by rockResolve** [comment]
@StefH Could you please revisit this.

How do I create null cast to a String?

**Comment by StefH** [comment]
Hello @rockResolve, can please check with the latest version from System.Linq.Dynamic.Core ?

I think this is fixed, see example: https://dotnetfiddle.net/3cA1gr

**Comment by rockResolve** [comment]
All fixed now. Thanks
