### ISSUE TITLE
System.Linq.Dynamic.Core.DynamicQueryableExtensions.AsEnumerable conflicts with System.Linq.Enumerable.AsEnumerable

### ISSUE THREAD

**Issue by jbagley-iona** [zzzprojects/System.Linq.Dynamic.Core#304]
I've run into an issue where the System.Linq.Dynamic.Core.DynamicQueryableExtensions.AsEnumerable extension method conflicts with the System.Linq.Enumerable.AsEnumerable extension method:

```
The call is ambiguous between the following methods or properties: 'System.Linq.Enumerable.AsEnumerable<TSource>(System.Collections.Generic.IEnumerable<TSource>)' and
 'System.Linq.Dynamic.Core.DynamicQueryableExtensions.AsEnumerable(System.Linq.IQueryable)'
```
I think this will become a more common issue with the upcoming release of EF Core 3.0 (where it will be necessary to explicitly force the enumeration of DB queries to avoid exceptions if they cannot be translated completely to SQL).

MoreLinq has similar issues and outlines a workaround in their documention (https://github.com/morelinq/MoreLINQ/blob/v3.1.0/README.md#usage).  Would it be possible to do something similar in System.Linq.Dynamic.Core?

**Comment by StefH** [comment]
If you want to apply the logic from this library on an IEnumerable, just to a AsQueryable() and continue to use this library.

**Comment by jbagley-iona** [comment]
The problem I've run into is I have a class that makes use of both this library and System.Linq.  In this class, I make use of System.Linq.AsEnumerable() to "switch" from an EF (IQueryable) query to a (IEnumerable) Linq-to-Objects query, but I cannot do that if the class also uses System.Linq.Dynamic.Core as it's .AsEnumerable() extension results in the error noted above.

**Comment by StefH** [comment]
Just call the `AsEnumerable()` from System.Linq.Dynamic.Core with full name, like:

``` c#
var result = System.Linq.Dynamic.Core.DynamicQueryableExtensions.AsEnumerable(x);
```

**Comment by jbagley-iona** [comment]
Thanks.  That's what I ended up doing but hoped there would be a better workaround (similar to what MoreLinq does).  These are very large queries with multiple chained calls so having to break the query up to work around an ambiguous extension method issue is not ideal.

**Comment by slang25** [comment]
This is quite a big usability issue. With `System.Linq` being included as a default global namespace in C# 10 I can only seeing this getting more difficult.

It could be worth considering redesigning this API to co-exist with `System.Linq`.

**Comment by pgaske** [comment]
+1 - even though this is an old issue, still affecting me today when upgrading old codebases to ef6.

**Comment by StefH** [comment]
@pgaske & @slang25 & @jbagley-iona 

I'll rename the extension method to `AsDynamicEnumerable` which should solve conflicts.

A new version will be released within a few days.
