### ISSUE TITLE
Examples of JOIN

### ISSUE THREAD

**Issue by YuriGal** [zzzprojects/System.Linq.Dynamic.Core#313]
Could you please provide some code examples on how to use `DynamicQueryableExtensions.Join` ?

EDIT: I think I got it, but when I try something like this:

`var finalResult = finalResult1.AsQueryable().Join(finalResult2, "id", "id", "new(outer.DNS as DNS, inner.TITLE as TITLE)");`

where `finalResult1` and `finalResult2` are `List<dynamic>` and try to use the result - I am getting "Target object is not an ExpandoObject" error. What am I missing?

**Comment by MarineMarin** [comment]
> Could you please provide some code examples on how to use `DynamicQueryableExtensions.Join` ?
> 
> EDIT: I think I got it, but when I try something like this:
> 
> `var finalResult = finalResult1.AsQueryable().Join(finalResult2, "id", "id", "new(outer.DNS as DNS, inner.TITLE as TITLE)");`
> 
> where `finalResult1` and `finalResult2` are `List<dynamic>` and try to use the result - I am getting "Target object is not an ExpandoObject" error. What am I missing?

Same problem here... 
@YuriGal did you solved it ?

**Comment by StefH** [comment]
You could use something like:
``` c#
var dynamicResult = dynamicQuery.ToDynamicArray();

            Assert.Equal(realResult.Length, dynamicResult.Length);
            for (int i = 0; i < realResult.Length; i++)
            {
                Assert.Equal(realResult[i].OwnerName, ((dynamic) dynamicResult[i]).OwnerName);
                Assert.Equal(realResult[i].Pet, ((dynamic) dynamicResult[i]).Pet);
            }
```


see also https://github.com/StefH/System.Linq.Dynamic.Core/blob/5863256c11e32b100c917d133c54bda4afae4d8a/test/System.Linq.Dynamic.Core.Tests/QueryableTests.Join.cs#L55

**Comment by JonathanMagnan** [comment]
Hello @YuriGal 

I will close this issue as it seems that @StefH provided the solution.

If you still have the issue and can reproduce it in a standalone project, we will be happy to re-open and investigate it.

Best Regards,
 
Jon
 
---
 
**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)
 
**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
