### ISSUE TITLE
Combine grouping and data in one list

### ISSUE THREAD

**Issue by rinaldo-rfjr** [zzzprojects/System.Linq.Dynamic.Core#324]
Hi.
I need to generate a list with the group keys and the grouped data, but can't get it to work. My source is a list of dictionaries. Here is what I have in my code:
  
 ``` c#

      private void btnDynamic3_Click(object sender, EventArgs e)
        {
        List<Dictionary<string, object>> listaPadrao = new List<Dictionary<string, object>>();
        Dictionary<string, object> padrao0 = new Dictionary<string, object>();
        Dictionary<string, object> padrao1 = new Dictionary<string, object>();
        Dictionary<string, object> padrao2 = new Dictionary<string, object>();

           padrao0.Add("hash", Guid.NewGuid().ToString());
            padrao0.Add("code", 2123345);
            padrao0.Add("subcode", "CS23");
            padrao0.Add("sign", "AWR");
            padrao0.Add("value", 30.758);

            padrao1.Add("hash", Guid.NewGuid().ToString());
            padrao1.Add("code", 5003345);
            padrao1.Add("subcode", "CS32");
            padrao1.Add("sign", "AWR");
            padrao1.Add("value", 15);

            padrao2.Add("hash", Guid.NewGuid().ToString());
            padrao2.Add("code", 2123345);
            padrao2.Add("subcode", "CS23");
            padrao2.Add("sign", "AWR");
            padrao2.Add("value", 5);

            listaPadrao.Add(padrao0);
            listaPadrao.Add(padrao1);
            listaPadrao.Add(padrao2);

            //This works
            var g = listaPadrao.AsQueryable().GroupBy("new(it[\"code\"] as Code, it[\"subcode\"] as Subcode)", "it").Select("new(Key.Code as Code,Key.Subcode as Subcode, Sum(Convert.ToDouble(it[\"value\"])) as Value, Math.Round(Average(Convert.ToDouble(it[\"value\"])),2) as Media, it as Padrao)");

            //This doesn't work, because I tried to add the field 'sign'
            var h = listaPadrao.AsQueryable().GroupBy("new(it[\"code\"] as Code, it[\"subcode\"] as Subcode)", "it") .Select("new(Key.Code as Code,Key.Subcode as Subcode, it[\"sign\"], Sum(Convert.ToDouble(it[\"value\"])) as Value, Math.Round(Average(Convert.ToDouble(it[\"value\"])),2) as Media, it as Padrao)");

        }
```

If I add the field **sign** to the select, I receive erros that **sign** does not exist. I need to show the sign entry along with the grouped data and the aggregates. Sign is not a field to be used in the grouping, but I need it in the final list.

How can I do that?

Thanks!

**Comment by StefH** [comment]
Should you use this : `Key[\"sign\"] as sign` ?

Like:
``` c#
var h = listaPadrao.AsQueryable().GroupBy("new(it[\"code\"] as Code, it[\"subcode\"] as Subcode)", "it").Select("new(Key.Code as Code,Key.Subcode as Subcode, Key[\"sign\"] as sign, Sum(Convert.ToDouble(it[\"value\"])) as Value, Math.Round(Average(Convert.ToDouble(it[\"value\"])),2) as Media, it as Padrao)");
```

**Comment by rinaldo-rfjr** [comment]
Hi Stef.

I can try it. If I add more fields in my dictionaries, should all of them be added as keys in the Select?

**Comment by rinaldo-rfjr** [comment]
Hi Stef

It didn't work. The list now has a **Sign** field but its value is empty:

![image](https://user-images.githubusercontent.com/48867975/69391893-f1e12e80-0cb2-11ea-811e-51804d878ee6.png)

I can access the **Sign** field and all the grouping data in a loop, but couldn't find a way to access them directly.

**Comment by StefH** [comment]
Sorry, the query should be:
``` c#
var h = listaPadrao.AsQueryable().GroupBy("new(it[\"code\"] as Code, it[\"subcode\"] as Subcode, it[\"sign\"] as sign)", "it").Select("new(Key.Code as Code, Key.Subcode as Subcode, Key.Sign as sign, Sum(Convert.ToDouble(it[\"value\"])) as Value, Math.Round(Average(Convert.ToDouble(it[\"value\"])),2) as Media, it as Padrao)");
```

**Comment by StefH** [comment]
@rinaldo-rfjr does this help?

**Comment by JonathanMagnan** [comment]
Hello @rinaldo-rfjr 

I will close this issue as it seems that for @StefH, everything was working fine.

If you can reproduce it in a standalone project, we will be happy to re-open and investigate it.

Best Regards,
 
Jon
 
---
 
**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)
 
**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
