### ISSUE TITLE
Ef.Like with int type

### ISSUE THREAD

**Issue by SamWhitby** [zzzprojects/System.Linq.Dynamic.Core#330]
Hi, is there any way you can express a cast as described [here](https://github.com/aspnet/EntityFrameworkCore/issues/11089#issuecomment-370059543)? It seems to be the only way to use the like function in .net core when dealing with types other than string.

I have tried 
"DbFunctionsExtensions.Like(EF.Functions, string(object(IntProperty)), @0)" results in : 'Unable to cast object of type 'System.Int32' to type 'System.String'.'

"DbFunctionsExtensions.Like(EF.Functions, IntProperty.ToString(), @0)" works but the sql generated is undesirable as it puts an explicit cast in

**Comment by Feroks** [comment]
If anyone comes here, you can do it like described here https://github.com/zzzprojects/System.Linq.Dynamic.Core/issues/328

**Comment by randellhodges** [comment]
That method doesn't work if the value is nullable

**Comment by StefH** [comment]
Dear @SamWhitby,

I'll close this issue for now, in case you have questions, just reply or create a new issue.
