### ISSUE TITLE
Shadow properties

### ISSUE THREAD

**Issue by akghasemi** [zzzprojects/System.Linq.Dynamic.Core#334]
It throws an Error when you try to use the shadow properties

**Comment by StefH** [comment]
@akghasemi Please provide example project

**Comment by StefH** [comment]
@akghasemi Please provide example project

**Comment by akghasemi** [comment]
HI, Sorry for responding too late,
Adding a shadow properties are simple and you can add shadow properties to entity framework like this
`public class SampleContext : DbContext
{
    public DbSet<Contact> Contacts { get; set; }
    
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
         modelBuilder.Entity<Contact>()
            .Property<DateTime>("LastUpdated");
    } 
}

public class Contact
{
    public int ContactId { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Email { get; set; } 
}`
now field LastUpdated is a part of Contact Entity and Entityframe work manages updating the field and just like other fields in contact model however it is not part of Contract model.
you can set the value of shadow property like this 
`var context = new SampleContext();
var contact = new Contact { FirstName = "John", LastName = "Doe" };
context.Add(contact);
context.Entry(contact).Property("LastUpdated").CurrentValue = DateTime.UtcNow;
context.SaveChanges();`
I hope this helps

**Comment by StefH** [comment]
Interesting... I need to take a look here...

**Comment by ricoisme** [comment]
I got same error.

**Comment by JonathanMagnan** [comment]
Hello @akghasemi , @ricoisme ,

Unfortunately, this request still doesn't support it. However, we might try to eventually add it as this can be useful sometimes.

However, that is already possible with another of our library: https://eval-expression.net/

```csharp
// Register Type & ExtensionMethod only once
EvalManager.DefaultContext.RegisterType(typeof(EF));

using (var context = new EntityContext())
{
	var list = context.EntitySimples.WhereDynamic("x => x.ColumnInt == 1 && EF.Property<string>(x, \"shadowSimple\") == \"1\"").ToList();
}
```

The library is paid but Dynamic LINQ extension such as WhereDynamic as free.

You can find some documentation here: https://eval-expression.net/linq-dynamic

Let me know if that solves your issues.

Best Regards,

Jon
