### ISSUE TITLE
Ordering on a anonymous type can not be translated to a LINQ query

### ISSUE THREAD

**Issue by rmosselveld** [zzzprojects/System.Linq.Dynamic.Core#335]
My application has always been working with dynamic ordering until i upgraded to EF Core 3.0. I now found out a part of my dynamic ordering LINQ query could not be created.

After some more debugging I found out that the query that is created by te dynamic linq library creates a new anonymous type and tries to sort on that type. This results in the following exception:

```
The LINQ expression 'DbSet<DeviceStatusHistory>
    .Where(d => d.DeviceId == __deviceId_0)
    .OrderByDescending(d => d.Id)
    .Take(__p_1)
    .Join(
        outer: DbSet<Device>, 
        inner: e => EF.Property<Nullable<long>>(e, "DeviceId"), 
        outerKeySelector: d0 => EF.Property<Nullable<long>>(d0, "Id"), 
        innerKeySelector: (o, i) => new TransparentIdentifier<DeviceStatusHistory, Device>(
            Outer = o, 
            Inner = i
        ))
    .OrderByDescending(e => new DeviceStatusHistory{ 
        Id = e.Outer.Id, 
        DeviceId = e.Outer.DeviceId, 
        Device = e.Inner, 
        StartTime = e.Outer.StartTime, 
        EndTime = e.Outer.EndTime, 
        SystemStatus = e.Outer.SystemStatus, 
        SubStates = e.Outer.SubStates 
    }
    .StartTime)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync().
```

If I remove the anonymous object and do a normal sorting, the query runs fine.

Is this something that is not supported?

**Comment by StefH** [comment]
This should just work fine.
See example here: https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/src-console/ConsoleAppEF3.1/Program.cs#L31

**Comment by rmosselveld** [comment]
I edited my post! I did some more debugging after you said this should be working. I found out that removing the creation of the anonymous object does fix this error.

However, I would like to use the object creation since in want to select only a subset of columns. Is this supported?

**Comment by StefH** [comment]
Did you try setting `EvaluateGroupByAtDatabase` to **true** in the ParsingConfig ?

Else, can you provide a full example project?

**Comment by rmosselveld** [comment]
Where should I apply that setting?

Code that is producing this LINQ expression is:

This is the base expression
```
IQueryable<TDeviceStatusHistory> source = this._repository
                                            .Where(d => de.DeviceId == id)
                                            .OrderByDescending(x => x.Id)
                                            .Take(10);
```

Which is extended with Dynamic linq (generic include):

`source = source.Include("Device");`

Doing a select to select only the properties i need (sourceProperties is an array of columnnames i need):

```
string columns = String.Join(",", sourceProperties.Select(p => p.Name));
 source = source.Select<TSource>($"new({columns})");
```

And do a generic sort:

`source = source.OrderBy($"{sortPath} {sortDir}");`

**Comment by StefH** [comment]
In my example, this also works fine:
https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/src-console/ConsoleAppEF3.1/Program.cs#L47

**Comment by JonathanMagnan** [comment]
Hello @rmosselveld ,

I will close this issue as it seems that for @StefH, everything was working fine.

If you can reproduce it in a standalone project, we will be happy to re-open and investigate it.

Best Regards,
 
Jon
 
---
 
**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)
 
**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
