### ISSUE TITLE
Case insensitive GroupBy()

### ISSUE THREAD

**Issue by kKen94** [zzzprojects/System.Linq.Dynamic.Core#351]
Is it possible adding IEqualityComparer to GroupBy()?

**Comment by StefH** [comment]
Technically this is possible, however, what problem will this solve? Can you provide an example / unit test?

**Comment by kKen94** [comment]
`var distinctedRaw = itemsToGroup
                .AsQueryable()
                .GroupBy($"new({string.Join(",", keys)})", "it")
                .Select("it.First()")
                .ToDynamicList<T>();`

I use GroupBy() to group same values by dynamic keys and get unique values to remove duplicates.
But if I don't apply UpperCase(), "STRing"and "strING" for GroupBy are not the same and when I go to save data on database, the latter (obviously) crashes

**Comment by StefH** [comment]
If you execute this query on a database (sql), then this does work fine.

In LinqPad:
``` c#
var city = x.AsQueryable().Where(t => t.Text == "NewYork");
city.Dump();

var distinctedRaw = x
  .AsQueryable().Where(t => t.Text == "NewYork")
  .GroupBy($"new({string.Join(",", keys)})", "it")
  .Select("it.FirstOrDefault()");
  distinctedRaw.Dump();
```
![image](https://user-images.githubusercontent.com/249938/75354467-4ba65580-58ad-11ea-93e8-c376470cfaca.png)

**Comment by kKen94** [comment]
The problem is that i'm not querying db, i'm manipulating local array

**Comment by StefH** [comment]
I see.
It's possible to fix this, however it requires a lot of code changes in the GroupBy methods.

**Comment by kKen94** [comment]
... and a lot of time I suppose. This issue is not urgent, at the moment I lowercasing all. It's a bad workaround, I know, but otherwise I wouldn't know how to do it

**Comment by JonathanMagnan** [comment]
Hello @kKen94 ,

The v1.1.2 has been released.

The GroupBy now supports the `IEqualityComparer` overload.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
