### ISSUE TITLE
OrderBy with non-english letters give different ordering result on string vs key selector

### ISSUE THREAD

**Issue by perason** [zzzprojects/System.Linq.Dynamic.Core#363]
The issue I have is that when using a _string_ (`"ProductId"`) for ordering it doesn't sort properly, e.g.
``` c#
    CultureInfo culture = new CultureInfo("nb-NO");

    itemList = itemList.AsQueryable()
        .OrderBy("ProductId", StringComparer.Create(culture, true))
        .ToList();
```
    Output:
    Ååå
    Ååå
    Aaa
    Aaa
    Bbb
    Bbb

but when using a _key selector_ (`s => s.ProductId`) it does, e.g.
``` c#
    CultureInfo culture = new CultureInfo("nb-NO");

    itemList = itemList.AsQueryable()
        .OrderBy(s => s.ProductId, StringComparer.Create(culture, true))
        .ToList();
```
    Output:
    Aaa
    Aaa
    Bbb
    Bbb
    Ååå
    Ååå

---

I am using `System.Linq.Dynamic.Core` ver. 1.0.23.

I also tried with `StringComparer.InvariantCulture`, but its result is the same.

My `itemList` object(s) looks like this, and is a `List<Inventory>`
``` c#
    public class MyModels
    {
        public int Id { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime EditDate { get; set; }
    }

    public class Inventory : MyModels
    {
        public string ProductId { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
    }
```

**Comment by StefH** [comment]
@perason The code examples you provide are 'normal' linq queries. Can you also provide examples for dynamic linq?

**Comment by perason** [comment]
I thought I just did. To enable a `string ordering` as a first `OrderBy` parameter I added this library, and when not, I am not able to use a `string`, only a `Func<Inventory, TKey>` expression.

If not this is a dynamic linq sample, what is?

**Comment by StefH** [comment]
Ah I see, sorry for the confusion, your code is like:
``` c#
.OrderBy("ProductId", StringComparer.Create(culture, true))
```

However the method will be : https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/DynamicQueryableExtensions.cs#L1316

Which means that the StringComparer will be supplied as a normal argument.
The arguments are used for code like this:
``` c#
.OrderBy("{0}, "ProductId")
```

Note that for numbers, there is https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/ParsingConfig.cs#L183

Maybe I should add StringComparer or CultureInfo setting so that you choose how it should behave.

**Comment by perason** [comment]
If you could add how to use StringComparer and CultureInfo I would be grateful, and thanks very much for quick response.

**Comment by JonathanMagnan** [comment]
Hello @perason ,

The v1.1.2 has been released.

The OrderBynow supports the `StringComparer` overload.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
