### ISSUE TITLE
dynamic queryable extensions "Where"

### ISSUE THREAD

**Issue by manideep418** [zzzprojects/System.Linq.Dynamic.Core#375]
Does the where extension in dynamic queryable extensions support datetime type?.

**Comment by JonathanMagnan** [comment]
Hello @manideep418 ,

It's possible to pass a DateTime type in parameter such as:

```csharp
orders.Where("Date > @0", DateTime.Now.AddDays(-1)).ToList();
```

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
