### ISSUE TITLE
Cannot use with EF.Functions.ILike(anything, "%aaa%")

### ISSUE THREAD

**Issue by mhosman** [zzzprojects/System.Linq.Dynamic.Core#376]
I get error:

`No property or field 'EF' exists in type 'xxxxx'`

**Comment by StefH** [comment]
You can only use EF functions when you use the EntityFramework.DynamicLinq or Microsoft.EntityFrameworkCore.DynamicLinq NuGet.

**Comment by mhosman** [comment]
I'm using System.Linq.Dynamic.Core. There's no way to run this inside a string? Something like... 

.Where("EF.Functions.ILike(anything, \""%aa%"\") and status eq true")

**Comment by mhosman** [comment]
Hey @StefH thanks for the response!
I'm using System.Linq.Dynamic.Core. There's no way to run this inside a string? Something like... 

.Where("EF.Functions.ILike(anything, \""%aa%"\") and status = true")

**Comment by StefH** [comment]
You could use `Contains`?
See https://github.com/zzzprojects/System.Linq.Dynamic.Core/blob/5863256c11e32b100c917d133c54bda4afae4d8a/test/System.Linq.Dynamic.Core.Tests/QueryableTests.Contains.cs#L12

**Comment by mhosman** [comment]
Yes but the problem with contains is that is not generating an ILIKE to the database query. In Postgre, you have LIKE and ILIKE (the ILIKE is for case insensivity). The idea is not to compare with a toUpper or something like that.

**Comment by StefH** [comment]
To get real SQL Like you need to use the EntityFramework.DynamicLinq or Microsoft.EntityFrameworkCore.DynamicLinq NuGet.

See this for an example:
https://github.com/zzzprojects/System.Linq.Dynamic.Core/blob/master/src-console/ConsoleAppEF2.1.1_InMemory/Program.cs#L212

**Comment by tinchoel10** [comment]
I have the same issue trying to migrate to Postgre
I can't use EF functions with DynamicLinq

**Comment by mhosman** [comment]
@tinchoel10 I have the same issue. I need to use EF funcions dynamically (as string).

**Comment by JonathanMagnan** [comment]
Hello all,

Unfortunately, this request go beyond of what this library can offer.

There is currently no plan adding it on a short time.

However, that is possible with another of our library: https://eval-expression.net/

```csharp
// Register Type & ExtensionMethod only once
EvalManager.DefaultContext.RegisterType(typeof(EF));
EvalManager.DefaultContext.RegisterExtensionMethod(typeof(DbFunctionsExtensions));

using (var context = new EntityContext())
{
    //var list = context.EntitySimples.Where(x => EF.Functions.Like(x.ColumnString, "%bc%")).ToList();

    var list2 = context.EntitySimples.WhereDynamic(x => "EF.Functions.Like(x.ColumnString, \"%bc%\")").ToList();

   // or

    var list3 = context.EntitySimples.WhereDynamic("x => EF.Functions.Like(x.ColumnString, \"%bc%\")").ToList();
}
```

The library is paid but Dynamic LINQ extension such as `WhereDynamic` as free.

You can find some documentation here: https://eval-expression.net/linq-dynamic

Let me know if that solves your issues.

Best Regards,

Jon

**Comment by mhosman** [comment]
Something like this can be done?

    var list2 = context.EntitySimples.WhereDynamic(x => "EF.Functions.Like(x.ColumnString, \"%bc%\") or id == 1").ToList();

**Comment by JonathanMagnan** [comment]
@mhosman ,

Everything you can do in C#, you should be able to do it on @mhosman .

Be careful, C# Eval Library require a valid C# syntax. The `or` should be replaced by `||`.

So probably more something like this:

```csharp
var list2 = context.EntitySimples.WhereDynamic(x => "EF.Functions.Like(x.ColumnString, \"%bc%\") || id == 1").ToList();
```

**Comment by rochapablo** [comment]
I'm trying

```
query = query.WhereDynamic(x.FirstOrDefault().Key);
```

where `x.FirstOrDefault().Key` is

```
"EF.Functions.Like(MyColumn, \"%mystringvalue%\")"
```

But I'm getting

```
"Oops! No applicable member has been found for the expression. The error occurred for expression \".\" at position 22 near \".Like(MyColumn, \\\"%mystringvalue%\\\")\"."
```

Also I tried 

```
"x => EF.Functions.Like(x.MyColumn, \"%mystringvalue%\")"
```

But didn't work.

**Comment by JonathanMagnan** [comment]
Hello @rochapablo ,

Have you registered the type?

```csharp
// Register Type & ExtensionMethod only once
EvalManager.DefaultContext.RegisterType(typeof(EF));
EvalManager.DefaultContext.RegisterExtensionMethod(typeof(DbFunctionsExtensions));
```

You are probably missing this.

Otherwise, just provide us an example with this issue and we will look at it.

You can send it in private here: info@zzzprojects.com

Best Regards,

Jon

**Comment by mhosman** [comment]
Hey @JonathanMagnan I get:

> System.Exception: Oops! No applicable member has been found for the expression. The error occurred for expression "." at position 3 near ".Where(c => status == t"

`Just using .WhereDynamic(x => "status == true")`

**Comment by JonathanMagnan** [comment]
Hello @mhosman ,

Here is an online example with `WhereDynamic` using a simple where clause and one using `EF.Functions.Like`

Example: https://dotnetfiddle.net/xCaJr8

In your case, you missing the `x` in `x.status`,

It should have been `.WhereDynamic(x => "x.status == true")`.

It looks like we could improve this part to allow property without having to specify the `x` but for now, you must use a valid C# syntax.
