### ISSUE TITLE
'No applicable aggregate method 'Aggregate' exists' error for enumerablequery`1 types

### ISSUE THREAD

**Issue by joshidp** [zzzprojects/System.Linq.Dynamic.Core#377]
Hi,

Thanks for your work.

I am using your lib and while parsing below snippet using DynamicExpressionParser.ParseLambda I am getting "'No applicable aggregate method 'Aggregate' exists' " error but in your unit tests it works fine.
`abc.Aggregate(\"Sum\",\"xyz\")`

XYZ is of TimeSpan type so I can't use Sum directly.

Please help

**Comment by JonathanMagnan** [comment]
Hello @joshidp ,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
