### ISSUE TITLE
Versioning Issue in Latest NUGET packages

### ISSUE THREAD

**Issue by joshidp** [zzzprojects/System.Linq.Dynamic.Core#378]
Hi,

Thanks for the great work!

After 1.0.22 version all the packages which are published from your end have versioning issue. For example, latest 1.1.0 nuget has version of 1.0.24 in the dll after the install. This creates lots of dependency resolution issue. Please check the issue.

![image](https://user-images.githubusercontent.com/7415276/81569288-b3544300-93bc-11ea-8608-4b3fd46a0b5e.png)

version 1.0.24 has 1.0.23 dll.

![image](https://user-images.githubusercontent.com/7415276/81569468-ebf41c80-93bc-11ea-8ea1-853fc2a570df.png)

**Comment by JonathanMagnan** [comment]
Hello @joshidp ,

Thank you for reporting. I made a very quick check and you are right.

We will try to deploy a new version this night.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by joshidp** [comment]
Any updates?

**Comment by JonathanMagnan** [comment]
Hello @joshidp ,

Sorry for the additional delay,

The v1.1.1 has been released.

Let me know if the issue is solved correctly.

Have a great day,

Best Regards,

Jon

**Comment by joshidp** [comment]
Thanks, issue has been fixed.
