### ISSUE TITLE
Request: Please implement ContainsKey for dictionary type 

### ISSUE THREAD

**Issue by joshidp** [zzzprojects/System.Linq.Dynamic.Core#384]
Hi,

Thanks for the great work.

Please implement ContainsKey for the dictionary ,
Enumerable.Empty<string>() for the enumerable.

Thanks

**Comment by JonathanMagnan** [comment]
Hello @joshidp ,

Thank you for reporting, we will look if that's possible.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @joshidp ,

The v1.1.3 has been released.

The library should now support ContainsKey from a dictionary. Here are some example: https://github.com/zzzprojects/System.Linq.Dynamic.Core/blob/master/test/System.Linq.Dynamic.Core.Tests/MikArea/Dictionary.cs

However, I do not think we will do the `Enumerable.Empty<T>()` as this moment, as it's currently harder to support it.

Let me know if the `ContainsKey` works as expected.

Best Regards,

Jon
