### ISSUE TITLE
Question: Generic and Param based Custom Type Methods Support

### ISSUE THREAD

**Issue by joshidp** [zzzprojects/System.Linq.Dynamic.Core#386]
Hello,

Thanks for the awesome work.

I'm using your lib to write json configurable rules. I want to used generic and param based custom type methods as Utility methods. Below is a sample json config snippet.

`{"expression": "Utilities.ConvertToArray(\"xyz\",\"abc\")"}`

and below is the method with param

``` cs
 public static string[] ConvertToArray(params string[] values)
        {
            if (values == null)
            {
                return new string[0];
            }

            return values.ToArray();
        }
```

When I try to call DynamicExpressionParser.ParseLambda method with above expression it fails with an error saying "No method called ConvertToArray found in Utilities". Please not normal method without param works just fine.

I want to create an array but since that was not possible in the expression directly using your lib I tried using the Utility method.

Similarly, generic methods also doesn't work. 

Please help in providing a solution.

Thanks

**Comment by JonathanMagnan** [comment]
Hello @joshidp ,

Depending on your requirement, I might recommend you our other library instead: https://eval-expression.net/

This library is not free (unless you use only the LINQ part), but allow you to do pretty much anything such as using static method that you have created (You will need to notify our library by Registering the type).

If the only method not supported you want is creating an array, we might add this in this library as we see a value here. However, if you want to go a lot deeper than this library `System.Linq.Dynamic.Core` will probably not allow it unless our other library (C# Eval Expression) which supports pretty much everything.

Let me know if all you are looking for is creating an array or not.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by joshidp** [comment]
Thanks @StefH for the reply.


If I use your example of Class X the solution works but if I try to use y example I still get and error "System.Linq.Dynamic.Core.Exceptions.ParseException: 'No applicable method 'ConvertToArray' exists in type 'Utils''
"

In you example, Values prop is already a string array but what I am trying to do is pass string param and get the array back. Show below

**Utility class**
 ```
 [DynamicLinqType]
    public static class Utils
    {
        public static string[] ConvertToArray(params string[] values)
        {
            if (values == null)
            {
                return new string[0];
            }

            return values.ToArray();
        }
    }
```

**Usage**
```

  var externals = new Dictionary<string, object>
            {
                {"Users", false},
                {"x", new[] { "a", "b", "c" } },
                {"y", 2},
            };

            string query = "Utils.ConvertToArray(\"a\",\"b\")";
            LambdaExpression expression = DynamicExpressionParser.ParseLambda(null, query, externals);
            Delegate del = expression.Compile();
            var result = del.DynamicInvoke();
```
Please tell how this issue can be resolved.

Thanks! in advance.

**Comment by StefH** [comment]
I think the *params* is not supported, so you can only use `string[] values` or `string value`.
Maybe you could just use `object value` and determine if it's an string or string-array yourself?
But I think that passing `\"a\",\"b\"` will be detected as 2 separate parameters, and not a params-string-array.

**Comment by joshidp** [comment]
ok, Thanks.

For now I'm thinking to write overloaded methods to return string[], it should suffice for limited set of values.

```
public static string[] ConvertToArray(string value1, string value2)
public static string[] ConvertToArray(string value1, string value2, string value3)
public static string[] ConvertToArray(string value1, string value2, string value3, string value4)
public static string[] ConvertToArray(string value1, string value2, string value3, string value4, string value5)
```

Thanks

**Comment by JonathanMagnan** [comment]
Hello @joshidp ,

Thank @StefH  for pointing us out the `DynamicLinqType`, we were not aware of it and seem to be very useful for plenty of scenarios.

The v1.1.3 has been released. The library should now support `params` parameter (You can pass it like in your example but cannot yet create an array such as `new string[] { "a", "b" }`).

Let us know if everything works as expected.

**Comment by StefH** [comment]
@JonathanMagnan 

I think that the original method from @joshidp is still not recognized?

``` cs
public static string[] ConvertToArray(params string[] values)
        {
            if (values == null)
            {
                return new string[0];
            }

            return values.ToArray();
        }
```

With
``` cs
public class X
{
  public string[] Values { get; set; }
}

var list = new[] { new X { }, new X { Values = new[] { "a", "b" } } }.AsQueryable();
var result = list.Select(config, "Utils.ConvertToArray(Values)").ToDynamicList<string[]>();
```

Still throws:

> Unhandled Exception: System.Linq.Dynamic.Core.Exceptions.ParseException: No applicable method 'ConvertToArray' exists in type 'Utils'

**Comment by JonathanMagnan** [comment]
You are right, we forget probably the most essential case!

The v1.1.5 has been released

**Comment by JimmyLzy** [comment]
@StefH @JonathanMagnan 
Hi team, this library is really powerful and I'm really appreciate your awesome work and support. Discussion within this issue has helped me to figure out how to define own custom static function and apply it in dynamic linq to object. However, I am wondering if there is a way we can apply C# extension function.

**Comment by JonathanMagnan** [comment]
Hello @JimmyLzy ,

When you say `C# extension function`, you mean `C# extension method` right?

Unless I'm wrong, extension methods are not yet supported.

We will look if that's possible or not to support basic scenario at least.

**Comment by JonathanMagnan** [comment]
What do you mean @JimmyLzy  by `works fine in local`.

Unless I'm wrong, the library doesn't support yet extension methods when I checked yesterday.

**Comment by JimmyLzy** [comment]
@JonathanMagnan I meant running code in my windows laptop

**Comment by JimmyLzy** [comment]
@JonathanMagnan  I managed to get more exception message Expression expected (at index 41).

**Comment by JonathanMagnan** [comment]
Hello @JimmyLzy ,

Just to let you know that a first version to support the extension method has been made.

We are currently completing the testing phase and a new version should be available within a few days.

**Comment by JonathanMagnan** [comment]
Hello @JimmyLzy ,

The v1.1.6 has been released which should now support extension methods.

See those unit tests example: https://github.com/zzzprojects/System.Linq.Dynamic.Core/blob/master/test/System.Linq.Dynamic.Core.Tests/Parser/DynamicLinqTypeTest.cs#L30

Let me know if everything works as expected.

**Comment by Feroks** [comment]
@JonathanMagnan i think it does not work, if extension uses generics.

**Comment by JonathanMagnan** [comment]
You are right @Feroks ,

We did it very basic for the first version. We support some simple scenarios.

I'm currently not sure if we wish to go further and support more scenario or redirect people to our other library [C# Eval Expression](https://eval-expression.net/) which handle more complex overload resolution.

If you wish we try it, create a new issue with an example of a method and I will ask my developer to look at it. I believe it could be possible to handle one generic parameter (which is more than enough for a lot of cases) but supporting multiple generic parameters would be too long for now.
