### ISSUE TITLE
Version from the dll is 0.0.0.0 (microsoft.entityframeworkcore.dynamiclinq)

### ISSUE THREAD

**Issue by StefH** [zzzprojects/System.Linq.Dynamic.Core#388]
I just noticed that the dll version is 0.0.0.0 for the latest nuget version `1.1.2`:
![image](https://user-images.githubusercontent.com/249938/84313161-6bb10a80-ab66-11ea-91d2-e60e827aa605.png)

&

![image](https://user-images.githubusercontent.com/249938/84313412-c5b1d000-ab66-11ea-9da7-6ba2c671e827.png)

The `System.Linq.Dynamic.Core` has a dll version (1.1.2). However this should also be `1.0.0.0`.

Because the version is `0.0.0.0` this gives problems using the *Like* functionality.

Can you please create new NuGet packages and make all versions are `1.0.0.0` ?

**Comment by JonathanMagnan** [comment]
That's weird,

I will release a new version during the weekend.

I will review all dll version from all library as well

**Comment by JonathanMagnan** [comment]
Hello @StefH ,

The v1.1.3 has been released. The FileVersion will now be the same as the product version.

**Comment by StefH** [comment]
@JonathanMagnan 
Because of the file-version fix: another fix is needed https://github.com/zzzprojects/System.Linq.Dynamic.Core/pull/390 else the DynamicFunctions class is not loaded anymore.

**Comment by JonathanMagnan** [comment]
Yup, thank again for your insight.

Your pull has been merged and released in v1.1.5
