### ISSUE TITLE
Dynamic LINQ - Repository Future

### ISSUE THREAD

**Issue by JonathanMagnan** [zzzprojects/System.Linq.Dynamic.Core#392]
## System.Linq.Dynamic vs System.Linq.Dynamic.Core
As you may already know, many GitHub repository of the [original code](https://weblogs.asp.net/scottgu/dynamic-linq-part-1-using-the-linq-dynamic-query-library) exists.
 
Since the last month, the 2 most popular repositories are owned by our company:

- https://github.com/zzzprojects/System.Linq.Dynamic (no longer supported since 2016)
- https://github.com/zzzprojects/System.Linq.Dynamic.Core
 
Since the System.Linq.Dynamic.Core is the most advanced repository; we recommend to use it from now (no point to support 2 similar libraries). Also, we intend to make it very clear that the System.Linq.Dynamic is deprecated:

- Mark the NuGet package as deprecated
- Publish a new version and change the description to make it very clear (We cannot change any descriptions of published packages)
- Create a branch named "legacy" that will contain the current code
- Remove everything from the master, but keep the readme file
- Update the readme file by making it clear that the library should not be used and that the code can still be found in the "legacy" branch
 
## EF Core Release Strategy
EF Core evolves very fast. Almost every year, a new major version is available.
 
The current package: https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.DynamicLinq still has a dependency on EF Core 1.1. However, if we want to support new features, we need to upgrade the dependency version.
 
At least, there are 3 choices available:

- To support only the latest EF Core version (A lot of people still use EF Core 2.x, which is not a good idea)
- To create a different package for every major EF Core version (it will generate a way to many different packages over time)
- To use the major version as the EF Core version indicator.
 
### Use the major version as the EF Core version indicator
So far, that's our preferred choice.
 
The following packages related to EF Core use this strategy:

- https://www.nuget.org/packages/LinqKit.Microsoft.EntityFrameworkCore/
- https://www.nuget.org/packages/Z.EntityFramework.Extensions.EFCore/
- https://www.nuget.org/packages/Z.EntityFramework.Plus.EFCore/
 
Since some of the products we own, such as EF Extensions and EF Plus, already use this strategy, it makes sense to continue with the same one.
 
## Will the library stay FREE and OPEN SOURCE?
Of course!
 
Our company has some paid libraries, but we also support various free libraries:

•	[HTML Agility Pack](https://html-agility-pack.net/)
•	[EF Dynamic Filters](https://entityframework-dynamicfilters.net/)
•	[EF Effort](https://entityframework-effort.net/)
•	[EF Graph Diff](https://github.com/zzzprojects/GraphDiff)
•	[EF Plus](https://entityframework-plus.net/)
•	And many more.
 
These libraries are free and will stay the same!
 
## Implementation
Those decisions are not yet final. That said, we value your opinion, and any suggestion will be taken into consideration!
 
We are planning on making a final decision and implement it at the beginning of August.

**Comment by joshidp** [comment]
Hi @JonathanMagnan 

In the NuGET Source Repo link we are redirected to below link, Can it be changed to this repo?

https://github.com/StefH/System.Linq.Dynamic.Core

Thanks

**Comment by JonathanMagnan** [comment]
Thank @joshidp  for reporting,

We fixed it in the v1.1.7

I will look soon with him how we can handle this problem, as the redirection is currently broken with the fork that has been created.

**Comment by JonathanMagnan** [comment]
The part about specifying `System.Linq.Dynamic` is now legacy has been completed.

Next week, we should start and create projects for every EF Core version.
