### ISSUE TITLE
OrderByDynamic: Value cannot be null. (Parameter 'type')  

### ISSUE THREAD

**Issue by wtujvk** [zzzprojects/System.Linq.Dynamic.Core#394]
Throw Exception: System.ArgumentNullException:“Value cannot be null. ”
// Type: System.Linq.EnumerableDynamic
// Assembly: Z.Expressions.Eval, Version=4.0.1.0, Culture=neutral, PublicKeyToken=59b66d028979105b
// MVID: 1B08F7D4-0A7D-4667-AB72-4B641D269972
// Assembly location: C:\Users\xx\.nuget\packages\z.expressions.eval\4.0.1\lib\netstandard2.1\Z.Expressions.Eval.dll
nuget: System.Linq.Dynamic.Core 1.1.5

```csharp
[TestClass]
public class Demo
{
    [TestMethod]
    public void OrderByDynamicTest()
    {
      IEnumerable<Model> list = new List<Model>()
      {
       new Model(){ Name = "jack", Age = 44}
      };
        var orderExpression = "name asc";
        var result = list.OrderByDynamic(orderExpression);
        Assert.IsNotNull(result);
    }
 }

public class Model
 {
      public string Name { get; set; }

      public int Age { get; set; }
 }
```

**Comment by JonathanMagnan** [comment]
Hello @wtujvk ,

You are currently mixing `System.Linq.Dynamic.Core` syntax with the [C# Eval Expression](https://eval-expression.net/) library

## System.Linq.Dynamic.Core

You must use the `OrderBy` method, not `OrderByDynamic` which is belongs our other library.

Here are some example of use:
- https://dynamic-linq.net/basic-simple-query#ordering-results
- https://dotnetfiddle.net/GdxsMG

## C# Eval Expression

Require the same syntax as C#, so "x => x.Name"

Let me know if everything is clear,

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by wtujvk** [comment]
use nuget  `System.Linq.Dynamic.Core 1.2.8`, it work ok like this:

`using System.Linq;`
`using System.Linq.Dynamic.Core;`

`var result = list.AsQueryable().OrderBy(orderExpression);`
