### ISSUE TITLE
SQL between and query

### ISSUE THREAD

**Issue by JimmyLzy** [zzzprojects/System.Linq.Dynamic.Core#395]
Hi team,
Are there any support for between sql query?
eg.
select * from table where value between 20 and 30

Thank you,
Jimmy

**Comment by JonathanMagnan** [comment]
Hello @JimmyLzy ,

The library doesn't create `SQL Statement`.

ORM such as `Entity Framework` does.

So if they have some special method that does it, then we can add it such as the `Like` operator for EF: https://dynamic-linq.net/advanced-entityframework#like-operator

Let me know if that answer correctly to your question

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
