### ISSUE TITLE
Dictionary parameter issue

### ISSUE THREAD

**Issue by b0bi79** [zzzprojects/System.Linq.Dynamic.Core#397]
If pass Dictionary as a parameter for a lambda expression, then DynamicInvoke will return the first result each time. It looks like a cached result is returning.

```c#
        [Fact]
        public void EvalDictionaryParams2()
        {
            object CreateDicParameter(string name) => new Dictionary<string, object>
                {{"Name", new Dictionary<string, object> {{"FirstName", name }}}};

            var config = new ParsingConfig()
            {
                CustomTypeProvider = new DefaultDynamicLinqCustomTypeProvider()
            };
            var parType = new Dictionary<string, object>().GetType();
            var lambda = DynamicExpressionParser.ParseLambda(config, new [] {Expression.Parameter(parType, "item")}, typeof(object), "item.Name.FirstName").Compile();
            lambda.DynamicInvoke(CreateDicParameter("Julio")).Should().Be("Julio");
            lambda.DynamicInvoke(CreateDicParameter("John")).Should().Be("John");  // Failure. DynamicInvoke returns "Julio"
        }
```

**Comment by JonathanMagnan** [comment]
Hello @b0bi79 ,

Thank you for reporting.

We will look at it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @b0bi79 ,

Just to let you know we fixed the issue. We will complete our test tomorrow and probably release it during the weekend.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @b0bi79 ,

The v1.1.8 has been released.

Let us know if everything is now working as expected.

Best Regards,

Jon
