### ISSUE TITLE
ParseException with Expressions containing Convert method

### ISSUE THREAD

**Issue by kyleherzog** [zzzprojects/System.Linq.Dynamic.Core#401]
I'm trying to take expressions created on a client, convert them to string by calling `ToString`, pass the string values to a web endpoint, and then convert them back to expression objects using `DynamicExpressionParser.ParseLambda`.  In most cases this works.  However, if i have an expression that results in a `Convert` method being called, I get the following exception.
```
System.Linq.Dynamic.Core.Exceptions.ParseException: '.' or '(' or string literal expected
```
The following simplified test case exhibits the issue.
```C#
Expression<Func<byte, bool>> originalExpression = x => x == 1;
var expressionText = originalExpression.ToString();
Console.WriteLine(expressionText);
// Output: x => (Convert(x, Int32) == 1)
var expression = DynamicExpressionParser.ParseLambda<long, bool>(new ParsingConfig(), false, expressionText);
```

**Comment by JonathanMagnan** [comment]
Hello @kyleherzog ,

Thank you for reporting, we will look at it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @kyleherzog ,

We checked at your issue and I don't think we will support your scenario for now.

What you are currently providing is not an expression, but a string representation which is not exactly a lambda expression.

For example, the following lambda expression working:

```csharp
var lambdaExpression = "x => Convert.ToInt32(x) == 1";
var expression = DynamicExpressionParser.ParseLambda<long, bool>(new ParsingConfig(), false, lambdaExpression);
var r1 = expression.Compile()(1);
```

But in your case, the expression string shows the following convert as `Convert(x, Int32)` which is not valid.

Let me know if that explains correctly why that's currently not working.

Best Regards,

Jon

**Comment by StefH** [comment]
@kyleherzog 
Maybe this library https://github.com/esskar/Serialize.Linq can help you when you want to serialize / deserialize linq.

**Comment by StefH** [comment]
Closing...
