### ISSUE TITLE
Add support to Max and Min functions

### ISSUE THREAD

**Issue by DelvisR** [zzzprojects/System.Linq.Dynamic.Core#404]
How to implement Max and Min aggregate functions:

public static object Max(this IQueryable source, string selector, params object[] values)

public static object Min(this IQueryable source, string selector, params object[] values)

**Comment by JonathanMagnan** [comment]
Hello @DelvisR ,

If we try to support it, it will be without the `params object[] values` parameter.

Will it still be good for you?

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @DelvisR ,

As expected `Min` and `Max` are already supported: https://dotnetfiddle.net/mvH6yJ

One problem by adding your overload to `IQueryable`, is that some ORM such as `Entity Framework` will not be compatible with it. So it might be better to stick with the overload that `IQueryable` provide to avoid some future confusion.

**Comment by DelvisR** [comment]
Even without parameters it would be very helpful.

Thank you,

**Comment by DelvisR** [comment]
> 
> 
> Hello @DelvisR ,
> 
> As expected `Min` and `Max` are already supported: https://dotnetfiddle.net/mvH6yJ
> 
> One problem by adding your overload to `IQueryable`, is that some ORM such as `Entity Framework` will not be compatible with it. So it might be better to stick with the overload that `IQueryable` provide to avoid some future confusion.

Thank you very much!
