### ISSUE TITLE
Does it support var query = dbContext.Set("Customers"),please?

### ISSUE THREAD

**Issue by effapp** [zzzprojects/System.Linq.Dynamic.Core#405]
Does it support var query = dbContext.Set("Customers"),please?

I hope that:

var query =  **dbContext.Set("Customers")**
    .Where("City == @0 and Orders.Count >= @1", "London", 10)
    .OrderBy("CompanyName")
    .Select("new(CompanyName as Name, Phone)");

**Comment by JonathanMagnan** [comment]
Hello @effapp ,

We will look at it,

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @effapp ,

Sorry for the long waiting,

The `SetDynamic` feature has been added in our EF Plus library: https://github.com/zzzprojects/EntityFramework-Plus/releases/tag/v3.0.61

We currently believe that feature related to Entity Framework should be part of our free library EF Plus instead which try to make it easier for developers to use EF.

Let me know if that solution can work for you.

Best Regards,

Jon

**Comment by StefH** [comment]
@effapp 

Is the code `dbContext.Set("Customers")` from EntityFramework ? Or from EntityFramework Core?

**Comment by StefH** [comment]
Closing...
