### ISSUE TITLE
DynamicExpression Missing

### ISSUE THREAD

**Issue by jcmontoya** [zzzprojects/System.Linq.Dynamic.Core#408]
When I use the NuGet package version 1.2.0, I get the error "DynamicExpression Missing" in the following code:

``` c#
DynamicProperty[] props = new DynamicProperty[] {
    new DynamicProperty("Name", typeof(string)),
    new DynamicProperty("Birthday", typeof(DateTime)) };
Type type = DynamicExpression.CreateClass(props);
object obj = Activator.CreateInstance(type);
t.GetProperty("Name").SetValue(obj, "Albert", null);
t.GetProperty("Birthday").SetValue(obj, new DateTime(1879, 3, 14), null);
Console.WriteLine(obj);
```

**Comment by StefH** [comment]
Hello @jcmontoya ,

You need to use `DynamicClassFactory`, see the documentation: https://dynamic-linq.net/advanced-create-dynamic-class

**Comment by StefH** [comment]
Dear @jcmontoya, closing this issue now. In case you have more questions, just reply here or open a new issue.
