### ISSUE TITLE
Can't apply the library while using reflection emit with dynamic linq

### ISSUE THREAD

**Issue by KhoiNguyenICT** [zzzprojects/System.Linq.Dynamic.Core#411]
Hi!
Today, i use reflection emit for generate dynamic entity for entityframework.
But library cannot support type IQueryable for dynamic query
Can you give me a solution for this problem!
Thank you so much!

**Comment by JonathanMagnan** [comment]
Hello @KhoiNguyenICT ,

Could you provide a full example of what you would want to do.

It will help my developer to get started with your request as I'm not fully sure to understand it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by KhoiNguyenICT** [comment]
![image](https://user-images.githubusercontent.com/25011643/90644560-10cf1a00-e25f-11ea-9dec-838dd05e9609.png)
Hi @JonathanMagnan 
This is example for my issue 
In the line 132 to line 134 i try build dynamic entity from my setting 
But in the line 135 i use dynamic linq for find item, but library not support query with IQueryable
This is class for job build dynamic type use reflection emit: [Link](https://raw.githubusercontent.com/Cell-Application/cell-core-backend/develop/src/Cell.Packages/Cell.Package.Extensions/TypeHelperExtensions.cs?token=AF62LOZFTHJASQS6GTXTZF27HUY2Y)
Thanks @JonathanMagnan

**Comment by JonathanMagnan** [comment]
Hello @KhoiNguyenICT ,

If you wish we try to find a solution, we will need a **full runnable project** that contains the minimum code to reproduce it.

**Comment by KhoiNguyenICT** [comment]
Hi @JonathanMagnan 
This is example for use refection emit: Link [https://github.com/giangcoi48k/test-assembly-emit](https://github.com/giangcoi48k/test-assembly-emit)
Thanks @JonathanMagnan

**Comment by JonathanMagnan** [comment]
Hello @KhoiNguyenICT ,

I tried a few examples with `System.Linq.Dynamic.Core` and `Z.Expressions.Eval` library and both are working as expected.

```csharp
_dbContext.Add(obj);
_dbContext.SaveChanges();

var set = _dbContext.Set(type);
//var q2 = set.Where("Name == \"test\"");
//var q2 = set.WhereDynamic("x => x.Name == 'test'");
var q3 = set.SingleOrDefaultDynamic("x => x.Name == 'test'");
return Ok(_dbContext.Set(type));
```

Both libraries support IQueryable, so I'm not really sure how to reproduce this issue.

**Comment by JonathanMagnan** [comment]
Hello @KhoiNguyenICT 

Since our last conversation, we haven't heard from you. 

As mentioned in my previous message, both libraries support IQueryable. 

Don't hesitate to provide further information, so that we can help you better.

Best regards,

Jon

**Comment by KhoiNguyenICT** [comment]
@JonathanMagnan 
Thank you so much
I tryed for this. Expression had good for template 
```
var record = _context.Set(type).SingleOrDefaultDynamic($"x => x.Id.Equals(@Id)", new { Id = id });
```

**Comment by KhoiNguyenICT** [comment]
@JonathanMagnan 
But I have not figured out how to re-initialize **Type** of **ModuleBuilder** when **DefineType** was successful before. Do you have any ideas for this problem?. 
Thanks!

**Comment by JonathanMagnan** [comment]
Sorry @KhoiNguyenICT , I do not understand what you want.

**Comment by KhoiNguyenICT** [comment]
@JonathanMagnan 
My problem has been solved. 
Thank you so much!
