### ISSUE TITLE
Contains search in an Enum

### ISSUE THREAD

**Issue by ste1nstone** [zzzprojects/System.Linq.Dynamic.Core#414]
Hi

I try to do an dynamic request which returns me all entries where an enum column contains a special value.
Unfortunately I could not find a solution the archieve this with a dynamic expression.

It seems like EF core has also a problem with this why I used the workaround from the following issue [https://github.com/dotnet/efcore/issues/20604](https://github.com/dotnet/efcore/issues/20604)
But with this I was able to do the request
`.Where(s => ((string)(object)s.Product).ToLower().Contains("test"))`

If I now try the same request as dynamic string
`.Where("((string)(object)Product).ToLower().Contains(\"test\"))")`
I receive the following issue `'.' or '(' or string literal expected (at index 8)`

Has someone an idea how I can fix this problem?

Thanks and best regards
Philipp

**Comment by JonathanMagnan** [comment]
Hello @ste1nstone ,

Unfortunately, we didn't find a working solution with Dynamic LINQ.

However, it is already possible to do such dynamic query with our other library: [C# Eval Expression](https://eval-expression.net/linq-dynamic) (LINQ extension method part are free)

Here is an online example: https://dotnetfiddle.net/qcbJ5I

Best Regards,

Jon
