### ISSUE TITLE
Expression is missing an 'as' clause

### ISSUE THREAD

**Issue by chriswarr** [zzzprojects/System.Linq.Dynamic.Core#417]
For the below code I get "Expression is missing an 'as' clause" on the call to ParseLambda.  This is my first time using this library so not sure if what i'm doing is ok or not?

           
```
            const string exp = @"version > new System.Version(""8.3.0.689"")";
            var p = Expression.Parameter(typeof(System.Version), "version");
            var l = System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(new[] { p }, null, exp);

            var version = new System.Version("8.3.0.600");

            var result = l.Compile().DynamicInvoke(version);

```

**Comment by JonathanMagnan** [comment]
Hello @chriswarr ,

This library is more for LINQ Dynamic.

I might be wrong but in your case, you look more like you want a runtime compiler.

In this case, I would suggest you try our [C# Eval Expression](https://eval-expression.net/) library (however, the library is not free)

Here is a working online example of what you want to try to achieve: https://dotnetfiddle.net/Ze57pA

```csharp
var version = new System.Version("8.3.0.600");

// Method 1 - With Compile
const string exp = @"version > new System.Version(""8.3.0.689"")";
var compiled = Eval.Compile<Func<System.Version, bool>>(exp, "version");
Console.WriteLine(compiled(version));

// Method 2 - With Execute
Console.WriteLine(Eval.Execute(exp, new { version }));
```

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by chriswarr** [comment]
Ah, thanks you so much.  I understand.  I will check out the library.  Looks perfect, I was using Roslyn for this but found it uses too much memory.

**Comment by Zeinabam** [comment]
Hello @chriswarr,

Don't hesitate to contact us for further assistance once you try it!

Best regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @chriswarr ,

Don't hesitate to contact us for further assistance once you try it!

Best regards,

Jon
