### ISSUE TITLE
How to set global date format conversion？not used utc

### ISSUE THREAD

**Issue by Angus221** [zzzprojects/System.Linq.Dynamic.Core#420]
Model

![image](https://user-images.githubusercontent.com/21039420/93205575-9d9bc380-f78a-11ea-834f-2bca0a02f9f6.png)

Code like :
`.Where("RequestDate>=\"2020/08/07 00:00:00\"")`

or
`.Where("RequestDate>=@1",Datetime.Now)`

I've tried two ways to use it, but still format as utc，
Exception
![image](https://user-images.githubusercontent.com/21039420/93205151-ef901980-f789-11ea-8b08-bdb28d168e93.png)

**Comment by JonathanMagnan** [comment]
Hello @Angus221 ,

In which format do you wish your date time? How you usually do it without `LINQ Dynamic` (so with purely LINQ)?

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by Angus221** [comment]
> Hello @Angus221 ,
> 
> In which format do you wish your date time? How you usually do it without `LINQ Dynamic` (so with purely LINQ)?
> 
> Best Regards,
> 
> Jon
> 
> **Performance Libraries**
> `context.BulkInsert(list, options => options.BatchSize = 1000); `
> [Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) • [Dapper Plus](http://dapper-plus.net/)
> 
> **Runtime Evaluation**
> `Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
> [C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

I wish date time format like "yyyy/MM/dd H:mm:ss"
Puerly Linq was not thorw exception with date time in the "where" method,
 the output sql query contains(Linq dynamic):
`[RequesteDate] > '2019-05-10T13:03:17.0000000+02:00'`
It doesn't work in the sql server.

**Comment by Angus221** [comment]
> Hello @Angus221 ,
> 
> In which format do you wish your date time? How you usually do it without `LINQ Dynamic` (so with purely LINQ)?
> 
> Best Regards,
> 
> Jon
> 
> **Performance Libraries**
> `context.BulkInsert(list, options => options.BatchSize = 1000); `
> [Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) • [Dapper Plus](http://dapper-plus.net/)
> 
> **Runtime Evaluation**
> `Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
> [C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

```
         var config = new System.Linq.Dynamic.Core.ParsingConfig() {
                DateTimeIsParsedAsUTC = false
            };
...
 .Where(config, "view.IsDeleted=false And "RequestDate>=@0 ",Datetime.Now )
```
I try use config ,but it doesn't work

**Comment by Angus221** [comment]
My  EF version   EntityframeworkCore  5.0-Preview8

**Comment by StefH** [comment]
@Angus221 What happens if you just use normal LINQ (so not dynamic), does that work for you?

**Comment by Angus221** [comment]
> @Angus221 What happens if you just use normal LINQ (so not dynamic), does that work for you?

 Normal LINQ has no exception,but my query columns should be configured dynamically，so I need dynamic.

Could you help me test the "datetime" type with EF Core 5-preview8 ?

**Comment by StefH** [comment]
@Angus221 
As a workaround, you could try to set the `Thread.CurrentThread.CurrentCulture` to the culture which will generate the correct DateTime format.

See: https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.defaultthreadcurrentculture?redirectedfrom=MSDN&view=netcore-3.1#System_Globalization_CultureInfo_DefaultThreadCurrentCulture

**Comment by Angus221** [comment]
> @Angus221
> As a workaround, you could try to set the `Thread.CurrentThread.CurrentCulture` to the culture which will generate the correct DateTime format.
> 
> See: https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.defaultthreadcurrentculture?redirectedfrom=MSDN&view=netcore-3.1#System_Globalization_CultureInfo_DefaultThreadCurrentCulture

Thanks for your reply ，I try it，but it doesn't work，still the same format.
![image](https://user-images.githubusercontent.com/21039420/93553676-2e9ab680-f9a6-11ea-82a3-97a4f29d330b.png)

**Comment by Angus221** [comment]
My code still have the exception with  System.Linq.Dynamic.Core 1.2.5 , why closed the issues?

![image](https://user-images.githubusercontent.com/21039420/99218479-8bcfae80-2815-11eb-9905-6824e27a836a.png)
