### ISSUE TITLE
What should be the statement to support the IN operator in where clause?

### ISSUE THREAD

**Issue by arivera12** [zzzprojects/System.Linq.Dynamic.Core#421]
I have a list of ids.

On regular entity framework would something like this 

`DbContext.Categories.Where(w => ids.Contains(w.CategoryId)).ToList()`

how can I achieve the same using dynamic linq?

CategoryId is known at runtime and I extract it from the DbContext.Model so I need this to be dynamic.

So it should be something closer to this but I could not get it to work

`DbContext.Set<T>().Where($"{tablePrimaryKey}.Contains(@0)", ids).ToList();`

I read this documentation https://dynamic-linq.net/basic-query-operators 

but the contains operator is missing there 

but it's seem to be supported since its being showed here as the first example in the home page

https://dynamic-linq.net/

**Comment by arivera12** [comment]
Also the 4 big red buttons that says `Read More` are broken in the main page https://dynamic-linq.net/

**Comment by arivera12** [comment]
I tried this fiddle https://dotnetfiddle.net/CXfG4d regarding on contains operators and works properly but how to do it for collection instead?

**Comment by arivera12** [comment]
I found this in a closed issue https://github.com/zzzprojects/System.Linq.Dynamic.Core/issues/314 

Why this is not on the main docs?

**Comment by belfortmaycon** [comment]
@arivera12 did it works for you?

I'm with same issue, but the filter is only executing the first parameter:

```
query.Where(config, "status in (@0)", new string[] {"DRAFT", "ACTIVE"}).ToListAsync(ct.Token);
```

This only do `status = 'DRAFT'` and not `status in ("DRAFT", "ACTIVE")`. How to do like `in` SQL statement?

Thanks.

**Comment by arivera12** [comment]
I ended using another approach

**Comment by arivera12** [comment]
Try removing the parentheses

**Comment by belfortmaycon** [comment]
> Try removing the parentheses and just do it like this #314

Thanks @arivera12. I just figure out that this approach of #314 only takes the first value of array. 
So I had to put more params to get each value from my array.

`query.Where(config, "status in (@0, @1, @...)", new string[] {"DRAFT", "ACTIVE", "..."}).ToListAsync(ct.Token);`

**Comment by arivera12** [comment]
@belfortmaycon makes sense that should work and behave like that.
