### ISSUE TITLE
How to use `Convert` in expression?

### ISSUE THREAD

**Issue by wakuflair** [zzzprojects/System.Linq.Dynamic.Core#422]
I see `Convert` is available  from the [doc](https://github.com/zzzprojects/System.Linq.Dynamic.Core/wiki/Dynamic-Expressions#types), however my expression `Convert.ToInt32("123") > @0` raises "could not be translated" exception.

Am I using it wrong?

**Comment by StefH** [comment]
Hello @wakuflair,

This should just work fine. See this https://dotnetfiddle.net/W5kF4k.

(See new doc : https://dynamic-linq.net/expression-language#accessible-types)
