### ISSUE TITLE
Produce Dynamic LINQ strings from expression trees

### ISSUE THREAD

**Issue by zspitz** [zzzprojects/System.Linq.Dynamic.Core#423]
I've written a [library](https://github.com/zspitz/ExpressionTreeToString/) producing various string representations of expression trees. I am now considering a Dynamic LINQ representation. In other words, from an expression tree like this:
```csharp
Expression<Func<Person, bool>> expr = p => p.BirthDate.DayOfWeek == DayOfWeek.Tuesday
```
produce a string like the following:
```none
$.BirthDate.DayOfWeek = Tuesday
```
Does System.Linq.Dynamic.Core have such functionality?

Also, for this purpose, where can I find the most up-to-date documentation describing the System.Linq.Dynamic.Core string syntax?

**Comment by zspitz** [comment]
Something similar has been discussed in #230 .

**Comment by JonathanMagnan** [comment]
Hello @zspitz ,

No, Dynamic LINQ doesn't offer this kind of feature.

Perhaps david-garcia-garcia in the mentioned issue could maybe help you more.

The most up to date documentation which has been added during the summer can be found here: https://dynamic-linq.net/overview

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by zspitz** [comment]
@JonathanMagnan I am very pleased to let you know that as of version 3.2, the [ExpressionTreeToString](https://github.com/zspitz/ExpressionTreeToString) library can produce corresponding Dynamic LINQ for many expressions. For example:
```csharp
public class Person {
    public string LastName { get; set; }
    public string FirstName { get; set; }
    public DateTime DOB { get; set; }
}
Expression<Func<Person, bool>> filter = p => p => 
    p.LastName == "A" || 
    p.FirstName == "B" || 
    p.DOB == DateTime.MinValue || 
    p.LastName == "C" || 
    p.FirstName == "D";
Console.WriteLine(expr.ToString("Dynamic LINQ"));
// prints:
/*
    LastName in ("A", "C") || DOB == DateTime.MinValue || FirstName in ("B", "D")
*/
```
Please feel free to refer to the library in help and documentation.
