### ISSUE TITLE
How to GroupBy Nullable DateTime Year?

### ISSUE THREAD

**Issue by brainded** [zzzprojects/System.Linq.Dynamic.Core#424]
I have tried the following to get the group by to work for this but I am having trouble getting past the nullable issues.

.GroupBy("new (NullableDate.Year)") throws an exception because the Year property doesn't exist. Makes sense because the property is actually on Value.
.GroupBy("new (NullableDate?.Year)") throws an exception that you can't use an NP with the library. I found the exception in the source code and I kinda get why that isn't supported.
.GroupBy("new (NullableDate.Value.Year)") works! But then fails to materialize results because the value returned should be nullable.

Is there a supported way to do what I am trying to do here? Or even an unsupported workaround?

**Comment by StefH** [comment]
@brainded 
You could take a look at null propagation : https://dynamic-linq.net/advanced-null-propagation

**Comment by brainded** [comment]
@StefH Thank you!

I tried:
.GroupBy("new (np(NullableDate.Year, 0))") and got "No property or field 'Year' exists in type 'DateTime?" again. 
I also tried:
.GroupBy("new (np(NullableDate.Value.Year))")
and 
.GroupBy("new (np(NullableDate.Value.Year, 0))")
 and got "The binary operator NotEqual is not defined for the types 'System.DateTime' and 'System.Object'."

Is NP supported in the GroupBy method? Or just in the Where and Select methods? Seems like the examples using the NP operator are Objects with a property.... but this is a little different being a Nullable base type.

**Comment by StefH** [comment]
Hello @brainded, I'll investigate.

**Comment by zspitz** [comment]
@StefH Might I suggest the following? Ordinarily, `np` rewrites a member chain:
```
np(PropA.PropB.PropC)
```
into a ternary conditional:
```
(PropA != null && PropB != null) ? PropA.PropB.PropC : null
```
But if any of the property checks (`PropA` or `PropB`) return a nullable struct, the rewrite should be as follows:
```
(PropA.HasValue && PropA.Value.PropB.HasValue) ? PropA.Value.PropB.Value.PropC : null
```
This assumes it would be legal syntax to write:
```
PropA.PropB.PropC
```
even if `PropA` and `PropB` return nullable structs, and should be translated to :
```
PropA.Value.PropB.Value.PropC
```

**Comment by StefH** [comment]
Hello @brainded 

Can you please test NuGet 1.2.7-preview-02 from https://www.myget.org/F/system-linq-dynamic-core/api/v3/index.json ?

**Comment by StefH** [comment]
Dear @brainded, did you have time to test this?

**Comment by StefH** [comment]
Dear @brainded, did you have time to test this?

**Comment by StefH** [comment]
Dear @brainded,

I'll close this issue and merge to fix to master. A new version will be released within a week.

In case you still have questions or issues with the new release, just open a new Issue here.

**Comment by brainded** [comment]
@StefH finally getting some time to return back to this after the holidays. updating now and will report back! Thank you for looking into it!
