### ISSUE TITLE
System.Linq.Dynamic.Core - error message: “target object is not an ExpandoObject”

### ISSUE THREAD

**Issue by shbha1** [zzzprojects/System.Linq.Dynamic.Core#433]
The solution is using System.Linq.Dynamic.Core v1.2.3. When I try to call ToDynamicList() on the result of a GroupBy() call (as shown below), I get the 'target object is not an ExpandoObject' error message at runtime. A sample snippet is provided below as well as the exception message. Please let me know what I can do to resolve the issue. 

```csharp
public class Data {
		public string Currency { get; set; }
		public int PreTaxCost { get; set; }
}

public static void Main(){
//**variable values:**
string groupingKeySelector = "new (it.Currency as Currency )";
string selector = "new ( Sum(Convert.ToInt32(it.PreTaxCost)) as PreTaxCost, it.Key.Currency )";
//data object is a list of defined class 'Data'.   
data.AsQueryable<T>().GroupBy(groupingKeySelector,"it").Select(selector).Cast<T>().ToDynamicList(); //**Call that throws exception:*

//**Variation of call that throws same exception**
//data.AsQueryable().GroupBy("new (it.Currency as Currency )", "it").First()
}
```

**Exception Message**
'data.AsQueryable<T>().GroupBy(groupingKeySelector,"it").Select(selector).Cast<T>().ToDynamicList()' threw an exception of type 'System.InvalidOperationException'
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146233079
    HelpLink: null
    InnerException: null
    Message: "Target object is not an ExpandoObject"
    Source: "System.Linq.Dynamic.Core"
    StackTrace: "   at System.Linq.Dynamic.Core.Dynamic.DynamicIndex(Object obj, String name) in C:\\Users\\Jonathan\\Documents\\GitHub\\System.Linq.Dynamic.Core\\src\\System.Linq.Dynamic.Core\\Dynamic\\DynamicIndexer.cs:line 30\r\n   at lambda_method(Closure , Object )\r\n   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)\r\n   at System.Linq.GroupedEnumerable`3.GetEnumerator()\r\n   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()\r\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n   at System.Linq.Dynamic.Core.DynamicEnumerableExtensions.ToDynamicList(IEnumerable source) in C:\\Users\\Jonathan\\Documents\\GitHub\\System.Linq.Dynamic.Core\\src\\System.Linq.Dynamic.Core\\DynamicEnumerableExtensions.cs:line 87"
    TargetSite: {System.Object DynamicIndex(System.Object, System.String)}

**Comment by JonathanMagnan** [comment]
Hello @shbha1 ,

What's exactly the type of your `T`?

The following expression look to be fine: 

```csharp
var datas = new List<Data>() { new Data()}.AsQueryable<Data>().GroupBy(groupingKeySelector).Select(selector).ToDynamicList();
``` 

Unless I miss something, you cannot perform the last `Cast<T>` since the selector expression creates an anonymous type.

Best Regards,

Jon
