### ISSUE TITLE
Typo in IDynamicLinkCustomTypeProvider name

### ISSUE THREAD

**Issue by glopesdev** [zzzprojects/System.Linq.Dynamic.Core#438]
This might well be an annoying breaking change now, but just for future reference there might be a typo in the name of `IDynamicLinkCustomTypeProvider`. All the other concrete types use the correct spelling `Linq` while this one uses `Link`.

No complaints here, but just wanted to flag the inconsistency between type names.

**Comment by StefH** [comment]
@glopesdev Good catch ;-)

Best would be to add the correct class `IDynamicLinqCustomTypeProvider` and let the older interface extend this one in order to maintain backward compatibility.

**Comment by StefH** [comment]
https://github.com/zzzprojects/System.Linq.Dynamic.Core/pull/476

**Comment by StefH** [comment]
Changed interface name will be included in next version.
