### ISSUE TITLE
UriKind is not recognized in Uri constructor

### ISSUE THREAD

**Issue by zspitz** [zzzprojects/System.Linq.Dynamic.Core#442]
[**System.Uri**](https://docs.microsoft.com/en-us/dotnet/api/system.uri?view=netcore-3.1) is a [predefined type](https://github.com/zzzprojects/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/Parser/PredefinedTypesHelper.cs#L47).

The following:
```csharp
class Person { }

var selector = "Uri(\"https://www.example.com/\", UriKind.Absolute)";
var prm = Parameter(typeof(Person));
var parser = new ExpressionParser(new[] { prm }, selector, new object[] { }, ParsingConfig.Default);
var expr = parser.Parse(null);
```
fails with:
> **System.Linq.Dynamic.Core.Exceptions.ParseException**: 'No property or field 'UriKind' exists in type 'Person''

`UriKind` appears to be understood as a member of `Person`, and not as an enum value.

This is especially puzzling, because the following selector:
```csharp
var selector = "DateTime(633979008000000000, DateTimeKind.Local)";
```
is parsed just fine.

Could it be because there is a string literal within the first selector?

**Comment by StefH** [comment]
Hello @zspitz.

A small remark: you always use the `ExpressionParser` in your examples.

However this class does not exists in this repository, it should be `DynamicExpressionParser`.
https://github.com/zzzprojects/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/DynamicExpressionParser.cs

I think you are mistaken by another source code repository?

**Comment by zspitz** [comment]
@StefH I don't think so; it's right here: https://github.com/zzzprojects/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/Parser/ExpressionParser.cs .

**Comment by StefH** [comment]
You are correct.

However I think the DynamicExpressionParser is a more public class, and the ExpressionParser is more internal. That's why I was confused.

**Comment by StefH** [comment]
Hello @zspitz,

As a workaround you can use the integer value from the enum:
`Uri(\"https://www.example.com/\", 0)`

or

Use parameter:
``` c#
var selector = "Uri(\"https://www.example.com/\", @0)";
var prm = Expression.Parameter(typeof(Uri));
var parser = new ExpressionParser(new[] { prm }, selector, new object[] { UriKind.Absolute }, ParsingConfig.Default);
var expr = parser.Parse(null);
```

I'll investigate further on the details on this issue.

**Comment by StefH** [comment]
Solved by https://github.com/zzzprojects/System.Linq.Dynamic.Core/pull/450
