### ISSUE TITLE
Dynamic.DynamicIndex is exposed in the expression

### ISSUE THREAD

**Issue by hazzik** [zzzprojects/System.Linq.Dynamic.Core#448]
After upgrading from 1.1.8 to 1.2.0 I'm getting MethodNotSupported exception because my expression parser finds `Dynamic.DynamicIndex(object, string)` method in the expression. Strangely this method was introduced in 1.1.8, but the error started happening only in 1.2.0

Here are the failing tests: https://ci.appveyor.com/project/hazzik/nhibernate-core/builds/35962348/job/uvi4bg3jew1giw41/tests

**Comment by StefH** [comment]
Hello @hazzik, thanks for reporting.

I'll take a look.

**Comment by StefH** [comment]
@hazzik 
Can you provide a full source code example which displays this error?

**Comment by hazzik** [comment]
This is the simplest reproduction: https://dotnetfiddle.net/8Az1F6

It outputs
```text
Product[].Where(Param_0 => (DynamicIndex(Param_0.Properties, "Name") == Convert("First Product", Object)))
```
And DynamicIndex method call is a problem here.

**Comment by StefH** [comment]
Hello @hazzik,
I think I found a possible fix for this issue, however I want to test this using NHibernate.
Can you please provide me with a minimal console-app which can reproduce this issue?

**Comment by StefH** [comment]
Dear @hazzik , can you please provide a minimal console-app to reproduce this issue?

**Comment by hazzik** [comment]
I'll do it on or by this weekend.

**Comment by hazzik** [comment]
@StefH here is the console app with reproduction: https://github.com/hazzik/nhibernate-linq-dynamic

**Comment by StefH** [comment]
@hazzik Thank you very much, I'll copy this example to verify/reproduce the bug.

**Comment by StefH** [comment]
I'm working on a fix, but `dynamic` cannot be supported.

This is also not supported in normal code:
![image](https://user-images.githubusercontent.com/249938/106781725-a7469a80-6649-11eb-8f14-7d7739117b07.png)


The code is reworked that this scenario can work:
``` c#
class Product
	{
		public virtual Guid Id { get; set; }
		public virtual string Name { get; set; }
		public virtual IDictionary<string, object> Properties { get; set; }   // <--
	}
```

with:
``` c#
var properties1 = new Dictionary<string, object>
{
	["Name"] = "First Product",
	["Description"] = "First Description"
};
session.Save(
	new Product
	{
		Id = Guid.NewGuid(),
		Properties = properties1
	});

//var properties2 = new
//{
//	Name = "Second Product",
//	Description = "Second Description"
//};
//session.Save(
//	new Product
//	{
//		Id = Guid.NewGuid(),
//		Properties = properties2
//	});

dynamic properties3 = new ExpandoObject();
properties3.Name = "Third Product";
properties3.Description = "Third Description";
session.Save(
	new Product
	{
		Id = Guid.NewGuid(),
		Properties = properties3
	});
```

And this works:
``` c#
var x = session.Query<Product>().Where(p => p.Properties["Name"] == "First Product").ToList();

				var y = session.Query<Product>()
					.Where("Properties.Name == @0", "First Product")
					.ToList();
```

**Comment by hazzik** [comment]
> I'm working on a fix, but dynamic cannot be supported.

This code was working fine in 1.1.8. I know that dynamic expressions are supported in the linq-tree, but not supported on a language level. To properly support them it would probably be required to depend on Microsoft.CSharp package.

**Comment by StefH** [comment]
@hazzik 
I did test previous versions.

However it seems that 1.1.7 does work, and higher versions fail with:
`Unhandled exception. System.NotSupportedException: System.Object DynamicIndex(System.Object, System.String)`

Correct ?

**Comment by hazzik** [comment]
Yes, that is correct. I might misremembered the working version due it is being long time since I've tested it myself.

**Comment by StefH** [comment]
Can you try

https://www.myget.org/feed/system-linq-dynamic-core/package/nuget/System.Linq.Dynamic.Core/1.2.8-preview-01

**Comment by StefH** [comment]
Hello @hazzik , did you have time to test this preview package?

**Comment by hazzik** [comment]
Seems to be working:

- https://ci.appveyor.com/project/nhibernate/nhibernate-core/builds/37695599
- https://travis-ci.org/github/nhibernate/nhibernate-core/builds/758298116?utm_source=github_status&utm_medium=notification

Thanks

**Comment by StefH** [comment]
Hello @hazzik,

Thanks a lot for your analysis and help.

In some day(s) , I'll merge this PR and create a new official 1.2.8 NuGet package
