### ISSUE TITLE
Filter properties of a derived class on a list of base class objects

### ISSUE THREAD

**Issue by StefanKoenigMUC** [zzzprojects/System.Linq.Dynamic.Core#452]
Hi all,

the situation is as follows:

``` c#
public class A {}
public class B : A { 
public string MyProperty {get;set;}
}


ParameterExpression transaction = Expression.Parameter(typeof(A), "obj");
LambdaExpression eView = DynamicExpressionParser.ParseLambda(new ParameterExpression[] { LIST_OF_As_and_Bs}, typeof(bool), "obj.MyProperty = "asdf"");
var expressionView = eView.Compile();
```

unfortunately and somehow expected, this is not working - as A does obviously not contain "MyProperty" and during expression generation, an exception is thrown 

`System.Linq.Dynamic.Core.Exceptions.ParseException: 'No property or field 'MyProperty' exists in type 'A''
`
Is there any way available to build this expression in a way, that subclasses of A are also taken into consideration?

Thanks in advance for your help,

**Comment by zspitz** [comment]
You could cast to `B`:
```none
B(it).MyProperty
```
which corresponds to the compiled lambda syntax:
```csharp
(A x) => ((B)x).MyProperty
```

**Comment by StefanKoenigMUC** [comment]
unfortunately, this won't out for me, as the provided expression is from an extern (user-generated) source, they should not bother about any casting issues.

Aside from that, there is not only a B (there are approx 10 classes, which may be addressed) and only a few of them may have the property. 

My "workaround" solution could be some kind of a view class, containing a union of properties from those subclasses and convert them into around. But that doesn't sound like a very good architectural approach.

**Comment by zspitz** [comment]
> unfortunately, this won't out for me, as the provided expression is from an extern (user-generated) source, they should not bother about any casting issues.

Do you mean the string is generated somewhere else? How does this external location know that there is a `MyProperty`? Right before `MyProperty` is appended to the string, wrap the instance in the appropriate conversion.

If you are producing the string from other input, then why can't you do the same?

**Comment by StefanKoenigMUC** [comment]
the source of this string is (kind of) a data-grid, containing the union of properties as columns (each row is an object, not available columns are just empty/nulled). The 3rd party knows about those properties by convention (it's basically manual user input - but they should not care about casting & stuff).

Data structure is kind of 

BaseClass > A > B > C
A > D > E
D > F
(> shows inheritance)

for the datagrid I only receive a List<BaseClass>. 

If a user filters a column, only objects containing this property should be taken into consideration.

**Comment by zspitz** [comment]
According to the [documentation](https://dynamic-linq.net/basic-query-operators#isascastoftype), this should work:
```csharp
var lst = new List<A>() {
    new A(),
    new B()
};
var qry = lst.AsQueryable().Where("np(As(@0).MyProperty) = \"asdf\"", typeof(B));
```
However, I was unable to get this to work.

**Comment by zspitz** [comment]
Ping @StefanKoenigMUC @StefH @JonathanMagnan -- see previous [comment](https://github.com/zzzprojects/System.Linq.Dynamic.Core/issues/452#issuecomment-726421944).

**Comment by StefanKoenigMUC** [comment]
sorry, didnt get an email / didnt see your last comment. 

Thanks a lot, I'll play around a bit further today!

**Comment by StefH** [comment]
@StefanKoenigMUC and @zspitz 
The bug with `IndexOutOfRangeException` has been fixed and will be included in next release.

**Comment by chait-01** [comment]
I have a similar requirement, and I am using dynamic lambda expression, and trying to filter records based on a derived type.

var expr1 = DynamicExpressionParser.ParseLambda<Settings, bool>(new ParsingConfig(), true, "c => (c.Applicability As WinApplicability).SKUs.Contains(@0)", result);

Here Appilicability is a property within Settings type, and WinApplicability is a derived type of Applicability. SKUs is a property within WinApplicability.

The above line of code fails with the below error. Any idea how to deal with this issue?

Exception
System.Linq.Dynamic.Core.Exceptions.ParseException: ')' or operator expected
