### ISSUE TITLE
How to validate query string value for order by

### ISSUE THREAD

**Issue by neman** [zzzprojects/System.Linq.Dynamic.Core#453]
How can I validate if value in query string is ok?

For example, the following value of **Id descblabla**, will cause 500.

`api/v1/test-api?orderBy=Id descblabla`

Is there some way to validate string values before parsing expression?
Some helper function? 

Example

`var items = _context.Items.OrderBy(request.OrderBy).ToList();`

How can I validate `request.OrderBy` query string parameter?

#245

**Comment by zspitz** [comment]
What happens when you pass `request.OrderBy` into `DynamicExpressionParser.ParseLambda`?
```csharp
DynamicExpressionParser.ParseLambda(null, request.OrderBy)
```

**Comment by neman** [comment]
I tried both

`var result = DynamicExpressionParser.ParseLambda(null, request.OrderBy);`

and

`var result = DynamicExpressionParser.ParseLambda<Person>(new ParsingConfig(), false, request.OrderBy);`

And got ParseException `Unknown identifier 'Id'`

**Comment by zspitz** [comment]
What about:
```
var result = DynamicExpressionParser.ParseLambda<Item, int>(ParsingConfig.Default, true, request.OrderBy);
```

**Comment by neman** [comment]
I ended up creating my custom parser validator utility.
