### ISSUE TITLE
Queryable Extensions missing Where<T> with LambdaExpression

### ISSUE THREAD

**Issue by jogibear9988** [zzzprojects/System.Linq.Dynamic.Core#456]
would it be possible to add a signature like this
 ``` c#
public static IQueryable<TSource> Where<TSource>([NotNull] this IQueryable<TSource> source, [NotNull] LambdaExpression lambda)
```

**Comment by zspitz** [comment]
Why do you want to add such a signature? You could cast the `LambdaExpression` to the appropriate type:
```csharp
Expression<Func<int, bool>> expr = x => x % 3 == 0;
LambdaExpression lmbd = expr;
var lst = Enumerable.Range(1, 100);
var qry = lst.AsQueryable().Where((Expression<Func<int,bool>>)lmbd);
```

**Comment by jogibear9988** [comment]
I've a IQueryableT, but for Perfromance I have a preparsed Expression, so I will not use Where<TSource>(String), instead I will use Where(Lambda), and so I have to cast the IQueryable before I could call ToList

**Comment by zspitz** [comment]
I'm still not following. You have an `IQueryable<T>`? What happens when you cast the `LambdaExpression` to `Expression<Func<T, bool>>`?

**Comment by StefH** [comment]
https://github.com/zzzprojects/System.Linq.Dynamic.Core/pull/463

**Comment by StefH** [comment]
Method added
