### ISSUE TITLE
Documentation: `Is` and `As` should be documented with the rest of the expression language

### ISSUE THREAD

**Issue by zspitz** [zzzprojects/System.Linq.Dynamic.Core#458]
The [Standard Query Operators](https://dynamic-linq.net/basic-query-operators) page documents the `OfType` and `Cast` LINQ operators, which begin with a sequence, and filter all the elements to a specific type (`OfType`) or convert all the elements to the given type (`Cast`).

The `As` and `Is` functions aren't used on the sequence as a whole, but rather within the Dynamic LINQ selector. Therefore, they do not belong here, but rather on the [Expression Language](https://dynamic-linq.net/expression-language) page, like the `np` function, or the `iif` function.

**Comment by StefH** [comment]
In progress...
