### ISSUE TITLE
Allow `as` and `is` to use instances of `System.Type`

### ISSUE THREAD

**Issue by zspitz** [zzzprojects/System.Linq.Dynamic.Core#459]
The following:
```csharp
class Foo { }
class Bar : Foo { }

var prm = Parameter(typeof(Foo));
var selector = $"as(@0)";
var parser = new ExpressionParser(new[] { prm }, selector, new object[] { typeof(Bar) }, ParsingConfig.Default);
var expr = parser.Parse(null);
```
fails with:

> **System.Linq.Dynamic.Core.Exceptions.ParseException:** 'The 'as' function requires one argument which is not null.'

The same happens with `is`:
```csharp
var selector = $"is(@0)";
```

It might be helpful to clarify the error by explaining that the one argument must be the `FullName` of the type.

But I suggest it be possible to accept a `System.Type`, and `FullName` should be read from the type.

**Comment by StefH** [comment]
I've updated the code to support also Type for As, Is, OfType and Cast.

However, it needs to be a constant value (note that your example works fine with the code fix)

**Comment by zspitz** [comment]
> However, it needs to be a constant value

In other words, if I have a property or method which returns a Type, it's not going to work?

**Comment by StefH** [comment]
Correct, that will not yet work.
