### ISSUE TITLE
setting time offset to a DateTimeOffset

### ISSUE THREAD

**Issue by tnlthanzeel** [zzzprojects/System.Linq.Dynamic.Core#460]
hi, i have the following query where i need to set offset to db column "NextRenewalDate" of typ DateTimeOffset.  

CurrentMemberLevel.NextRenewalDate.Value.ToOffset(new TimeSpan(5, 30, 0).Date<="2020-11-07"

I get this error message "Expression is missing an 'as' clause".

please help

**Comment by zspitz** [comment]
Dynamic LINQ constructors are called without the `new`:
```
CurrentMemberLevel.NextRenewalDate.Value.ToOffset(TimeSpan(5, 30, 0).Date <= "2020-11-07")
```
`new` is only used to create dynamic type instances, like anonymous types in C#/VB.

**Comment by tnlthanzeel** [comment]
@zspitz , thanks, it work!!
