### ISSUE TITLE
Blazor WebAssembly : "where" error in release mode

### ISSUE THREAD

**Issue by Saeidasadi32** [zzzprojects/System.Linq.Dynamic.Core#461]
I use where with string parameter and run correctly in debug mode.
 but when i use release  mode system has generate error

**Comment by zspitz** [comment]
1. What does your code look like?
2. What is your predicate? In other words, what string are you passing in to `Where`?
3. What exception are you getting? Include the stack trace.
4. What is the shape of the objects you are querying?
5. Is it possible you are querying different objects in release mode?

**Comment by Saeidasadi32** [comment]
Thank you for your response1) I write this code : Freports = Freports.AsQueryable().Where(formula).OrderBy(x => x.PE).ToList();2) String (formula ) is : "(PE > 0.0) && (PE < 15.0 ) &&  (LST > 300.0)"3) exception in release mode: ﻿Operator 'and' incompatible with operand types 'Boolean' and 'Boolean'5) when run  'where' with just one statement like "(PE>0.0)" in release or debug mode system run correctly and no exception
please help me!Thanks' againSaeid    On Saturday, November 21, 2020, 10:29:26 PM GMT+3:30, Zev Spitz <notifications@github.com> wrote:  
 
 

   
   - What does your code look like?
   - What is your predicate? In other words, what string are you passing in to Where?
   - What exception are you getting? Include the stack trace.
   - What is the shape of the objects you are querying?
   - Is it possible you are querying different objects in release mode?

**Comment by zspitz** [comment]
1. What is the compile-time type of `Freports`? `IEnumerable`? `IEnumerable<Freport>`?
2. What is at the `ElementType` property of `Freports` after the query, and before the `ToList`?
2. What is the shape of that type? `public class ...`

**Comment by Saeidasadi32** [comment]
1)private List<SReport> Preports = new List<SReport>();
public class SReport    {        public int ACID { get; set; }        public string Group { get; set; }        public string Namad { get; set; }        public string NameFa { get; set; }        public int EPS { get; set; }        public double PE { get; set; }....2) ToList3 public class
    On Saturday, November 21, 2020, 10:59:27 PM GMT+3:30, Zev Spitz <notifications@github.com> wrote:  
 
 

   
   - What is the compile-time type of Freports? IEnumerable? IEnumerable<Freport>?
   - What is at the ElementType property of Freports after the query, and before the ToList?
   - What is the shape of that type? public class ...

**Comment by zspitz** [comment]
From what I can see, the syntax looks fine, and it should work in both Debug and Release mode.

1. I don't see the `LST` property/field in the definition you posted.
2. Again, **is it possible the query is being run against different objects in release mode?**
3. Are we talking about `Preports`? Or `Freports`?

Please try to use Markdown formatting for code and lists; it makes things much easier to read.

**Comment by Saeidasadi32** [comment]
1) public class SReport    {        public int ACID { get; set; }        public string Group { get; set; }        public string Namad { get; set; }        public string NameFa { get; set; }        public int EPS { get; set; }        public double PE { get; set; }        public double LST { get; set; }....2) No!3)private List<SReport> Freports = new List<SReport>();

    On Saturday, November 21, 2020, 11:14:13 PM GMT+3:30, Zev Spitz <notifications@github.com> wrote:  
 
 


From what I can see, the syntax looks fine, and it should work in both Debug and Release mode.
   
   - I don't see the LST property/field in the definition you posted.
   - Again, is it possible the query is being run against different objects in release mode?
   - Are we talking about Preports? Or Freports?

Please try to use Markdown formatting for code and lists; it makes things much easier to read.

**Comment by zspitz** [comment]
1. What framework are you targeting?
2. What version of Dynamic LINQ?
3. Which version of Visual Studio are you using, if any? Or, if you're using another editor, please specify.

**Comment by zspitz** [comment]
This is the code I am using to try and reproduce your exception; it works in both Debug and Release mode:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Dynamic.Core;

var formula = "(PE > 0.0) && (PE < 15.0 ) &&  (LST > 300.0)";
var FReports = new List<SReport>();
FReports = FReports.AsQueryable().Where(formula).OrderBy(x => x.PE).ToList();

foreach (var x in FReports) {
    Console.WriteLine(x);
}

public class SReport {
    public double PE { get; set; }
    public double LST { get; set; }
}
```

Using:

* Visual Studio 2019 (16.8.1)
* Targeting .NET 5
* Dynamic LINQ 1.2.5

I can't think of what else to try.

**Comment by Saeidasadi32** [comment]
My project create with webassambelyDotnetcore 3.1 Lasted version of dynamic LINQ2019 lasted version

Sent from Yahoo Mail on Android 
 
  On Sat, Nov 21, 2020 at 11:44 PM, Zev Spitz<notifications@github.com> wrote:   

   
   - What framework are you targeting?
   - What version of Dynamic LINQ?
   - Which version of Visual Studio are you using, if any? Or, if you're using another editor, please specify.

**Comment by zspitz** [comment]
I've never used C# to generate WebAssembly. Can you post a sample project with code that reproduces this issue?

**Comment by Saeidasadi32** [comment]
Hi againI upload in Attachment very simple project.This sample work correctly in debug mode and generated error in release mode!Thanks
https://drive.google.com/file/d/1TDheadz092FgMvxOj7MYY5Rd8dq_2txP/view?usp=drivesdk

    On Sunday, November 22, 2020, 12:39:26 AM GMT+3:30, Zev Spitz <notifications@github.com> wrote:  
 
 


I've never used C# to generate WebAssembly. Can you post a sample project with code that reproduces this issue?

**Comment by Saeidasadi32** [comment]
HiI myself try to Solving the Problem in System.Linq.Dynamic.Core in release mode.I replace all '&&' with '&' and run My project in release mode.In this Time no Error reported and ran correctly!Why!!
    On Sunday, November 22, 2020, 10:02:49 AM GMT+3:30, Saeid Asadi <asadi_s@yahoo.com> wrote:  
 
  Hi againI upload in Attachment very simple project.This sample work correctly in debug mode and generated error in release mode!Thanks
https://drive.google.com/file/d/1TDheadz092FgMvxOj7MYY5Rd8dq_2txP/view?usp=drivesdk

    On Sunday, November 22, 2020, 12:39:26 AM GMT+3:30, Zev Spitz <notifications@github.com> wrote:  
 
 


I've never used C# to generate WebAssembly. Can you post a sample project with code that reproduces this issue?

**Comment by zspitz** [comment]
> I replace all '&&' with '&'

That may be a different operation; it's interpreted as a bitwise AND, and may produce different results.

**Comment by Saeidasadi32** [comment]
Hi againI upload in Attachment very simple project.This sample work correctly in debug mode and generated error in release mode!Thanks
https://drive.google.com/file/d/1TDheadz092FgMvxOj7MYY5Rd8dq_2txP/view?usp=drivesdk
    On Sunday, November 22, 2020, 11:00:15 PM GMT+3:30, Zev Spitz <notifications@github.com> wrote:  
 
 



I replace all '&&' with '&'


That may be a different operation; it's interpreted as a bitwise AND, and may produce different results.

**Comment by zspitz** [comment]
OK. I can confirm the following:

* the `&&` operator between two `bool`s causes an exception when run in Release mode, but not in Debug mode.
* `&` works in both Debug and Release; the expression tree is still built correctly as a logical AND between two `bool`s.
* Neither operand seems to be a `bool?`.
* The types of the two operands are equivalent -- `expr.Left.Type == expr.Right.Type` returns `true`

The following code also produces the same error only in Release mode, not in Debug mode:

    var prm = System.Linq.Expressions.Expression.Parameter(typeof(string));
    var selector = "true && false";
    var parser = new System.Linq.Dynamic.Core.Parser.ExpressionParser(new[] { prm }, selector, new object[] {}, System.Linq.Dynamic.Core.ParsingConfig.Default);
    var expr = parser.Parse(null);

**Comment by zspitz** [comment]
Try the following:

1. Close Visual Studio
2. Delete the `.vs` folder in the root solution folder
3. Delete all the `bin` and `obj` folders
4. Reopen the solution

I did this and now it works in both Debug and Release mode.

**Comment by Saeidasadi32** [comment]
I try but not work

Sent from Yahoo Mail on Android 
 
  On Sun, Nov 22, 2020 at 11:31 PM, Zev Spitz<notifications@github.com> wrote:   


Try the following:
   
   - Close Visual Studio
   - Delete the .vs folder in the root solution folder
   - Delete all the bin and obj folders
   - Reopen the solution

I did this and now && works in both Debug and Release mode.

**Comment by StefH** [comment]
Hello @Saeidasadi32,

Your issue can be solved by adding this line to your Client WebAssembly project:
``` xml
<BlazorWebAssemblyEnableLinking>false</BlazorWebAssemblyEnableLinking>
```

Or you can specify exactly what you want, see this link : https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/configure-linker?view=aspnetcore-3.1#control-linking-with-a-configuration-file

I applied this also to my example project here: [BlazorAppHandlebarsExample](https://github.com/StefH/BlazorAppHandlebarsDemo/blob/master/src/BlazorAppHandlebarsExample/BlazorAppHandlebarsExample.csproj#L7-L8)

I probably have to add a Blazor WebAssembly section to the documentation to explain this scenario.

**Comment by Saeidasadi32** [comment]
Hi AgainThanks
It worked .
    On Thursday, November 26, 2020, 07:19:21 PM GMT+3:30, Stef Heyenrath <notifications@github.com> wrote:  
 
 


Hello @Saeidasadi32,

Your issue can be solved by adding this line to your Client WebAssembly project:
<BlazorWebAssemblyEnableLinking>false</BlazorWebAssemblyEnableLinking>
Or you can specify exactly what you want, see this link : https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/configure-linker?view=aspnetcore-3.1#control-linking-with-a-configuration-file

I applied this also to my example project here: BlazorAppHandlebarsExample

I probably have to add a Blazor WebAssembly section to the documentation to explain this scenario.
