### ISSUE TITLE
net5.0 OrderBy problem

### ISSUE THREAD

**Issue by totpero** [zzzprojects/System.Linq.Dynamic.Core#468]
Hi,
I'm using aspboilerplate that use [this nuget](https://github.com/aspnetboilerplate/aspnetboilerplate/blob/c0604b9b1347a3b9581bf97b4cae22db5b6bab1b/src/Abp/Application/Services/CrudAppServiceBase.cs#L52).
After update entityframework to version 5 and net5.0 [this not longer work](https://zzzprojects.github.io/System.Linq.Dynamic.Core/api/System.Linq.Dynamic.Core.DynamicQueryableExtensions.html#System_Linq_Dynamic_Core_DynamicQueryableExtensions_OrderBy_System_Linq_IQueryable_System_String_System_Object___)

When i run sqlprofiler on my query i saw that is translated into: `order by (SELECT 3)` and this is not ok;

Because this two query are not equals on result:
Select top 10 * from [pay].[table] order by 3 DESC

Select top 10 * from [pay].[table] order by (SELECT 3) DESC

**Comment by StefH** [comment]
Hello @totpero, I'll take a look.

(Note that I'm also building a EF5 specific NuGet which could maybe solve your issue)

I keep you informed.

**Comment by StefH** [comment]
Should a normal OrderBy not be like:
`Select top 10 * from [pay].[table] order by id DESC` instead of `3 desc` ?

**Comment by njsent** [comment]
Hi, 
We're having the same issue with dynamic sql order by in .NET Core 5.  What's strange is that everything works fine until I added 2 new columns to a sql server view, BillingIndLastName and BillingIndFirstName.  I'm able to filter using these two columns with ef core linq to sql, but the dynamic OrderBy throws an error ("No property or field 'BillingIndLastName' exists in type 'MyView'")  when I try to sort on these columns.  There is an object in the EF5 class for this view named BillingInd and a property named BillingIndId - so I'm not sure if that's related to the problem.  I will try to research more but will look for the EF5 nuget lib.  Thank you for this awesome library!

**Comment by StefH** [comment]
I've uploaded a preview for EF5 (Microsoft.EntityFrameworkCore.DynamicLinq 5.2.7-preview-03)
See https://www.myget.org/feed/Packages/system-linq-dynamic-core

**Comment by totpero** [comment]
> 
> 
> Should a normal OrderBy not be like:
> `Select top 10 * from [pay].[table] order by id DESC` instead of `3 desc` ?

The boilerplate use datatables.net and the order is made by the number of the column. If the translated into  order by 3 DESC instade of that will solve the problem order by (SELECT 3) DESC

**Comment by StefH** [comment]
As far I can see, this code 
``` c#
var orderBy3 = context.Cars.OrderBy("3 DESC").ToList();
```

Does compile, however no order by is executed because the generated SQL does not have an order by generated:
``` sql
SELECT [c].[Key], [c].[Brand], [c].[Color], [c].[DateDeleted], [c].[DateLastModified], [c].[Extra], [c].[NullableInt], [c].[Vin], [c].[Year]
      FROM [Cars] AS [c]
```

**Comment by totpero** [comment]
Yes, you have right,  the` .OrderBy("3 DESC")`  do nothing , but after that I have [PageBy() ](https://github.com/aspnetboilerplate/aspnetboilerplate/blob/e0ded5d8702f389aa1f5947d3446f16aec845287/src/Abp/Linq/Extensions/QueryableExtensions.cs#L31) and there is set the `ORDER BY (SELECT 1)` clause.
But in the previous verison of ef core this works fine `OrderBy("3 DESC")`

**Comment by StefH** [comment]
OK. Closing this issue.

@njsent If you still have questions, raise a new issue regarding this.

**Comment by njsent** [comment]
> I've uploaded a preview for EF5 (Microsoft.EntityFrameworkCore.DynamicLinq 5.2.7-preview-03)
> See https://www.myget.org/feed/Packages/system-linq-dynamic-core

Unfortunately the new version did not fix the problem but I was able to solve the problem by SELECTing the last & first columns.  These two columns were only used for dynamic OrderBy previously so I'm not sure if it's even related to .net core 5.0 or if I just have to always SELECT the columns that are used for dynamic OrderBy.  I really appreciate you putting the 5.0 lib up so quickly anyway.

**Comment by StefH** [comment]
https://github.com/zzzprojects/System.Linq.Dynamic.Core/pull/470
