### ISSUE TITLE
Question: DynamicClass with INotifyPropertyChanged

### ISSUE THREAD

**Issue by zspitz** [zzzprojects/System.Linq.Dynamic.Core#472]
If the result of my selector is an anonymous type:
```c#
IQueryable<Person> persons = /* ... */;
var qry = persons.Select("new (LastName, FirstName)");
```
is there any way to specify that the result type should implement `INotifyPropertyChanged`?

Properly implementing this interface requires two parts:

1. Declaring a `PropertyChanged` event handler, and
2. Raising the event within each property setter.

**Comment by yisman** [comment]
Hi! Was this ever implemented?
It is of great importance to me
Thanks so much!

**Comment by StefH** [comment]
Hello @yisman, this is not implemented. And I don't think this will be implemented soon.

**Comment by yisman** [comment]
Make your new year an innovative one!

View this email in your browser (https://mailchi.mp/machshevet/drfklqb6ix-4666046?e=d5059cf304)
https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=e1f771c482&e=d5059cf304
בס"ד

לכל לקוחותיי וידידיי היקרים

[ אין לכם זמן לקרוא את ההודעה?
פנו אלינו לקבל מערכת חדשה לניהול נתונים, שתחסוך לכם שעות כל יום!! ]

בפרוס השנה החדשה הבאה עלינו לטובה,
נאחל לכם ולמשפחתכם
ברכת שנה טובה ומתוקה,
שנת בריאות, שמחה ופרנסה טובה,
שפע ברכה והצלחה.
Wishing you all a happy and healthy New Year


תוסף חדש מבית 'מחשבת'
מהיום תראה את כל פרטי אנשי הקשר בחלון ה-Gmail שלך.
https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=bd2ab5d16f&e=d5059cf304
Turbo Paced Custom Software Development
Tel: +972 (52) 764-9971 (tel:972527649971)

============================================================
** (https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=399eeb5ecc&e=d5059cf304)
** ***@***.***)
Copyright © 2021 machshevet, All rights reserved.
 contact

Our mailing address is:
machshevet
88 Agripas Street
jerusalem 9453331
Israel
Want to change how you receive these emails?
You can ** update your preferences (https://machshevet.us3.list-manage.com/profile?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&e=d5059cf304&c=a6138bfd9a)
or ** unsubscribe from this list (https://machshevet.us3.list-manage.com/unsubscribe?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&e=d5059cf304&c=a6138bfd9a)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=752c5e4f79a9fa7c8f2e896ea&afl=1

**Comment by yisman** [comment]
Make your new year an innovative one!

View this email in your browser (https://mailchi.mp/machshevet/drfklqb6ix-5412508?e=d5059cf304)
https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=bcd81feef0&e=d5059cf304
בס"ד

לכל לקוחותינו וידידינו היקרים

[ אין לכם זמן לקרוא את ההודעה?
פנו אלינו לקבל מערכת חדשה לניהול נתונים, שתחסוך לכם שעות כל יום!! ]

בפרוס השנה החדשה הבאה עלינו לטובה,
נאחל לכם ולמשפחתכם
ברכת שנה טובה ומתוקה,
שנת בריאות, שמחה ופרנסה טובה,
שפע ברכה והצלחה.
Wishing you all a happy and healthy New Year


מיוחד מבית "מחשבת"
אזור אישי ללקוחות שלכם לראות סטטוס הזמנות, חיובים ועוד
https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=dd866fa5ba&e=d5059cf304
Turbo Paced Custom Software Development
Tel: +972 (52) 764-9971 (tel:972527649971)

============================================================
** Website (https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=e22f98ed3c&e=d5059cf304)
** Email ***@***.***)
Copyright © 2023 machshevet, All rights reserved.
 contact

Our mailing address is:
machshevet
88 Agripas Street
jerusalem 9453331
Israel
Want to change how you receive these emails?
You can ** update your preferences (https://machshevet.us3.list-manage.com/profile?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&e=d5059cf304&c=746ecb8128)
or ** unsubscribe from this list (https://machshevet.us3.list-manage.com/unsubscribe?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&e=d5059cf304&c=746ecb8128)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=752c5e4f79a9fa7c8f2e896ea&afl=1

**Comment by yisman** [comment]
שנה טובה ומתוקתקת - פ'תרון ת'וכנה ש'מקיף ה'כל

View this email in your browser (https://mailchi.mp/machshevet/drfklqb6ix-5844976?e=d5059cf304)
https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=bd98d8dc80&e=d5059cf304

שנה חדשה זו ההזדמנות שלכם לגלות את המערכות המידע המתקדמות של מחשבת, המתאימות לכל סוגי העסקים והארגונים... גם שלכם! עם כלים עוצמתיים כמו:
* 📧 חיבור לג'ימייל ושילוב מיילים וסמסים
* 📊 ייבוא וייצוא מאקסל
* 📞 חיבור למרכזיה טלפונית
* 💼 ניהול לקוחות ולידים בצורה אוטומטית
* 🔔 דוחות והתראות חכמות בזמן אמת
* 💰 גביה באשראי והוראות קבע
* 📦 ניהול מלאי ומשלוחים
* 📅 יומן פגישות עם תזכורן חכם וגמיש

לא רק שזה מתאים בדיוק לכם, אלא גם מותאם אישית לכל משתמש! כל משתמש יכול לסדר את הממשק בדיוק לפי הצרכים שלו 🎯. מדהים, לא?

אם אתם מחפשים להתקדם ולהפוך את העסק שלכם ליעיל יותר ב-תשפ"ה, אין זמן טוב יותר להתחיל!

המערכות שלנו מתחברות ומשתלבות עם המון ספקים מובילים, וביניהם:


מכירים?

וגם חשבונית ירוקה, בנק ישראל, מערכות גביה ומשלוחים ועוד המון פלטפורמות נפוצות ושימושיות .

ובמשפט אחד?

פתרון תוכנה שמקיף הכל!

בא נצא לדרך חדשה ביחד, ותראו איך המערכות של מחשבת יעזרו לכם להצליח ולגדול בס"ד
לקבלת הדגמה אישית עכשיו! ***@***.***)

יותר טיפוס של דיבורים? התקשרו אלינו כבר עכשיו
+972-5276-49971 (tel:972527649971)

מאחלים לכם שנה של התפתחות, הצלחות חדשות ושיתופי פעולה פוריים,
צוות מחשבת

להסרה מרשימת התפוצה, לחץ כאן (https://machshevet.us3.list-manage.com/unsubscribe?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&t=b&e=d5059cf304&c=824fac5f79) .

============================================================
** Website (https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=1e7d51142d&e=d5059cf304)
** Email ***@***.***)
Copyright © 2024 machshevet, All rights reserved.
 contact

Our mailing address is:
machshevet
88 Agripas Street
jerusalem 9453331
Israel
Want to change how you receive these emails?
You can ** update your preferences (https://machshevet.us3.list-manage.com/profile?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&e=d5059cf304&c=824fac5f79)
or ** unsubscribe from this list (https://machshevet.us3.list-manage.com/unsubscribe?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&t=b&e=d5059cf304&c=824fac5f79)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=752c5e4f79a9fa7c8f2e896ea
