### ISSUE TITLE
How to project a Count from a Select ?

### ISSUE THREAD

**Issue by YeskaNova** [zzzprojects/System.Linq.Dynamic.Core#474]
Hi,

I need to project the count of the underlying collection, I can't use Count(expr) or .Count() . In this example, I'm using an array but in my case, it's an EF Core IQueryable ( it's not working for arrays also, I don't know if it's a bug or if it's by design) . Is it possible to do something like this? 

system.linq.dynamic.core: 1.2.7
.net core: 5
Exception : No applicable method 'Count' exists in type 'Entity'

```
using System;
using System.Diagnostics;
using System.Linq;
using System.Linq.Dynamic.Core;

namespace ConsoleApp36
{
    class Program
    {
        static void Main(string[] args)
        {
            var data = Enumerable.Range(0, 100).Select(id=> new Entity(){Id=id}).ToArray();
            var count = 0;
            try
            {
                count =data.AsQueryable().Select("Count()").Cast<int>().First();
            }catch{}

            try
            {
                count = (int)data.AsQueryable().Select("new (Count() as TotalCount)").Cast<dynamic>().First().TotalCount;
            }
            catch { }

            try
            {
                count = (int)data.AsQueryable().Select("new (Count(Id>=0) as TotalCount)").Cast<dynamic>().First().TotalCount;
            }
            catch { }

            Debug.Assert(count == data.Length);
        }
    }

    class Entity
    {
        public int Id { get; set; }
    }
}
```

**Comment by zspitz** [comment]
You wouldn't expect to be able to do this:
```csharp
var context = /* ... */;
var count = context.Entities.Select(x => x.Count());
```
For this reason the same doesn't work in Dynamic LINQ:
```csharo
var context = /* ... */
IQueryable qry = context.Entities;
var count = qry.Select("Count");
```
---
You could either get the count using `.Count` outside of the query:
```csharp
var context = /* ... */;
IQueryable qry = context.Entities;
var count = qry.Count();
```
and you could pass the count into successive queries using `@` parameter syntax. Note that this would involve two database calls.

Alternatively, it might be possible to pass the query using `@` parameter syntax in order to get the `Count` in a single database call:
```csharp
var context = /* ... */;
IQueryable qry = context.Entities;
var results = qry.Select("@0.Count - Id", qry);
```

**Comment by YeskaNova** [comment]
Thanks a lot, much clearer.
