### ISSUE TITLE
No property or field exists in type IGrouping

### ISSUE THREAD

**Issue by rochapablo** [zzzprojects/System.Linq.Dynamic.Core#475]
When using group, I'm not able to order by the summed field giving the following error

`No property or field 'income' exists in type 'IGrouping`2'`

group: `new (it.user.domain)`

order: `it.income desc`

select `new (it.Sum(income) as income, it.Key.domain)`

What could I be missing?

**Comment by zspitz** [comment]
The result of a grouping, which implements the `IGrouping<TKey, TElement>` interface, implements `IEnumerable<TElement>` and has a `Key` property. This means the properties of the individual elements aren't available on the grouping, and thus you can't order the groupings by some property of the elements inside them.

If you want to order by the sum of the group, you could `OrderBy("Sum(invome)")`. Alternatively, you could specify that `GroupBy` should return the sum as the result of the grouping, as described [here](https://dynamic-linq.net/basic-query-operators#groupby-by-a-single-key-and-do-a-sum).

**Comment by StefH** [comment]
Closing...
