### ISSUE TITLE
System.Linq.Queryable breaking changes in .NET 6 

### ISSUE THREAD

**Issue by eiriktsarpalis** [zzzprojects/System.Linq.Dynamic.Core#493]
Hi, I'm the area owner for System.Linq in the .NET libraries team. As part of our efforts to [improve LINQ in .NET 6](https://github.com/dotnet/runtime/issues/47231) we have added a small number of method overloads to the queryable APIs. This is known to [break query providers](https://github.com/dotnet/efcore/issues/24002) whose reflection code does not account for method overloading. I have filed a [breaking change issue](https://github.com/dotnet/runtime/issues/47231) which contains instructions on how to mitigate the problem.

I'm contacting you directly since we have [received reports](https://github.com/dotnet/runtime/issues/50349) that your nuget package `System.Linq.Dynamic.Core` is also affected by this change.

**Comment by StefH** [comment]
Hello @eiriktsarpalis, thanks for notifying these changes.

Can you give an ETA when these changes will be published to .NET 6 ?

BTW: I need to read all the information you provided to assess the changes required in this project.

**Comment by eiriktsarpalis** [comment]
Hi @StefH, some of these changes can already be found in .NET 6 preview 2.

**Comment by StefH** [comment]
Preview versions for EF 6 are available on NuGet.

**Comment by wihrl** [comment]
How extensive are the changes necessary to fix this? Can I expect a fix anytime soon? 

I ended up having to downgrade a project back to .NET 5 because of this.

**Comment by StefH** [comment]
@wihrl and @enchev 

What version from System.Linq.Dynamic.Core did you use?
(Note that there is a `6.2.11-preview.4.21253.1`)

**Comment by wihrl** [comment]
I used 1.2.11.
I cannot install the Microsoft.EntityFrameworkCore.DynamicLinq package as it requires EF Core 6, but I'm using 3.1.17 and cannot upgrade because of other packages.

Here is the error I'm getting:
![image](https://user-images.githubusercontent.com/57505542/127173646-cddfa857-9198-4c72-9997-b1e2fdccc58b.png)

I believe that a dynamic .Where call on an IQueryable is causing it. It works fine in .NET 5.

**Comment by StefH** [comment]
@wihrl 
Now I understand.

This is about **.NET 6**, and not about **EF 6**.

I'll look into this.

**Comment by tirth-uhn** [comment]
Hi - we've also run into this issue using Radzen.Blazor with .NET 6 preview, it's described [on the Radzen forums](https://forum.radzen.com/t/linq-error-with-net-6-0-preview-3-and-dropdown-control/7483) which actually references this issue.

**Comment by StefH** [comment]
@wihrl 
@tirth-uhn 

Please try version `1.2.12-preview-01` from MyGet:
https://www.myget.org/feed/system-linq-dynamic-core/package/nuget/System.Linq.Dynamic.Core

**Comment by sofiageo** [comment]
@StefH It works fine for me on a Radzen RadzenDataGrid. It used to throw an exception before upgrading to `1.2.12-preview-01`

p.s I've only tested filtering on a text column.

**Comment by tirth-uhn** [comment]
@StefH it works! Thanks so much for the quick fix.

**Comment by wihrl** [comment]
It works for me too.

**Comment by StefH** [comment]
@sofiageo 
@wihrl 
@tirth-uhn 
@enchev

I'll try to release an official `1.2.12` on NuGet this weekend.

Note that I'll also create a new issue to also support the new Queryable methods which are introduced in .NET 6

**Comment by StefH** [comment]
https://github.com/zzzprojects/System.Linq.Dynamic.Core/issues/537

**Comment by Mike-E-angelo** [comment]
Woohoo bless you all.  +1 to being brought here due to Radzen.  Installed the latest preview and ERRORS BE GONE.  Well, until the next one. 😅

Appreciate all the work you are doing out there!

**Comment by StefH** [comment]
@Mike-E-angelo 
You can also install the official `1.2.12` version.

**Comment by Mike-E-angelo** [comment]
Gosh @StefH you're right I got so excited once I saw the preview I stopped reading the rest of the thread and just upvoted. 😆  Updated and installed. 👍
