### ISSUE TITLE
Feature: Support for Concat and optionally Union, Except, Intersect

### ISSUE THREAD

**Issue by jbhelm** [zzzprojects/System.Linq.Dynamic.Core#499]
It does not appear there is support for the concatenation functions `Concat`, `Union`, `Except`, or `Intersect`. Would it be possible to add support for these? The most important one for my use case is `Concat`, while the others would just be nice-to-have to round out the functionality.

My use case would be to use the function inside a Select() string, for example:
`Select("CollectionA.Concat(CollectionB).Sum(SomeValue)")`

**Comment by StefH** [comment]
@jbhelm 
See 1.2.10-preview-01 version at https://www.myget.org/feed/Packages/system-linq-dynamic-core

**Comment by StefH** [comment]
Hello @jbhelm, did you have time to test this preview version?

**Comment by jbhelm** [comment]
Hi @StefH  --  I've never MyGet. Following the link provided takes me to a login prompt , I do not have a MyGet account. I also tried adding the URL as a NuGet package source in Visual Studio, but that does not work either. I'm not sure what I'm supposed to do with that URL.

**Comment by StefH** [comment]
Hello @jbhelm, see this link which describes how to use MyGet for NuGet packages:
https://github.com/zzzprojects/System.Linq.Dynamic.Core/wiki/MyGet-preview-versions

**Comment by StefH** [comment]
A new NuGet version which includes this functionality will be released.
