### ISSUE TITLE
Convert IQueryable to dynamic linq String

### ISSUE THREAD

**Issue by mkalinski93** [zzzprojects/System.Linq.Dynamic.Core#502]
## 1. Description
I just wanted to get to if there´s a chance to convert a IQueryable<T> to a Dynamic Linq string value.
The reason for that is that I want to select data at frontend level, but sending the server the translated query as a string.
Of course I can write a query string, but when my dto model change, I need to reassure that every query string I´ve written is modified to the dto properties.

Maybe there´re extension methods I don´t know yet, but it would be nice to have something like this

_users.Where(x => x.UserName == "Test").OrderBy(x => x.UserName).ToDynamicLinqString();

Thank you in advance

**Comment by StefH** [comment]
Hello @mkalinski93.

This is not supported by this project, but you can try:
- https://github.com/esskar/Serialize.Linq
