### ISSUE TITLE
Custom query operators

### ISSUE THREAD

**Issue by mkalinski93** [zzzprojects/System.Linq.Dynamic.Core#512]
Hey,

I would like to know if it´s possible to create custom filter operators such as "Starts with", "Ends with", "Is null" and "Is not null" ?
In my current project, the client (Blazor WebAssembly) sends a querystring to the server to retrieve just the desired data it needs. It works perfect so far, but in my case, the given operators are mandatory and I wasn´t able to figure out how to implement them yet.

Here are some examples of how it could be implemented

``` c#
Context.Users.Where("LastName.StartsWith(\"xxx\")")
Context.Users.Where("LastName.EndsWith(\"xxx\")")
Context.Users.Where("LastName == null")
Context.Users.Where("LastName != null")

```
I also know that there were some issues with StartsWith/EndsWith  using Entity Framework Core. But this seems to be solved with ef core 3.x

https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.x/

The question would be: Can I extend the operators with custom operator? Are these operators applicable somehow?

Thank you in advance.

best regards

**Comment by StefH** [comment]
@mkalinski93 
This is already supported, you can use StartsWith:
![image](https://user-images.githubusercontent.com/249938/128738367-1ddded90-86d2-477c-911c-d417b60289ae.png)
