### ISSUE TITLE
Consider making TextParser public

### ISSUE THREAD

**Issue by igitur** [zzzprojects/System.Linq.Dynamic.Core#515]
## 1. Description
I'm not using this library on a database. My underlying data is access via an API with fairly expensive operations. I have to retrieve each property of my class separately (poor design, but it is what it is). I'm trying to improve our performance by retrieving only properties that are used by the user. 

We don't use SQL, but in pseudo-code, if the user "executes"
`select p.Name from Person p where p.Age > 30`
then I want to retrieve only the entity properties `Name` and `Age` and ignore other properties, like `Telephone` and `Address`, because, as I say, retrieving them requires separate, expensive operations.

Additionally, the number of properties per entity is not a fixed set. It's a kind of sparse entity/attribute design.

Given all this, I want to build my own `DynamicClass` with its own subset of required `DynamicProperty` instances. I can already do this successfully. All I now need is a way to parse the clause to extract the identifiers that are used. 

So I'm asking you to consider making `TextParser`, `Token` and `TokenId` public, instead of internal, please. I'd then be able to use an instance of `TextParser` to extract all the identifiers and take it from there.

Example of what I want to do:
```c#
var whereClause = @"Age >= 30 and Name.StartsWith('Jo')";

var parsingConfig = new ParsingConfig();

var textParser = new TextParser(parsingConfig, whereClause);

while (textParser.CurrentToken.Id != TokenId.End)
{
    if (textParser.CurrentToken.Id == TokenId.Identifier)
        System.Console.WriteLine($"{textParser.CurrentToken.Pos}: {textParser.CurrentToken.Id} | {textParser.CurrentToken.Text}");

    textParser.NextToken();
}
```

This will, of course, also return `StartsWith` as an identifier, but that's OK. I can check the returned identifier against a large, but known list of properties on my side.

**Comment by igitur** [comment]
@StefH Your thoughts on this? I will submit the PR if you agree that this is allowed.

**Comment by StefH** [comment]
Hello @igitur,

Do you still need this functionality ?

**Comment by igitur** [comment]
Hi, yes, definitely. At the moment I'm using reflection to access these private APIs.

**Comment by StefH** [comment]
#562
