### ISSUE TITLE
Unable to use DynamicClassFactory.CreateType from Blazor WebAssembly

### ISSUE THREAD

**Issue by Matthewsre** [zzzprojects/System.Linq.Dynamic.Core#516]
## 1. Description
Unable to use DynamicClassFactory.CreateType from Blazor WebAssembly.

## 2. Exception

```
Exception message: 'The method or operation is not implemented.'
Stack trace:
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at System.Linq.Dynamic.Core.DynamicClassFactory.CreateType(IList`1 properties, Boolean createParameterCtor)
```

## 3. Fiddle or Project

Simple example Blazor page to repro:

```
@page "/dynamic"

@using System.Linq.Dynamic.Core

@code {
    protected override Task OnInitializedAsync()
    {
        var dynamicProperties = new List<DynamicProperty>();
        dynamicProperties.Add(new DynamicProperty("Name", typeof(string)));

        try
        {
            var model = DynamicClassFactory.CreateType(dynamicProperties);
        }
        catch (Exception exception)
        {
            throw;
        }

        return Task.CompletedTask;
    }
}
```

Exception screenshot:

![image](https://user-images.githubusercontent.com/2955659/120948767-d18f8e00-c6f7-11eb-8c4c-57af573d788e.png)

## 4. Any further technical details

Using .Net 5 Blazor WebAssembly, can provide more details it needed. Not sure if there are workaround options or if this is something that needs to be addressed in the underlying runtime used for WebAssembly.

**Comment by StefH** [comment]
#518

**Comment by StefH** [comment]
@Matthewsre 

Can you please try 11-preview-01 from https://www.myget.org/feed/system-linq-dynamic-core/package/nuget/System.Linq.Dynamic.Core ?

**Comment by Matthewsre** [comment]
> @Matthewsre
> 
> Can you please try 11-preview-01 from https://www.myget.org/feed/system-linq-dynamic-core/package/nuget/System.Linq.Dynamic.Core ?

@StefH,

Just walked through the code with the preview package from your feed and it worked as expected.

Thank you so much for providing a fix so quickly on this! :)

How long until I might expect an updated package on NuGet.org so I don't have to change the build pipelines?

**Comment by StefH** [comment]
I still need to verify another PR and review some other issues.

Would it help you if I would publish this version to the normal NuGet ?

**Comment by Matthewsre** [comment]
@StefH , Sorry for the late follow up, it would be very helpful if you were able to push the preview version to the normal NuGet. :)

**Comment by StefH** [comment]
@Matthewsre 
Official version 11 has been updated to NuGet.
