### ISSUE TITLE
Filtering based on derived property Types in dynamic Linq

### ISSUE THREAD

**Issue by chait-01** [zzzprojects/System.Linq.Dynamic.Core#519]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description
I am using dynamic lambda expression, and trying to filter records based on a derived type. 

``` c#
var expr1 = DynamicExpressionParser.ParseLambda<Settings, bool>(new ParsingConfig(), true, "c => (c.Applicability As WinApplicability).SKUs.Contains(@0)", result);
```

Here Appilicability is a property within Settings type, and WinApplicability is a derived type of Applicability. SKUs is a property within WinApplicability.

The above line of code fails with the below error. Any idea how to deal with this issue?

**Exception**
```
System.Linq.Dynamic.Core.Exceptions.ParseException: ')' or operator expected
```

If I try to use static lambda expression, I dont see any error, but result being variable, the code fails with 
``` c#
Expression<Func<Settings, bool>> expr2 = c => (c.Applicability as WinApplicability).SKUs.Contains(result);
```

since the variable "result" is not pre-computed
```
"Object reference not set to an instance of an object."
StackTrace = "   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()\r\n   at System.Linq.SystemCore_EnumerableDebugView`1.get_Items()"
```

**Comment by StefH** [comment]
https://github.com/zzzprojects/System.Linq.Dynamic.Core/pull/622

**Comment by StefH** [comment]
Hello @chait-01, in your example you use the `as` as the naming operator (giving a property a different name).

In your example here, you need this code:
``` c#
var config = new ParsingConfig { ResolveTypesBySimpleName = true };
var expr1 = DynamicExpressionParser.ParseLambda<Settings, bool>(config, true, "As(Applicability, \"WinApplicability\").SKUs.Contains(@0)", result);
```

See also unit-test:
https://github.com/zzzprojects/System.Linq.Dynamic.Core/blob/master/test/System.Linq.Dynamic.Core.Tests/QueryableTests.Is%2COfType%2CAs%2CCast.cs#L181


Note that I'll also update the documentation on https://dynamic-linq.net/expression-language#is-and-as-examples

**Comment by StefH** [comment]
@chait-01 
Explanation for 
>  in your example you use the as as the naming operator (giving a property a different name).

![image](https://user-images.githubusercontent.com/249938/183237596-15f5de59-2c78-4b6a-9ea4-c48264668c1c.png)
