### ISSUE TITLE
list<dynamic> convert to IQueryable and use groupby(propertyname) Error occurred

### ISSUE THREAD

**Issue by ClementeGao** [zzzprojects/System.Linq.Dynamic.Core#523]
the code is 
```
public class ImportDataInput
    {
        public List<dynamic> JsonDatas { get; set; }
    }
```

```
var data = input.JsonDatas.AsQueryable().GroupBy(input.GroupFieldName);
```
i need your help

**Comment by StefH** [comment]
@ClementeGao 
Can you please provide a full working example console - app which describes your isssue?

**Comment by StefH** [comment]
Hello @ClementeGa,
Can you please provide a full working example console - app  / dotnet fiddle or unit-test which describes your issue?

**Comment by StefH** [comment]
Closing...
