### ISSUE TITLE
SetDynamicPropertyValue causing issue when the value is parsed from jsondocument

### ISSUE THREAD

**Issue by RevathiNeminathan** [zzzprojects/System.Linq.Dynamic.Core#533]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description
I am planning to implement dynamic class in my project. I am facing the issue when executing Where condition against the input list.
 I have an input dictionary where I store all my data by parsing jsondocument and  use those values to set dynamic properties. 
Problem is, the condition is not met if I set the dictionary value by parsing the jsondocument. instead If i set the dictionary value "Male" then it's working fine.
 Could you please help me ?

``` c#
Dictionary<string, object> inputList = new Dictionary<string, object>();
string EmployeeData = JsonDocument.Parse(EmployeeList).RootElement.GetProperty("gender").ToString();

inputList.Add("gender","Male"); // --> Working
inputList.Add("gender",EmployeeData); // --> not working

List<DynamicProperty> props = new List<DynamicProperty>();

Type type = DynamicClassFactory.CreateType(props,true);

var obj = (DynamicClass) Activator.CreateInstance(type) ;

var typeProps = type.GetProperties().ToDictionary(c => c.Name);

foreach (var dict in inputList)
{
obj.SetDynamicPropertyValue(dict.Key,dict.Value);
}

var LstOfRecords  = new List<DynamicClass>();
LstOfRecords.Add(obj);
LstOfRecords.AsQueryable().Where("gender == \"Male\"");
```

```

**Comment by RevathiNeminathan** [comment]
Hi StefH, Is there any update on this issue? I am struck in this issue .

**Comment by StefH** [comment]
var EmployeeData = JsonDocument.Parse(EmployeeList).RootElement.GetProperty("gender");
```

**Comment by RevathiNeminathan** [comment]
I already tried above line, it doesn't work. If I don't use .ToString() method then ValueKind = string is added

**Comment by RevathiNeminathan** [comment]
Were you able to reproduce the issue ? I always get false even if the gender is male

**Comment by StefH** [comment]
Do you use Newtonsoft json or system.text.json?

And this code works fine?
``` c#
void Main()
{
	var inputList = new Dictionary<string, object>();

	inputList.Add("gender", "Male");

	var props = new List<DynamicProperty>();
	props.Add(new DynamicProperty("gender", typeof(string)));

	Type type = DynamicClassFactory.CreateType(props, true);

	var obj = (DynamicClass)Activator.CreateInstance(type);

	var typeProps = type.GetProperties().ToDictionary(c => c.Name);

	foreach (var dict in inputList)
	{
		obj.SetDynamicPropertyValue(dict.Key, dict.Value);
	}

	var LstOfRecords = new List<DynamicClass>();
	LstOfRecords.Add(obj);
	LstOfRecords.AsQueryable().Where("gender == \"Male\"");
}
```

Can you please update my working example code (above) to code what you are trying to do and that fails?

**Comment by RevathiNeminathan** [comment]
In my post I mentioned below lines
inputList.Add("gender","Male"); // --> Working
inputList.Add("gender",EmployeeData); // --> not working
The problem arises when I parse the data from jsondocument and jsondocument by default uses system.text.json

**Comment by StefH** [comment]
Please post a full working example, including how you define `EmployeeData`.

**Comment by RevathiNeminathan** [comment]
class Program
    {
        static void Main(string[] args)
        {
            Dictionary<string, object> inputList = new Dictionary<string, object>();
            List<DynamicProperty> props = new List<DynamicProperty>();
            string EmployeeData = "{\"transactions\":[],\"profile\":{\"employeeCode\":\"EMP336\",\"clientEmployeeCode\":\"CLIENT_EMP_1\",\"salutation\":\"Mr\",\"firstName\":\"Employee\",\"middleName\":\"\",\"lastName\":\"1\",\"gender\":\"Male\"},\"status\":false}";
            JsonDocument empDoc = JsonDocument.Parse(EmployeeData);

            var value = empDoc.RootElement.GetProperty("profile").GetProperty("gender");
            inputList.Add("gender", value);
            props.Add(new DynamicProperty("gender", value.GetType()));
            Type type = DynamicClassFactory.CreateType(props, true);
            var obj = (DynamicClass)Activator.CreateInstance(type);
            var typeProps = type.GetProperties().ToDictionary(c => c.Name);


            foreach (var dict in inputList)
            {

                obj.SetDynamicPropertyValue(dict.Key, dict.Value);

            }
            var InputData = new List<DynamicClass>();
            InputData.Add(obj);
            Console.WriteLine(InputData[0]);
            var result =InputData.AsQueryable().Where("gender == \"Male\"");
            Console.WriteLine(result);
            Console.WriteLine(result.ToList().Count);
        }
    }

**Comment by RevathiNeminathan** [comment]
@StefH were you able to reproduce the issue?

**Comment by StefH** [comment]
I can reproduce it.

However this is not really related to this library, but the way how comparison on**Value** differs from **Reference**.

![image](https://user-images.githubusercontent.com/249938/126892824-a85d5d5a-8241-4943-ae89-244c4bf72f01.png)


As you can see have "gender" (1) and "objectWithAStringValue" (2) the value "Male", but the equal check (3) resolves to false.
