### ISSUE TITLE
OrderBy - potential sql injection?

### ISSUE THREAD

**Issue by msciborski** [zzzprojects/System.Linq.Dynamic.Core#534]
## 1. Description
Is the OrderBy method safe from sql injection? I've discovered that I can execute .OrderBy("IIF(2=1,1,1/0)"), and it throws DiviedByZeroException. On the other hand, if I execute .OrderBy("SELECT *"), then it throws ParseException("No property or field 'SELECT' exisit in type T".

**Comment by StefH** [comment]
Hello @msciborski,

All dynamic methods are safe for SQL injection because they are translated via LINQ / Database Query provider to valid SQL commands.

**Comment by Ali-Bdeir** [comment]
Bumping @nev-21's question
