### ISSUE TITLE
OrderBy not working with dynamic parameters

### ISSUE THREAD

**Issue by TheGreeNSparT** [zzzprojects/System.Linq.Dynamic.Core#536]
## 1. Description
I'm trying to use the OrderBy method with argument. For a reason unknown to me, I don't have any exception but my result is not ordered. 

Here is my code : 
``` c#
var Query = _MyDBContext.MyTable.AsQueryable<MyTable>();
var datas = Query.OrderBy("@0 " + (sortDir == "asc" ? sortDir : "desc"), sortBy).ToList();
```

where sortDir is equal to either "desc" or "asc" and sortBy is the name of the property I want to order by.I checked the value of sortBy while debugging and it was the correct property name. Query is just an IQueryable.

If I change my code like this, it works :
``` c#
var Query = _MyDBContext.MyTable.AsQueryable<MyTable>();
var datas = Query.OrderBy("ID " + (sortDir == "asc" ? sortDir : "desc")).ToList();
```
where ID is the property name.

Is there an issue with my use of parameters with OrderBy ?

Thanks in advance.

**Comment by StefH** [comment]
What happens if you use:
``` c#
string sortByProperty = "ID";
string sortBy = $"{sortByProperty} {(sortDir == "asc" ? sortDir : "desc")}";
var datas = Query.OrderBy("@0", sortBy).ToList();
```

**Comment by TheGreeNSparT** [comment]
> What happens if you use:
> 
> ```cs
> string sortByProperty = "ID";
> string sortBy = $"{sortByProperty} {(sortDir == "asc" ? sortDir : "desc")}";
> var datas = Query.OrderBy("@0", sortBy).ToList();
> ```
Thank you for your quick reply. 
I don't get any errors, but unfortunately the results are still not ordered :(

**Comment by StefH** [comment]
Hello @TheGreeNSparT,

I did some debugging and checked the documentation, but this is not possible.
Using `@0` is only for **values**.

https://dynamic-linq.net/expression-language#identifiers
![image](https://user-images.githubusercontent.com/249938/128641707-d6766f1c-b9fc-44d6-9e50-7b80e9d4a346.png)

**Comment by AdamGovier** [comment]
Hi @StefH, is there any work around for this?
