### ISSUE TITLE
Could not load file or assembly 'System.Linq.Dynamic.Core' in newer releases

### ISSUE THREAD

**Issue by Jupakabra** [zzzprojects/System.Linq.Dynamic.Core#538]
## 1. Description
I'm a library creator who uses `System.Linq.Dynamic.Core` as a reference. I recently updated dynamic linq reference from `1.0.0` to `1.2.X` and my library consumers started getting assembly load exceptions. I bisected it back to `1.0.21` version as a first failing one. Did something change from that release onwards in nuget packaging or compiling?

## 2. Exception
```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Linq.Dynamic.Core, Version=1.0.21.0, Culture=neutral, PublicKeyToken=0f07ec44de6ac832'. The system cannot find the file specified.
```

## 3. Fiddle or Project
Sorry don't have one.

## 4. Any further technical details
A workaround seems to be including a direct `System.Linq.Dynamic.Core` reference in the project consuming my library.

**Comment by StefH** [comment]
@Jupakabra 
Version 1.0.0 is very old (from 2016), a lot has been changed since then.

And I cannot remember / see anymore in the changelog what exactly had been changed between 1.0.20 and 1.0.21

So in order to help you further, I really need an example project to reproduce your issue.
