### ISSUE TITLE
Documentation for expression syntax

### ISSUE THREAD

**Issue by zspitz** [zzzprojects/System.Linq.Dynamic.Core#54]
Thanks for taking up this project; it fills the niche between compile-time LINQ and expressions built using static methods on System.Linq.Expressions,Expression.

The previous incarnation of this project by https://github.com/NArnott had excellent documentation on the expression syntax used by Dynamic LINQ (including nested query expressions such as `Any` or `Where` within the string), which this version seems to be lacking.

Is there any such documentation?

**Comment by zspitz** [comment]
I see that the original source is contained in this project; are the generated pages hosted anywhere?

**Comment by StefH** [comment]
I also copied/updated the documentation from @NArnott, this documentation/help page is available at https://system-linq-dynamic-core.azurewebsites.net

This project https://github.com/kahanu/System.Linq.Dynamic has some very detailed WIKI pages, which I always wanted to copy to my project, but did not have time for this.

I'm not aware of any other documentation.

**Comment by zspitz** [comment]
The link to the current documentation gets me to a simple listing of classes and members:
![current documentation](https://cloud.githubusercontent.com/assets/312166/20245529/06e88de0-a9ac-11e6-9263-c0c583f80ddc.png)
---
The previous documentation link looked like this:
![old documentation - home page](https://cloud.githubusercontent.com/assets/312166/20245532/2229a472-a9ac-11e6-8087-9e6c0122bebf.png)
Of particular interest was the **Getting Started** link, which had a detailed description of the entire expression syntax used by Dynamic LINQ:
![old documentation - getting started](https://cloud.githubusercontent.com/assets/312166/20245540/3f9e20c8-a9ac-11e6-8683-e0305a281b63.png)
and the **Expressions** link, which had a list of methods and keywords that could be used within string expressions:
![old documentation - expression methods expression keywords](https://cloud.githubusercontent.com/assets/312166/20245552/622d24ea-a9ac-11e6-87c7-ce1c6f9e8863.png)
As I said, the source for this documentation is [in the project repo](https://github.com/StefH/System.Linq.Dynamic.Core/tree/master/web/DynamicLinqWebDocs); it can be viewed locally by setting the `.csproj` file in that directory to the startup project.
---
The documentation you point to at https://github.com/kahanu/System.Linq.Dynamic is almost all about standard compiled LINQ (with the exception of https://github.com/kahanu/System.Linq.Dynamic/wiki/Dynamic-Expressions) and perhaps shouldn't be included in the documentation for this project.

**Comment by StefH** [comment]
My help page is indeed more like a class/member description, although there is also some example code present:
https://system-linq-dynamic-core.azurewebsites.net/html/21a732e6-735e-5b2d-765b-ba7931521dbe.htm

But I agree that this webpage is not that helpful for beginners and starters.

I actually wanted to move all the examples from web/DynamicLinqWebDocs into that new site because maintaining two help pages is too much work, but I never completed completely this move.

**Comment by zspitz** [comment]
Would you be willing to take a PR for this?

**Comment by StefH** [comment]
Would be an option.

What the best would be is to move that MVC help stuff to System.Linq.Dynamic.Core.SandCastle and link the "Library" page to the real Class Sandcastle generated page.

**Comment by jogibear9988** [comment]
Why don't we use the old Documentation? I tried to run it in VS2017 and it still works

**Comment by JonathanMagnan** [comment]
Hello all,

A website with some documentation has been released here: https://dynamic-linq.net/

Some sections, such as [Getting Started](https://dynamic-linq.net/overview), [Knowledge-Base](https://dynamic-linq.net/knowledge-base), and [Online Examples](https://dynamic-linq.net/online-examples) are already available.

@StefH is currently working to improve it so it will get better and better in the coming month.

I will currently close this issue as we are pretty much working on improving the documentation, and it will be easier to review what’s missing in a few months.

Best Regards,
 
Jon
 
---
 
**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)
 
**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
