### ISSUE TITLE
Expression of type 'Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable1[System.Boolean]' cannot be used for return type 'System.Collections.Generic.IEnumerable1[System.Object]'

### ISSUE THREAD

**Issue by emaborsa** [zzzprojects/System.Linq.Dynamic.Core#542]
As previously issued [here](https://github.com/dotnet/efcore/issues/25958):

EF Core version: 5.0.9
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL 5.0.7
Target framework: .NET 5.0
Operating system: Windows 10
IDE:  Visual Studio 2019

I am working with Dynamic Linq, when working with strings I have no problems, when dealing with bool's, i got the following error:

##### Expression of type 'Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1[System.Boolean]' cannot be used for return type 'System.Collections.Generic.IEnumerable`1[System.Object]'

For testing purpuses I wrote three cases:
``` c#
            IQueryable iQueryable = dbContext.MyEntity.AsQueryable();
            var one = iQueryable.Select("MyBooleanField").Distinct();
            var two = iQueryable.Select("MyBooleanField").Distinct().Cast<object>();
            var three = iQueryable.Select("MyBooleanField").Distinct().Cast<bool>();
```
`one` and `three` work fine, `two` leads to the above exception.
What's the problem?
I made a sample: [EF-Test.zip](https://github.com/zzzprojects/System.Linq.Dynamic.Core/files/7160133/EF-Test.zip)

**Comment by StefH** [comment]
@emaborsa 
I used your solution, and this data:
![image](https://user-images.githubusercontent.com/249938/176024453-5bf180ed-9d48-4fe5-b0e3-5cafaaab5e4b.png)


And this code works fine:
``` c#
IQueryable iQueryable = _context.Groups.AsQueryable();
var oneFirstOrDefault = iQueryable.Select("IsActiveDirectoryGroup").Distinct().FirstOrDefault();
var twoFirstOrDefault = iQueryable.Select("IsActiveDirectoryGroup").Distinct().Cast<object>().FirstOrDefault();
var threeFirstOrDefault = iQueryable.Select("IsActiveDirectoryGroup").Distinct().Cast<bool>().FirstOrDefault();

var oneToDynamicList = iQueryable.Select("IsActiveDirectoryGroup").Distinct().ToDynamicList();
var twoToDynamicList = iQueryable.Select("IsActiveDirectoryGroup").Distinct().ToDynamicList<object>();
var threeToDynamicList = iQueryable.Select("IsActiveDirectoryGroup").Distinct().Cast<bool>().ToDynamicList();


return new JsonResult(new
{
    oneFirstOrDefault,
    twoFirstOrDefault,
    threeFirstOrDefault,
    oneToDynamicList,
    twoToDynamicList,
    threeToDynamicList
});
```

-->

![image](https://user-images.githubusercontent.com/249938/176024340-90845b06-4838-4665-81bb-9bb43be489cd.png)
