### ISSUE TITLE
Single nested object unwraps into parent

### ISSUE THREAD

**Issue by penumbra23** [zzzprojects/System.Linq.Dynamic.Core#543]
Hi everyone! 👋 

First of excellent library helped me very much in my projects!

I have an issue that should be easy to solve, but I can't find any solution...
I'm using the latest version so far and the in-memory SQL package.

## Description
When having a class with a property of another class type, the child object unwraps instead of leaving as it is. For example,
``` c#
class Person {
    public string Name { get; set; }
    public Vehicle Vehicle { get; set; }
}

class Vehicle {
    public string Manuf { get; set; }
}
...
var query = context.Persons.Select("Name, Vehicle.Select(new { Manuf } as Car)")
```

throws 
`Unhandled exception. No property or field 'Manuf' exists in type 'Person'`

And this
`var query = context.Persons.Select("Name, Vehicle.Manuf as Car)")`
unwraps the Vehicle inside the Person object, so I get `Manuf` inside of `Person`

But this
`var query = context.Persons.Select("Name, Vehicle as Car)")`
returns fine with the `Vehicle` object nested inside the `Car` prop.

## Fiddle or Project
Here is an example with `Customer` and `Address`
https://dotnetfiddle.net/FO1vuS

Any ideas why and how to get the expected result of Vehicle nested inside Person?

**Comment by danijerez** [comment]
Something similar happens to me, did you manage to find a solution?

**Comment by penumbra23** [comment]
@danijerez Nope, still ongoing I guess

**Comment by StefH** [comment]
@penumbra23 
In your example the `AddressId` is a property from `Address`, not from `Person`.
So your code should look like:
``` c#
.Select(config, "new { CustomerID, City, CompanyName, np(Address.AddressId, -1) as Address }") 
```

--> I've added the `np` (Null Propagation) because for some Persons, the Address is null.

See https://dotnetfiddle.net/Cc0ZOY

**Comment by danijerez** [comment]
What if I want to select a field that is not a number? I was trying it like this

```
public class Stay
    {
        public string Id {get; set;}
        public string Cause {get; set;}
        public DateTime? EntryDate {get; set;}
        public DateTime? DischargeDate {get; set;}
        public List<Room> Room {get; set;}
        public List<Patient> Patient {get; set;}
    }
```

```
public class Room
    {
        public string Id {get; set;}
        public string Code {get; set;}
        public bool Active {get; set;}
    }
```

T is Stay

`result.Select<T>($"new (np(Room.Code,-1) as Room)");`

 but I get the following error

"Neither of the types 'String' and 'Int32' converts to the other"

**Comment by StefH** [comment]
Did you try this code:

``` c#
result.Select<T>($"new (np(Room.Code, \"\") as Room)");
```

**Comment by danijerez** [comment]
the following happens to me
`"Unable to promote expression 'IIF((((Param_0 != null) AndAlso (Param_0.Room != null)) AndAlso (Param_0.Room.Code != null)), Param_0.Room.Code, \"\")'."`

**Comment by StefH** [comment]
@danijerez Can you provide a dotnet fiddle for this ?

**Comment by danijerez** [comment]
Let me know if the example works for you, I did it a little fast
https://dotnetfiddle.net/ij3o3e

**Comment by StefH** [comment]
This : `Select<Stay>` cannot work because the result from the dynamic expression is not a `Stay` object.

See fixed fiddle:
https://dotnetfiddle.net/K7Fxto

**Comment by danijerez** [comment]
I understand, and could the result of the Room select be integrated so that the output was <Stay> ? to be able to combine levels of depth

example

```
"results": [
    {
      "cause": "Dog bite",
      "room": {
        "code": "R-01"
      },
```

**Comment by StefH** [comment]
Hello @danijerez,

I'm not sure what you mean, can you please update my https://dotnetfiddle.net/K7Fxto so that this reflects your question?

**Comment by danijerez** [comment]
Don't worry, in the end I took an alternative with reflection to achieve what I wanted, thanks for the support!
