### ISSUE TITLE
IComparer<T> not supported for OrderBy?

### ISSUE THREAD

**Issue by NetMage** [zzzprojects/System.Linq.Dynamic.Core#548]
How can the `OrderBy` overloads that take an `IComparer` actually be used, since the calls generated expect the types passed to the comparer match the types of the dynamic fields created by the string expression?

Is there any way to have an `IComparer<object>` be used?

**Comment by StefH** [comment]
Hello @NetMage,

The `IComparer` is supported, a unit test can be found here:
https://github.com/zzzprojects/System.Linq.Dynamic.Core/blob/master/test/System.Linq.Dynamic.Core.Tests/QueryableTests.OrderBy.cs#L10

(`IComparer<object>` is compatible with `IComparer`)

**Comment by NetMage** [comment]
Except that test only works if the string for the field is actually the name of a string field. Try again with an integer field and your passed in IComparer object will be the wrong type.

**Comment by StefH** [comment]
Hello @NetMage,

Can you check this test:
https://github.com/zzzprojects/System.Linq.Dynamic.Core/blob/stef-add-more-OrderByIComparer-unittests/test/System.Linq.Dynamic.Core.Tests/QueryableTests.OrderBy.cs#L40

And provide some insights from your side?

**Comment by maxime-ducoroy** [comment]
I have the same problem, 
I have some code similar to the link you sent [(QueryableTests.OrderBy.cs#L10)](https://github.com/zzzprojects/System.Linq.Dynamic.Core/blob/master/test/System.Linq.Dynamic.Core.Tests/QueryableTests.OrderBy.cs#L10)
For information I use .NET 6, EF Core 6.0.3, and a PostgresSQL database.
Here is my code: 
```
query.OrderBy($"{columnName} {(sorting.Descendant ? "desc" : "asc")}", StringComparer.OrdinalIgnoreCase)
```

The error in visual studio when I run the code 
```
The LINQ expression 'DbSet<Reference>()
    .Include(_ => _.Warehouse)
    .Include(_ => _.Departments)
    .Include(_ => _.Nature)
    .OrderBy(
        keySelector : => .Nature.Description, 
        compare : __p_0)' 
could not be translated. Either rewrite the query in a form that can be translated, 
or explicitly switch to client evaluation by inserting
 a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList' or 'ToListAsync'. 
See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
 ```
 
 Can you please help me?

**Comment by StefH** [comment]
@NetMage Did you have time to look at my new / updated UnitTests ?

@maxime-ducoroy Maybe it's related to Postgress database? Did you try SQL ? Or can you provide a full working example project?

**Comment by i-am-jyotirmaya** [comment]
OrderBy accepts a IComparer but it have to impement both IComparer and IComparer<object>. It would look something like,
```
public class CustomComparer : IComparer<object>, IComparer
	{
		public int Compare(object x, object y)
		{
			// Compare here
		}
	}
```

**Comment by StefH** [comment]
@i-am-jyotirmaya 
I understand your issue.

I've changed the code so that you can also provide an `IComparer<T>` to the order extension method:
``` c#
 var orderByDynamic = qry.OrderBy("Income", new ObjectComparer()).ToArray();
```

**Comment by StefH** [comment]
https://github.com/zzzprojects/System.Linq.Dynamic.Core/pull/584
