### ISSUE TITLE
Missing parse from binary literal to integer

### ISSUE THREAD

**Issue by RafaelEnriquez** [zzzprojects/System.Linq.Dynamic.Core#552]
ExpressionParser parses from hexadecimal literal to integer, but is missing a parse from binary literal to integer.

https://dotnetfiddle.net/cTfqh7

Exception

**Comment by StefH** [comment]
https://github.com/zzzprojects/System.Linq.Dynamic.Core/pull/554

**Comment by RafaelEnriquez** [comment]
Hi @StefH , thanks for your work on this.

I was expecting the fix to be something like the existing code for hexadecimal in "ExpressionParser.ParseIntegerLiteral".

Does this PR makes the provided fiddle test pass???

Regards

**Comment by StefH** [comment]
Hello @RafaelEnriquez,

I did move some code from `ExpressionParser.ParseIntegerLiteral` to a new file and also added some more tests for that new code.

See 
https://github.com/zzzprojects/System.Linq.Dynamic.Core/blob/stef-binary/test/System.Linq.Dynamic.Core.Tests/Parser/NumberParserTests.cs#L137

(I think this covers your scenario, but if you have questions or want to add more test, please let me know)

**Comment by StefH** [comment]
Hello @RafaelEnriquez, did you have time to check if the unit-test is enough for your scenario?

**Comment by RafaelEnriquez** [comment]
Hi @StefH . Yes, the tests you added are enough.

Thank you very much.
