### ISSUE TITLE
Support Cast/As for non enumerable properties

### ISSUE THREAD

**Issue by dsidedp** [zzzprojects/System.Linq.Dynamic.Core#566]
Consider the following

```csharp
    public class BaseClass {}

    public class DerivedClass1 
    {
        public int DerivedProperty1 { get; set; }
    }

    public class DerivedClass2
    {
        public int DerivedProperty2 { get; set; }
    }

    public class SomeClass
    {
        public BaseClass Item { get; set; }
    }
```
As far as I understand, currently, it is not possible to filter ``List<SomeClass>`` based on ``SomeClass.Item`` derived class property value since there is no way to cast non-enumerable property ``SomeClass.Item`` to ``DerivedClass1`` or ``DerivedClass2``:

Please consider supporting Cast/As/Is for non-enumerable properties.

```csharp
    var list = new List<SomeClass>(){.....};
    //cast function
    var result1 = list.Where("Cast(Item, DerivedClass1).DerivedProperty1 == str")
    //this should correspond to 
     var linq1 = list.Where(x=> ((DerivedClass1)x.Item).DerivedProperty1 == str)

    //as/is as operators or functions
    var result2 = list.Where("(Item as DerivedClass1).DerivedProperty1 == str")
    var result3 = list.Where("As(Item, DerivedClass1).DerivedProperty1 == str")
    var linq2 = list.Where(x=> (x.Item as DerivedClass1).DerivedProperty1 == str)
```
``result1`` and corresponding ``linq1`` cases are very useful when parsed expression is passed to EF or other ORMs with inheritance support.

Thanks.

**Comment by StefH** [comment]
Hello @dsidedp , did you also investigate if the `OfType` functionality could help in this scenario?


See below links on how to use it:
- https://github.com/zzzprojects/System.Linq.Dynamic.Core/blob/9ca9b3428961ebb757e8e4129195486b9be5dddf/test/System.Linq.Dynamic.Core.Tests/QueryableTests.Is%2COfType%2CAs%2CCast.cs
- https://dynamic-linq.net/basic-query-operators#cast-and-oftype

**Comment by dsidedp** [comment]
``OfType`` is applicable to enumerables only.  ``As'`` as applied to ``It`` but not to ``It.Property``.

Maybe I miss something, but I was not able to cast property of ``it`` when property is not Enumerable.

**Comment by dsidedp** [comment]
This is the not the case. 

In example you referred to, cast is applied to `it` to get access to ``it.DerivedProperty``. And I'm talking about casting ``it.Property`` to get access to ``it.Property.DerivedProperty``. 

If ``it.Property`` is Enumerable, then ``OfType`` can be used. But there are no options if ``it.Property`` is an object. 
Take a look at pseudo-code example is provided in the first comment.

BTW, here is the similar issue [https://github.com/zzzprojects/System.Linq.Dynamic.Core/issues/519](https://github.com/zzzprojects/System.Linq.Dynamic.Core/issues/519)

**Comment by StefH** [comment]
@dsidedp 
I understand.

This is not yet supported, but this can be added.

Would this syntax be ok?
``` c#
        [Fact]
        public void IsAndCastToType_Dynamic_ActingOnProperty_And_GetProperty()
        {
            // Assign
            var qry = new []
            {
                new EmployeeWrapper { Employee = new Worker { Name = "1", Other = "x" } }, 
                new EmployeeWrapper { Employee = new Boss { Name = "2", Function = "y" } }
            }.AsQueryable();

            // Act
            var cast = qry.Select(c => c.Employee is Worker ? ((Worker) c.Employee).Other : "-").ToArray();
            var castDynamic = qry.Select("iif(Is(Employee, \"System.Linq.Dynamic.Core.Tests.Entities.Worker\"), Cast(Employee, \"System.Linq.Dynamic.Core.Tests.Entities.Worker\").Other, \"-\")").ToDynamicArray();

            // Assert
            Check.That(cast.Length).Equals(castDynamic.Length);
        }
```

**Comment by dsidedp** [comment]
Sure.

IMHO, that's the simplest and most obvious syntax.

**Comment by StefH** [comment]
simple type resolution will be supported with:
``` c#
var config = new ParsingConfig
{
  ResolveTypesBySimpleName = true
};
```

**Comment by StefH** [comment]
A new version will be released soon.


#567

**Comment by dsidedp** [comment]
Thank you for the fast update.
