### ISSUE TITLE
DynamicLinqTypeAttribute does not support custom structs

### ISSUE THREAD

**Issue by dolunay** [zzzprojects/System.Linq.Dynamic.Core#578]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description
I create a custom struct for combine decimal with unit types. named as Measurable. The struct can convert numbers with many unit types. 

## 2. Exception
Does not generate any exception. Because, I cant set the [DynamicLinqType] declaration.

Please change the code like this:

Path to file : src/System.Linq.Dynamic.Core/CustomTypeProviders/DynamicLinqTypeAttribute.cs

line 6:  [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum, AllowMultiple = false, Inherited = false)]

**Comment by StefH** [comment]
https://github.com/zzzprojects/System.Linq.Dynamic.Core/pull/579

**Comment by dolunay** [comment]
Thank you for your response. With this development, it will be possible to use 'attribute' for 'struct'.
