### ISSUE TITLE
Convert string lambda expression with anonymous type

### ISSUE THREAD

**Issue by Josrph** [zzzprojects/System.Linq.Dynamic.Core#582]
am new to this library so I don't know if what am trying to do is possible or not

I have a string lambda expression with anonymous type which am trying to convert to an actual object lambda expression :

`"x => new { x.ID,  x.Name }" ====> Expression<Func<Product, object>> exp = x => new { x.ID,  x.Name };
`
so my question is can this be done in this library? and How?

Note: Product class has ID and Name properties.

**Comment by StefH** [comment]
@Josrph 

Please provide a full working (console-app) example which describes your problem.

**Comment by StefH** [comment]
@Josrph 
Did you have time to build a full working example?

**Comment by StefH** [comment]
@Josrph 
I think this can be solve using : https://eval-expression.net/
