### ISSUE TITLE
Can't Translate Empty Parameters

### ISSUE THREAD

**Issue by PostAlmostAnything** [zzzprojects/System.Linq.Dynamic.Core#588]
I have a scenario in which I need to use OrderBy and ThenBy for some sorting operation, but just OrderBy for most operations. For instance, if I want to order posts by like count I only use OrderBy, but if I need to sort by ratings I must also use ThenBy for rating count because otherwise you get a bunch of stuff with 1 or 2 five star reviews even thought there are those with more. Unfortunately, Linq.Dynamic.Core does not seem capable of translating empty strings properly.

Here is an example:
``` c#
string sortBy = "Ratingavg DESC";
string thenBy = "Ratingcount DESC";
... OrderBy(sortBy).ThenBy(thenBy)
```

The above works, but if I need to pass parameters without a value for thenBy it fails. The exact error says 

"The string argument 'ordering' cannot be empty."

Would it be possible for you guys to include a change in your next update which treats any query featuring ThenBy with an empty parameter as if there is no ThenBy at all? That would work much better than trying to translate it into the SQL equivalent with an empty string that won't work anyway. You could simply add a line of code saying that if the query includes ThenBy and the parameter is empty then the query has no ThenBy.

I am trying to come up with an efficient dynamic task capable of filtering, paging, and sorting for any number of parameters. This requires that sometimes the parameters be null or empty. Otherwise I find myself having to write a different task for each combination of parameters and choosing which one to use in the view based on RouteData.Value. My hope is that this last part has more to do with my lack of familiarity with LINQ syntax than anything else because I have a hard time finding ways to add if statements to LINQ queries.

**Comment by StefH** [comment]
Hello @PostAlmostAnything,

I understand your question and proposal, however adding this could break some usage by other projects. So for now I would suggest that you build your own extension method like:
```OrderByAndThenBy(sortBy, thenBy)```
