### ISSUE TITLE
Possible to restrict selectable properties?

### ISSUE THREAD

**Issue by DanielStout5** [zzzprojects/System.Linq.Dynamic.Core#589]
I'd like to use this library in a way where the frontend can decide which properties to include in the response, so I'm passing up a string e.g. `new { Id, Name, Age }` for the select in e.g. `var people = db.People.Select(select).ToDynamicList()` - but there are some properties that should not be possible to select.

I was imagining an attribute that could be placed on properties to block them from being selectable, just as if they didn't exist on the type.

The workaround I've found is to use AutoMapper's `ProjectTo` method for IQueryable to map to a different type that doesn't have the "hidden" properties - in that case, passing up a Select for a hidden property does cause an error. 

This seems like a common situation, so I'm wondering if there is something built into `System.Linq.Dynamic.Core` already to handle it directly?

**Comment by StefH** [comment]
@DanielStout5 
This functionality is not present, and probably will not added soon.
