### ISSUE TITLE
Bug on where clause with composite string 

### ISSUE THREAD

**Issue by GrandStrateguerre** [zzzprojects/System.Linq.Dynamic.Core#623]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description
Try to execute a query  with a where as :

``` c#
.Where("field1 == @0 & Field2 <> @1", "xxx", "")
```
The second parameter is empty string.

## 2. Exception
No excexption raise

## 3. technical details

Get the log of what  entity  generates :
```
WHERE (('XXX' = "Extent1"."field1 ") AND ("Extent1"."field1 " IS NOT NULL) AND 
( NOT (('' = "Extent1"."Field2 ") AND ("Extent1"."Field2 " IS NOT NULL))))
```

The error  is in Field2 " IS NOT NULL=> shoud  be IS NULL without NOT because we set a NOT before :
![image](https://user-images.githubusercontent.com/86523070/183671148-115f0fd6-0435-497e-b906-9053c24b072a.png)

with Field2 != @1 => gives the same issue

**Comment by GrandStrateguerre** [comment]
Finally à replace by :

![image](https://user-images.githubusercontent.com/86523070/183706578-229a25f1-65f1-4b03-b2dc-c3d401b2ba87.png)

and it works.

It sems that a empty string is not interpreted like a null .
Is is interpreded like a char.

And we see EF always add  IS NOT NULL....

it is still a bit confusing :)

I let you close or do something ?

**Comment by StefH** [comment]
https://github.com/zzzprojects/System.Linq.Dynamic.Core/pull/625

**Comment by StefH** [comment]
@GrandStrateguerre 
I'll close this.
