### ISSUE TITLE
Dynamic select results "No property or field 'MyProperty' exists in type 'List`1'"

### ISSUE THREAD

**Issue by LuigiMaestrelli** [zzzprojects/System.Linq.Dynamic.Core#628]
## 1. Description
I'm selecting fields dynamic on a class that has as list property mapped as One to Many.
The client sends to the server an array on fields and the server convert the list to the lib's format.

This is a simple class to show my use-case.
```
public class Parent
{
	public int Id { get; set; }
	public List<Child> Children { get; set; } 
}

public class Child
{
	public int Id { get; set; }
	public string MyProperty { get; set; }
}
```
Every thing works fine except when I select an field from the Child object.

This is the select string that result and throws an error:
`new { Id, new { Children.MyProperty } as Children }`

## 2. Exception
"No property or field 'MyProperty' exists in type 'List`1'"

## 4. Any further technical details
.NET 6
DynamicCore version 1.2.20

**Comment by StefH** [comment]
Can you show the non dynamic linq select version?

**Comment by LuigiMaestrelli** [comment]
Sure. It will be something like this.

```
 return (from p in DbSet.Include(p => p.Children)
      select new
      {
          p.Id,
          Children = from c in p.Children
                     select new
                     {
                         c.Id,
                         c.MyProperty
                     }
      }).ToList();
```

**Comment by StefH** [comment]
@LuigiMaestrelli 
This will be something like:
``` c#
var resultDynamic = DbSet.Include(p => p.Children).Select("new (it.Id as ParentId, Children.Select(new (Id, MyProperty)) as Children)");
```
