### ISSUE TITLE
Orderby slow after upgrade from version 18

### ISSUE THREAD

**Issue by rubeesh** [zzzprojects/System.Linq.Dynamic.Core#638]
Orderby slow after upgrade from version 18 to version 20.
Working fine when downgraded to 18.
Project:. Net 6

**Comment by StefH** [comment]
@rubeesh 
Can you please provide a console app + database to reproduce this issue?

**Comment by StefH** [comment]
@rubeesh
Can you please provide a console app + database to reproduce this issue?

Else I cannot investigate this properly.

**Comment by rubeesh** [comment]
Sorry for the delayed response,

Below is the controller action:
`  
 
        public async Task<IActionResult> GetDeletedItems(string filter, string orderBy,  int pageNo = 0, int pageSize = 12)
        {
            var query = context.AppDeletedItems.AsQueryable();

            if (!string.IsNullOrEmpty(filter))
                query = query.Where(filter);

            var count = await query.CountAsync();

            if (string.IsNullOrEmpty(orderBy))
                orderBy = "DeletedOn desc";
            query = query.OrderBy(orderBy);

            query = query.AsNoTracking().Skip(pageNo * pageSize).Take(pageSize);
            return Ok(new PagedList<AppDeletedItem>
            {
                Items = await query.ToListAsync(),
                Count = count
            });
        }


`

Model:

`
   public class AppDeletedItem
    {
        [Key] public int Id { get; set; }

        [Required] public string EntityName { get; set; }

        [Required] public string ItemId { get; set; }

        [Required] public string Item { get; set; }

        [Required] public DateTime DeletedOn { get; set; }

        [Required] public string DeletedBy { get; set; }
    }
`

SQL Database Table:
`
CREATE TABLE [dbo].[AppDeletedItems](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[EntityName] [nvarchar](100) NOT NULL,
	[ItemId] [nvarchar](100) NOT NULL,
	[Item] [nvarchar](max) NOT NULL,
	[DeletedOn] [datetime2](7) NOT NULL,
	[DeletedBy] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_AppDeletedItems] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

`

**The above is working perfectly with version 1.2.18 but  it is very slow  in version 1.2.19 and 20**

Project Environment: .Net 6  Project

**Comment by StefH** [comment]
Can you provide the generated SQL which executed on the SQL-server for the old and the new version?

**Comment by rubeesh** [comment]
There is no difference between the generated sql:

Version="1.2.18" :
exec sp_executesql N'SELECT [a].[Id], [a].[EntityName], [a].[ItemId], [a].[DeletedBy], [a].[DeletedOn], [a].[Item]
FROM [AppDeletedItems] AS [a]
ORDER BY [a].[DeletedOn] DESC
OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY',N'@__p_0 int,@__p_1 int',@__p_0=0,@__p_1=12


Version="1.2.19"  & "1.2.20":
exec sp_executesql N'SELECT [a].[Id], [a].[EntityName], [a].[ItemId], [a].[DeletedBy], [a].[DeletedOn], [a].[Item]
FROM [AppDeletedItems] AS [a]
ORDER BY [a].[DeletedOn] DESC
OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY',N'@__p_0 int,@__p_1 int',@__p_0=0,@__p_1=12

THE SLOWNESS IS WHEN THE SORT IS DONE FOR THE FIRST TIME. HOWEVER THIS ISSUE IS NOT THERE FOR OLDER VERSIONS AND THE TIME DIFFERENCE IN THE SORT USING THE VESRION (18) AND VERSION (19) IS AROUND 25 SEC

**Comment by w0pr** [comment]
> The slowness is when the sort is done for the first time. However this issue is not there for older versions and the time difference in the sort using the version (18) and version (19) is around 25 sec

Have you compared execution plans (like this https://dba.stackexchange.com/a/250978/16642) and cleared data caches (https://stackoverflow.com/a/55307666/539056) before measuring execution time?

**Comment by rubeesh** [comment]
> Hello @rubeesh, thanks for the information, however in order to have the exact same setup as you, the only way to debug this is if you provide a full working console app + example database (or use Northwind for example or https://github.com/chriseaton/docker-adventureworks) to test this issue.

Thanks for the response.
The issue is resolved after I upgraded the version to 1.2.22
