### ISSUE TITLE
Can you add a demo project as document

### ISSUE THREAD

**Issue by binson143** [zzzprojects/System.Linq.Dynamic.Core#64]
It would be awesome if you provide a sample console application which demonstrate the features of the  Library

**Comment by StefH** [comment]
Sounds good, however this is a lot of work. Better would be to use the unit-tests for that.

**Comment by jogibear9988** [comment]
We could also look to bring back the documentation of NArnott, this one was very good. I've a fork of his old repo with the html doku: https://github.com/jogibear9988/System.Linq.Dynamic/tree/master/Src/DynamicLinqWebDocs

**Comment by StefH** [comment]
The old documentation project is still there:
https://github.com/StefH/System.Linq.Dynamic.Core/issues/59

**Comment by JonathanMagnan** [comment]
Hello all,

A website with some documentation has been released here: https://dynamic-linq.net/

A lot of online examples is already available here: https://dynamic-linq.net/online-examples

@StefH is currently working to improve the documentation so it will get better and better in the coming month. So he might bring back some examples as well from the old documentations.

I will currently close this issue as we are pretty much working on improving the documentation, and it will be easier to review what’s missing in a few months.

Best Regards,
 
Jon
 
---
 
**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)
 
**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
