### ISSUE TITLE
NullReferenceException during json serialize of DynamicClass

### ISSUE THREAD

**Issue by BlueBasher** [zzzprojects/System.Linq.Dynamic.Core#640]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description
DynamicClass throws exception when serializing to Json.

## 2. Exception
NullReferenceException

## 3. Fiddle or Project
```csharp
using Newtonsoft.Json;
using System.Linq.Dynamic.Core;
using System.Text.Json.Serialization;

DynamicProperty[] props = new DynamicProperty[] { new DynamicProperty("Name", typeof(string)), new DynamicProperty("Birthday", typeof(DateTime)) };
Type type = DynamicClassFactory.CreateType(props);
DynamicClass dynamicClass = Activator.CreateInstance(type) as DynamicClass;
dynamicClass.SetDynamicPropertyValue("Name", "Albert");
dynamicClass.SetDynamicPropertyValue("Birthday", new DateTime(1879, 3, 14));
Console.WriteLine(dynamicClass);

JsonConvert.SerializeObject(dynamicClass);

Console.ReadLine();
```
## 4. Any further technical details
It seems the issue has been fixed in [this commit](https://github.com/zzzprojects/System.Linq.Dynamic.Core/commit/c1a977158e04d9c77ad07e21fb4646d9ea0aecec).
This commit has been done a few minutes before creating release 1.2.20 but it is actually not part of that release.
Not sure if this was on purpose but it would be really nice if a new release could be made that includes the bugfix.

**Comment by StefH** [comment]
The fix is indeed not yet present in the new version.
https://github.com/zzzprojects/System.Linq.Dynamic.Core/blob/master/CHANGELOG.md

I'll also add this example to the unit-test to be sure that it works correct.

**Comment by BlueBasher** [comment]
Cool, thanks for the info! Do you have any indication when you expect version 1.2.21 to be released?

**Comment by StefH** [comment]
I'll try to release a new version this weekend.

**Comment by StefH** [comment]
https://github.com/zzzprojects/System.Linq.Dynamic.Core/pull/641
