### ISSUE TITLE
Valid lambda expressions produce a generic parse exception when used with a nullable parameter

### ISSUE THREAD

**Issue by girlpunk** [zzzprojects/System.Linq.Dynamic.Core#648]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description
A seemingly valid lambda expression (for example, `value => value == 1`) will parse correctly if given a not nullable parameter, but fail when used with a nullable one.

## 2. Exception
If you are seeing an exception, include the full exception details (message and stack trace).

```
Exception message: System.Linq.Dynamic.Core.Exceptions.ParseException: 'Expression of type 'Boolean' expected'
Stack trace:
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.Parse(Type resultType, Boolean createParameterCtor)
   at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(Type delegateType, ParsingConfig parsingConfig, Boolean createParameterCtor, ParameterExpression[] parameters, Type resultType, String expression, Object[] values)
   at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(Type delegateType, ParsingConfig parsingConfig, ParameterExpression[] parameters, Type resultType, String expression, Object[] values)
   at xxmyprojectxx.<GetPassValue>d__5.MoveNext() in C:\xxx\xxx.cs:line 159
```

## 3. Fiddle or Project
https://dotnetfiddle.net/fUWKrB

## 4. Any further technical details
Add any relevant detail that can help us.

**Comment by StefH** [comment]
@girlpunk 

I think there are some issues with your code. See my modified working below.

Can you check if this solution is applicable to you?

``` c#
[Theory]
[InlineData(1, true)]
[InlineData(5, false)]
public void DynamicExpressionParser_ParseLambda_Func2(int? input, bool expected)
{
    // Arrange
    var nullableType = typeof(int?);
    var functionType = typeof(Func<,>).MakeGenericType(nullableType, typeof(bool));
    var valueParameter = Expression.Parameter(nullableType, "value");

    // Act 1
    var expression = DynamicExpressionParser.ParseLambda(
        functionType,
        new ParsingConfig(),
        new[] { valueParameter },
        typeof(bool),
        "value != null && value == 1"
    );

    // Act 2
    var compiledExpression = expression.Compile();
    var result = compiledExpression.DynamicInvoke(input);

    // Assert
    result.Should().Be(expected);
}
```

**Comment by girlpunk** [comment]
Thanks for your help, the only difference I can see between the two is the lambdas I have (originally generated by [EamonNerbonne/ExpressionToCode](https://github.com/EamonNerbonne/ExpressionToCode)) are in the "full" `value => value != null && value == 1` format. Is the prior format not supported by `ParseLambda()`?

This format was being used as not all of the lambdas use `value` as the name of the parameter, as the generation frequently picks ``Nullable`123456`` or similar.

**Comment by StefH** [comment]
@girlpunk The format `value => value != null && value == 1` should work, but it has a bug. I've fixed this so that that expression is also supported.
Do you want to test a preview version to see it it works for your use-case?

**Comment by StefH** [comment]
Preview version `1.2.23-issue-648`

Can be found here:
https://www.myget.org/F/system-linq-dynamic-core/api/v3/index.json

**Comment by StefH** [comment]
@girlpunk 
Did you have time to validate?

**Comment by girlpunk** [comment]
Sorry, been a bit of a hectic week. Beyond variables names it all looks fairly similar. The only difference I can see is that `nullableType` would be known at compile-time in your example, whereas it's loaded from the result of a previous expression in mine.

I do now have a workaround, involving finding the parameter name by splitting on `=>` then removing it from the lambda string.

**Comment by StefH** [comment]
@girlpunk 
The real difference is that in your fiddle, you have:
``` c#
var valueParameter = Expression.Parameter(valueType);
```

And in my unit test  I have:
``` c#
var valueParameter = Expression.Parameter(valueType, "value");
```

If I remove the `, "value"` from my unit test code, I get an exception like "System.Linq.Dynamic.Core.Exceptions.ParseException : Expression of type 'Boolean' expected" when parsing `value => value != null && value == 1`.

So can you try that preview version with the correct valueParameter?

**Comment by girlpunk** [comment]
Right, ok. Unfortunately at the moment I can't guarantee that `value` is the correct parameter name. Let me see if I can figure out some parsing to detect it and pass the appropriate name to the `Expression.Parameter` call.

**Comment by StefH** [comment]
OK.
