### ISSUE TITLE
Implement casting to fully qualified type

### ISSUE THREAD

**Issue by StefH** [zzzprojects/System.Linq.Dynamic.Core#652]
``` c#
namespace X
{
    internal class Program
    {
        [DynamicLinqType]
        public enum ExampleEnum
        {
            Value1,
            Value2,
        };

        private static readonly ParsingConfig DefaultParsingConfig = new() { 
        };

        static void Main(string[] args)
        {
            var data = new[]
            {
                new { Value = ExampleEnum.Value1 },
                new { Value = ExampleEnum.Value2 },
            };

            // This should work:
            data.AsQueryable().Select(DefaultParsingConfig, $"\"{typeof(ExampleEnum).FullName}\"?(Value)");  

        }
    }
}
```

Related: https://github.com/zzzprojects/System.Linq.Dynamic.Core/issues/643

**Comment by StefH** [comment]
@jbhelm

I've update the code to support casting to a FullName type using `"` -->

`"\"System.DateTime\"(Value)"`
or
`"\"My.NameSpace.EnumX\"(Value)"`

Nullable does also work:

`"\"System.DateTime\"?(Value)"`
or
`"\"My.NameSpace.EnumX\"?(Value)"`

Can you please test preview:
**1.2.24-preview-02**

**Comment by jbhelm** [comment]
@StefH 
I've tried the preview in my scenario. I can confirm this works for me using fully qualified names, _without_ the `DynamicLinqType` attribute on the types. Thank you!

**Comment by StefH** [comment]
Thanks for testing.

**Comment by StefH** [comment]
Done
