### ISSUE TITLE
Ram Usage Spike in WinForms

### ISSUE THREAD

**Issue by jaafar-k** [zzzprojects/System.Linq.Dynamic.Core#655]
## 1. Description
When using Dynamic LINQ in a WinForms application, the ram usage increases by about 100 MB, no matter how much data is being returned. Simply using anything from the Dynamic LINQ library, whether it's a select, where, or any other method, the ram usage can be seen instantly increasing regardless of the data size. Some delay is also noticed as the form will pause until execution is done (as it is synchronous). Note that this only happens the first time Dynamic LINQ is used, the ram usage will increase and it will stay the same (around 140 MB in my experience), and any further usage will not be as slow.

## 4. Any further technical details
WinForms in .Net 6 (Core), with EF Core 7, and SQLite.

**Comment by StefH** [comment]
@jaafar-k 
Can you please provide a full working example?

**Comment by StefH** [comment]
@jaafar-k
Can you please provide a full working example?

**Comment by StefH** [comment]
@jaafar-k 
It's very difficult to analyze without a example project, please provide a full working example.

**Comment by StefH** [comment]
@jaafar-k 
Can you please provide a full example?

**Comment by StefH** [comment]
@jaafar-k
Can you please provide a full example?
