### ISSUE TITLE
Question about security

### ISSUE THREAD

**Issue by ItSkary** [zzzprojects/System.Linq.Dynamic.Core#660]
I have discovered that original System.Linq.Dynamic arround 2016 incorporate a security issue :
https://insinuator.net/2016/10/linq-injection-from-attacking-filters-to-code-execution/

Because i don't know how this product work, i would ask if such problem may affect also this tool, and if  the answer is yes, which conter measure/mitigation may be adopted to prevent the issue.

Thanks for clarification.

**Comment by JonathanMagnan** [comment]
Hello @ItSkary ,

Sorry for the delay, and thank you for reporting this.

We are currently working on this issue and hope to release a new version shortly with a fix.

Best Regards,

Jon

**Comment by StefH** [comment]
https://github.com/zzzprojects/System.Linq.Dynamic.Core/pull/669

**Comment by StefH** [comment]
Hello @ItSkary, a new version 1.3.0 will have this fix and will be released shorty.

**Comment by ItSkary** [comment]
Thanks a lot, i will update the package in my project ASAP
