### ISSUE TITLE
Question on projection of child object properties in a Select.

### ISSUE THREAD

**Issue by CJS2025** [zzzprojects/System.Linq.Dynamic.Core#661]
Thanks for a great product. I'm hoping you can help with the following.

## Description
See the fiddle below. I would like to know how to perform a projection on a child property of the collection type within a Select; in this case the collection type is Person and the child property of Person is Address. The goal is to only populate the properties of the Person and Person.Address that are required. I have this working for Person but can't figure out how to do if for Person.Address.

## Fiddle
Fiddle showing simple example
https://dotnetfiddle.net/nvU7DB

## Technical details
The reason for wanting this is to reduce the amount of columns being retrieved from the database. We are using Microsoft.EntityFrameworkCore Version 6.0.5, Microsoft.EntityFrameworkCore.SqlServer Version 6.0.5 to access an Azure SQLServer database.

**Comment by CJS2025** [comment]
I have found that if I include ParsingConfig as below

ParsingConfig parsingConfig = new ParsingConfig(){ AllowNewToEvaluateAnyType = true};
IEnumerable<Person> result = (IEnumerable<Person>)peopleQueryable.Select(parsingConfig, dynamicSelect); 

with the linq string "new Person(Id, FirstName, **new Address(it.Address.Id, it.Address.City) As Address**)" 

it will work but the comment on the property AllowNewToEvaluateAnyType  suggests it is a bad idea, without it I get the error "Unhandled exception. Type 'Address' not found", so I guess the question is why is the Address type not found?

**Comment by StefH** [comment]
Did you also try setting `ParsingConfig.ResolveTypesBySimpleName` to true?

**Comment by CJS2025** [comment]
Hi Stef, thanks that has got it working.

The code from my simple example would look like this.

string dynamicSelect = "new Person(Id, FirstName, new Address(it.Address.Id, it.Address.AddressLine1, it.Address.City) as Address)";
		
ParsingConfig parsingConfig = new ParsingConfig(){ResolveTypesBySimpleName = true};
		
IEnumerable<Person> result = (IEnumerable<Person>)peopleQueryable.Select(parsingConfig, dynamicSelect);
