### ISSUE TITLE
DateOnly support

### ISSUE THREAD

**Issue by EfrSyn** [zzzprojects/System.Linq.Dynamic.Core#667]
Hello, I have some DateOnly fields in our Database. (for example "MyDate")

I wasn't able to write a where string like:

" MyDate > DateOnly('2023-01-01') "

as I would have done with a DateTime Field.

I was able to work with DateOnly field using a parameter field (1)  but it's not really an option in my case as I have very complex where clause. 

Any suggestion / workaround?

Thank you!

(1) I mean : 
   var d = new DateOnly(2023,1,1);
   query.where(" MyDate > @0", d)

**Comment by StefH** [comment]
@EfrSyn 
Support for DateOnly and TimeOnly will be present in the next release.
