### ISSUE TITLE
Expression does not parse any more 1.2.25 (works in 1.2.24)

### ISSUE THREAD

**Issue by jogibear9988** [zzzprojects/System.Linq.Dynamic.Core#675]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description
I've the following expression:

``` c#
"DateTime.UtcNow.AddHours(2).ToString(\"o\")"
```

it parses correctly in 1.2.24, but fails in 1.2.25

## 2. Exception

```
Unhandled exception. Enum type 'UtcNow' not found (at index 24)
Command terminated by signal 6
```

## 3. Fiddle or Project
https://dotnetfiddle.net/0GEix9

**Comment by StefH** [comment]
This is related to https://github.com/zzzprojects/System.Linq.Dynamic.Core/issues/670

**Comment by jogibear9988** [comment]
@StefH Du you think it is a good Idea to change the default behavior? I think the Library is widely used and it would break many projects.

**Comment by StefH** [comment]
@jogibear9988 
I'm currently busy with other issues on this library, and will probably need to create a new minor version (1.3.x) because some other behavior also changes.

For this issue : I don't know yet, maybe I'll indeed revert the behavior back to 1.2.24

**Comment by StefH** [comment]
https://github.com/zzzprojects/System.Linq.Dynamic.Core/pull/676

**Comment by jogibear9988** [comment]
thx
