### ISSUE TITLE
DynamicExpression parser can't parse when there is a dot in a string

### ISSUE THREAD

**Issue by YeskaNova** [zzzprojects/System.Linq.Dynamic.Core#683]
## 1. Description
I need to parse a condition that checks that the Name of an entity is "System.Int32" , but because of the dot, I get an error. Could you see why is that happening please? It seems to me that it's a very simple situation.

## 2. Exception
Unhandled exception. '.' or '(' or string literal expected (at index 19)

## 3. Fiddle
https://dotnetfiddle.net/hdL13r

**Comment by StefH** [comment]
> 

You mean : 
``` c#
"Name=\"System.Int32\""
```
?

**Comment by YeskaNova** [comment]
Yes, this part \"System.Int32\"  is a string token and should not be interpreted by the interpretor.

**Comment by StefH** [comment]
What do you mean by string token?

The whole purpose from this library is to allow dynamic querying using a string expression, like:
``` c#
var resultDynamic = context.Customers
     .Where("City == \"Paris\"")
    .ToList();
```

https://dynamic-linq.net/basic-simple-query

**Comment by YeskaNova** [comment]
The string token is "System.Int32" .

For example, this code should work:

var resultDynamic = context.Customers
     .Where("City == \"System.Int32\"")
    .ToList();

"Paris" is a string token, and the interpretor should not try to understand what is "inside" the string. Like "1/0" should not be a problem but 1/0 will raise an exception, anything inside a string should not be considered by the interpretor. I don't see any usecase where intepreting inside a string is useful ( and that's not string interpolation )

**Comment by StefH** [comment]
It will be fixed in next release.

https://github.com/zzzprojects/System.Linq.Dynamic.Core/pull/687

**Comment by YeskaNova** [comment]
Great, thanks a lot!
