### ISSUE TITLE
Methods on type 'Enum' are not accessible.

### ISSUE THREAD

**Issue by DamienLaw** [zzzprojects/System.Linq.Dynamic.Core#696]
I'm using `Microsoft.EntityFrameworkCore.DynamicLinq@7.3.0` which has a dependency on `System.Linq.Dynamic.Core@1.3.0` and I'm getting an exception `Methods on type 'Enum' are not accessible (at index 3)` with query

``` c#
var status = Status.Active | Status.Inactive;
query = query.Where("@0.HasFlag(StatusColumn)", status); // I believe Enum.HasFlag() is triggering the error.
```

`status` is an enum as follows:
``` c#
public enum Status
{
    None = 0,
    Active = 1,
    Inactive = 2,
    Deleted = 4
}
```

I have tried both methods ([DynamicLinqTypeAttribute] and CustomTypeProvider) mentioned in https://github.com/zzzprojects/System.Linq.Dynamic.Core/issues/689#issuecomment-1465246450
to no avail.

How do I call a method on an `enum`, not a `class`.

**Comment by StefH** [comment]
https://github.com/zzzprojects/System.Linq.Dynamic.Core/pull/714

**Comment by StefH** [comment]
@DamienLaw 
This will be added in next release.
