### ISSUE TITLE
Dynamic query on timestamptz

### ISSUE THREAD

**Issue by emaborsa** [zzzprojects/System.Linq.Dynamic.Core#697]
Hi all,
my Model has a DateTime property:

``` c#
public class Appointment : Item
{
    public int ClientId { get; set; }
    public int? OperatorId { get; set; }
    public DateTime Date { get; set; }
    public decimal From { get; set; }
    public decimal To { get; set; }
    public string Notes { get; set; }

    public virtual Client Client { get; set; }
    public virtual Operator Operator { get; set; }
}
```
The DatabaseContext:
```c#
entity.Property(e => e.Date)
  .HasColumnType("timestamptz")
  .IsRequired()
  .HasColumnName("date");
```
I am using dynamic Linq query, I simply use a where condition over a iQueryable:

`iQueryable.Where(condition);`

The `condition` is fully dynamic, I build it based on the passed parametes. If the parameter is a filter for the `Date` property I don't really know how the query should be. I tried `Date == "2023-03-30T00:00:00.000Z"` and `Date == DateTime.Parse("2023-03-30T00:00:00.000Z")` I get:

`'timestamp with time zone' literal cannot be generated for Local DateTime: a UTC DateTime is required`.

The database field is a `timestamptz`. I already tried adding the attribute as mentioned [here](https://github.com/zzzprojects/System.Linq.Dynamic.Core/issues/240#issuecomment-456232845), did not help.

How has the condition to look like?

**Comment by StefH** [comment]
Maybe use something like:

``` csharp
var x = dbcontext.Appointments.Where("Date == @0", DateTime.Parse("2023-03-30T00:00:00.000Z").ToUniversalTime());
```

**Comment by StefH** [comment]
@emaborsa 
Did this answer help you?

**Comment by emaborsa** [comment]
Sorry, I have not been able to check it yet.

**Comment by StefH** [comment]
@emaborsa 
Did you have time to check?

**Comment by emaborsa** [comment]
Unfortunately I didnt, have to work on another project.

**Comment by StefH** [comment]
I'm closing this now.

In case you still have an issue, comment here or create a new issue.
