### ISSUE TITLE
Casting int to long in a Sum using Dynamic.linq throws an arithmetic exception

### ISSUE THREAD

**Issue by Bremms** [zzzprojects/System.Linq.Dynamic.Core#699]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description
We use dynamic linq to fetch lists with the sum of each column. Some columns are integers and reaches the max int value. When casting them to a double or any other type we get an error converting them.

## 2. Exception
```
Unhandled exception. System.Data.Entity.Core.EntityCommandExecutionException: An error occurred while reading from the store provider's data reader. See the inner exception for details.
 ---> System.Data.SqlClient.SqlException (0x80131904): Arithmetic overflow error converting expression to data type int.

```

## 3. Fiddle or Project
https://dotnetfiddle.net/ZwQHB2

## 4. Any further technical details
I've modified an existing fiddle from the website to replicate this issue.
Current data inside the list:
```

new Worker { Name = "w1", Other = "o1",Test= int.MaxValue },
			new Worker { Name = "w2", Other = "02",Test = int.MaxValue },
			new Boss { Name = "b", Function = "f", Test= int.MaxValue }
```

Whenever I try to cast Test to a double it throws the exception above
This is the query I try:
`var count = context.Employees.GroupBy(w=>true).Select("new(Double(SUM(Test)) as Test, SUM(Id) as Id )").FirstOrDefaultDynamic();`

**Comment by StefH** [comment]
@Bremms 

_I thought I did already answer this question, but somehow the answer got lost..._

---

When you rewrite that dynamic query to a normal LINQ query, it throws the same error. So it's not related to dynamic linq.

**Comment by StefH** [comment]
https://stackoverflow.com/questions/76016715/casting-int-to-long-in-a-sum-using-dynamic-linq-throws-an-exception
