### ISSUE TITLE
Dynamic Average does not support nullable types

### ISSUE THREAD

**Issue by daviscollins** [zzzprojects/System.Linq.Dynamic.Core#700]
## 1. Description
It appears that `System.Linq.Dynamic.Core.DynamicQueryableExtensions.Average()` differs from `System.Linq.Enumerable.Average()` in that it does not support averaging values of _nullable_ type `Int32?`.

Is this expected behavior or a bug?

## 2. Exception
```
Exception message: Specific method not found: Average
```
## 3. Fiddle or Project
[https://dotnetfiddle.net/kgbraA](https://dotnetfiddle.net/kgbraA)

## 4. Any further technical details
Filtering out the null values and casting to `Int32` or `Double` seems to work as an alternative (see Fiddle above).

**Comment by StefH** [comment]
This is fixed and will be included in next version.
