### ISSUE TITLE
GetAssemblyTypesWithDynamicLinqTypeAttribute fails to type load failures

### ISSUE THREAD

**Issue by philr** [zzzprojects/System.Linq.Dynamic.Core#702]
For .NET Framework, [`AbstractDynamicLinqCustomTypeProvider.GetAssemblyTypesWithDynamicLinqTypeAttribute()` calls `Assembly.GetExportedTypes()`](https://github.com/zzzprojects/System.Linq.Dynamic.Core/blob/3e4262a8e4b4eed322722b1a5f011ae5138247a2/src/System.Linq.Dynamic.Core/CustomTypeProviders/AbstractDynamicLinqCustomTypeProvider.cs#L137) and handles a resulting `ReflectionTypeLoadException`.

[`Assembly.GetExportedTypes()`](https://learn.microsoft.com/dotnet/api/system.reflection.assembly.getexportedtypes) will actually throw `FileNotFoundException` if an assembly cannot be loaded.

`ReflectionTypeLoadException` is only thrown by [`Assembly.GetTypes()`](https://learn.microsoft.com/dotnet/api/system.reflection.assembly.gettypes).

As a result, if there's a failure loading a type caused by a missing assembly, none of the types marked with `DynamicLinqTypeAttribute` in the assembly will be returned.

**Comment by StefH** [comment]
@philr Did you encounter this issue in your application, or did you check the source code?

Because the logic in the code is that if an assembly cannot be loaded, the `definedTypes` will be empty and no types will be returned for that assembly, but the next assembly will be analyzed.

**Comment by StefH** [comment]
@philr 
If you have time, can you verify that PR?

**Comment by philr** [comment]
@StefH I've added a review to the PR with a few comments.
