### ISSUE TITLE
DynamicExpressionParser.ParseLambda order by DESC not work

### ISSUE THREAD

**Issue by triumphtang** [zzzprojects/System.Linq.Dynamic.Core#707]
This statement runs good,
var orderByExpression = DynamicExpressionParser.ParseLambda<T, object>(new ParsingConfig() { }, true, "rowkey");
But after adding DESC, it suggested an error:
var orderByExpression = DynamicExpressionParser.ParseLambda<T, object>(new ParsingConfig() { }, true, "rowkey DESC");

**Comment by StefH** [comment]
@triumphtang 

ParseLambda does not support order-by.

If you want to use order-by / order-by DESC, use this:

``` csharp
var orderByIdDesc = qry.OrderBy("Id DESC");
```

**Comment by triumphtang** [comment]
Thanks
