### ISSUE TITLE
support return Tuple

### ISSUE THREAD

**Issue by xieyufei1220** [zzzprojects/System.Linq.Dynamic.Core#709]
I want to pass the specified fields and then return tuple. It's ok with linq to db but error with EF 6. The exception is : Only parameterless constructors and initializers are supported in LINQ to Entities.

code:
```c#
async Task Main()
{
	Pick<(string, string)>("x=>new {x.AuthorCode,x.AuthorName}").Dump();  
}

public List<T> Pick<T>(string selector)
{
	return this.Author.Select<T>(selector).ToList();
}
``` 

can be improved to support return tuple as linq to db?

**Comment by StefH** [comment]
Related to https://github.com/zzzprojects/System.Linq.Dynamic.Core/issues/491

**Comment by StefH** [comment]
Closing this one in favor of #491
