### ISSUE TITLE
Is there a way to convert lambda where expression into string representaion?

### ISSUE THREAD

**Issue by VyacheslavGarshin** [zzzprojects/System.Linq.Dynamic.Core#710]
Use case is that I have an endpoint which accepts a filter part as string.
I'm going to create a client application on .net and construct this filter part from the models I have from the server. 
Is there method like in this example `string filter = Customers.Where(x => x.Name.Contains("apple")).ToDynamicLinqFilter()`?
Tried to find it on stackoverflow and source code with no avail.

**Comment by zspitz** [comment]
If your `Where` returns an `IQueryable`, every `IQueryable` has an **Expression** property, returning an expression tree representing the query.

I've written a library which [creates strings from expression trees](https://github.com/zspitz/ExpressionTreeToString); one of the available representations is Dynamic LINQ:

```csharp
var qry = Customers.Where(x => x.Name.Contains("apple"));
var expr = qry.Expression
string filter = expr.ToString("Dynamic LINQ", "C#");
```

**Comment by VyacheslavGarshin** [comment]
Great project! Why there is no nuget package though?

**Comment by zspitz** [comment]
> Great project! Why there is no nuget package though?

https://www.nuget.org/packages/ExpressionTreeToString/

**Comment by VyacheslavGarshin** [comment]
My bad=) Have been looking Installation section in readme. Thanks a lot!

**Comment by StefH** [comment]
@VyacheslavGarshin 
Can I close your question since it's resolved by ExpressionTreeToString?

**Comment by VyacheslavGarshin** [comment]
> My bad=) Have been looking Installation section in readme. Thanks a lot!

Sure! And it would be nice to have some mentioning of the solution in documentation. This is a usual case in using API based on DynamicLinq and should help to promote it.
