### ISSUE TITLE
Select on ForeignKey properties: main level name missing

### ISSUE THREAD

**Issue by Hurricane31337** [zzzprojects/System.Linq.Dynamic.Core#715]
Using the `dbContext.TableName.Select("Property1, Property2.Property5")` syntax, how can I achieve that the property names in the output are kept exactly as put in? Currently, the result would contain Property1 and Property5 (instead of Property2.Property5).
Using the "AS" operator also doesn't help, because firstly I can't use dots in the renamed property name (as required) and secondly, it would be cumbersome to specify it for each selector over and over again.

I would very much welcome an optional parameter for the `Select` function to be able to keep the main level names.

**Comment by StefH** [comment]
This should be made possible in PR https://github.com/zzzprojects/System.Linq.Dynamic.Core/pull/719

### SupportDotInPropertyNames

Support a `.` in a property-name. Default value is `false`.

``` csharp
var config = new ParsingConfig
{
    SupportDotInPropertyNames = true
};

var result = persons.Select(config, "new (Profile.FirstName as Prof.Name)").ToDynamicArray();
```
