### ISSUE TITLE
ParseException ToString() does not contain stack trace

### ISSUE THREAD

**Issue by codelovercc** [zzzprojects/System.Linq.Dynamic.Core#716]
## 1. Description
When a System.Linq.Dynamic.Core.Exceptions.ParseException was thrown, It's hard to locate where cause this exception when I using NLog with layout renderer [${exception}](https://github.com/NLog/NLog/wiki/Exception-Layout-Renderer). I'm only can find a line `No applicable aggregate method 'Cast(Object)' exists (at index 3)` in my log file, but no stack trace, this makes me confused, I know this message means but I don't know where the exception thrown. It takes me a lot of time to find out where goes wrong.

## 2. Exception
System.Linq.Dynamic.Core.Exceptions.ParseException

```
Exception message: No applicable aggregate method 'Cast(Object)' exists (at index 3)
Stack trace: NA
```
I've read `System.Linq.Dynamic.Core.Exceptions.ParseException` source code and found that `ToString()` method simply return one line message.  Can we change this like the other exceptions do? Thanks :)

**Comment by StefH** [comment]
@codelovercc 

Thanks for this suggestion.

The next version will include InnerException (if present) and a StackTrace.

https://github.com/zzzprojects/System.Linq.Dynamic.Core/pull/717
