### ISSUE TITLE
background

### ISSUE THREAD

**Issue by NavirDev** [zzzprojects/System.Linq.Dynamic.Core#718]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description
Describe the issue or propose a feature.

## 2. Exception
If you are seeing an exception, include the full exception details (message and stack trace).

```
Exception message:
Stack trace:
```

## 3. Fiddle or Project
If you are able,

Provide a Fiddle that reproduce the issue: https://dotnetfiddle.net/25Vjsn

Or provide a project/solution that we can run to reproduce the issue.
- Make sure the project compile
- Make sure to provide only the code that is required to reproduce the issue, not the whole project
- You can send private code here: info@zzzprojects.com

Otherwise, make sure to include as much information as possible to help our team to reproduce the issue.

## 4. Any further technical details
Add any relevant detail that can help us.

**Comment by StefH** [comment]
@NavirDev Can you please fill in the issue template?
