### ISSUE TITLE
Enhance filtering capabilities using enum namespace string

### ISSUE THREAD

**Issue by victorplanag** [zzzprojects/System.Linq.Dynamic.Core#724]
# Description:

Currently, when filtering an enum class using dynamic LINQ, I'm manually converting string values to enum values and applying the filter. However, I believe there should be a more automated way to filter the enum based on its namespace string using reflection.

# Enum class example:

``` c#
public enum MyEnum
{
    Lorem,
    Ipsum,
    Dolor
}
```
# Current filtering approach:
``` c#
var filterStringValues = new string[] { "Lorem", "Dolor" };
var filterValues = filterStringValues.Select(v => (MyEnum)Enum.Parse(typeof(MyEnum), v));
query.Where("@0.Contains(EnumColumnName)", new List<object>() { filterValues });
```
# Requested enhancement:

I would like to suggest an improvement to the dynamic LINQ library to allow filtering based on the enum namespace string ("MyNamespace.MyEnum"). This way, the filtering process can be fully automated, eliminating the need for manual conversion.

# Example usage with proposed enhancement:

``` c#
var filterStringValues = new string[] { "MyEnum.Lorem", "MyEnum.Dolor" };
```
or
``` c#
var filterStringValues = new string[] { "MyNamespace.MyEnum.Lorem", "MyNamespace.MyEnum.Dolor" };
```
``` c#
query.Where("@0.Contains(EnumColumnName)", new List<object>() { filterStringValues });
```

By adding this feature, it will simplify the filtering process and make the library more flexible for dynamic enum filtering scenarios.

**Comment by StefH** [comment]
@victorplanag 
I understand your question ans use-case, however adding this would require to much magic-string-parsing.
What if a string really looks like "MyEnum.Lorem" and your just want to filter on this string and not an enum?

So I'll close this issue.
