### ISSUE TITLE
How can we do string interpolation using $?

### ISSUE THREAD

**Issue by tcortega** [zzzprojects/System.Linq.Dynamic.Core#733]
Seems like $ and it are equivalent, and a reserved keyword. How would we do string interpolation without having to use `string.Format`?

**Comment by StefH** [comment]
Can you provide a full example what you are trying to do?

**Comment by tcortega** [comment]
> Can you provide a full example what you are trying to do?

`new ExpressionParser(null, """$"{1+1}"+string.Empty""", null, null).Parse(null);`

Has a simple string interpolation but leads to the `No 'it' is in scope` exception.

**Comment by StefH** [comment]
This is not yet possible.

I'll add config setting
(https://github.com/zzzprojects/System.Linq.Dynamic.Core/pull/734)

**Comment by StefH** [comment]
Closing as not planned.
