### ISSUE TITLE
How to get the value of the key, and access its value pair

### ISSUE THREAD

**Issue by 3ggerhappy** [zzzprojects/System.Linq.Dynamic.Core#738]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description
Ok so I have a List(CustomObject) that I have successfully filtered and grouped. This returns a List(dynamic). (Key as Key, "it"(is List(CustomObject))
 I can iterate through it but failed to get the value of the key as string, then the Keys value pair w/c is a List(CustomObject)

## 2. Exception
If you are seeing an exception, include the full exception details (message and stack trace).

```
Exception message:
Stack trace:
```

## 3. Fiddle or Project
If you are able,

Provide a Fiddle that reproduce the issue: https://dotnetfiddle.net/25Vjsn

Or provide a project/solution that we can run to reproduce the issue.
- Make sure the project compile
- Make sure to provide only the code that is required to reproduce the issue, not the whole project
- You can send private code here: info@zzzprojects.com

Otherwise, make sure to include as much information as possible to help our team to reproduce the issue.

## 4. Any further technical details
Add any relevant detail that can help us.

**Comment by StefH** [comment]
@3ggerhappy 
The dotnetfiddle links to different code, can you please use the correct link?

**Comment by StefH** [comment]
@3ggerhappy 
Can you please update the dotnet fiddle?

**Comment by StefH** [comment]
@3ggerhappy
The dotnetfiddle links to different code, can you please use the correct link?

**Comment by StefH** [comment]
@3ggerhappy 
I'll close this question now. In case you have still questions, reply here.
