### ISSUE TITLE
An error is reported if the name is different

### ISSUE THREAD

**Issue by DotNetNext** [zzzprojects/System.Linq.Dynamic.Core#748]
![image](https://github.com/zzzprojects/System.Linq.Dynamic.Core/assets/12455385/121e4072-a650-445b-b528-0d7396b83893)

**Comment by DotNetNext** [comment]
Looks like it's a caching problem

**Comment by StefH** [comment]
@DotNetNext 
Please provide a full working example.
- console app
- - dotnet fiddle (https://dotnetfiddle.net/)

**Comment by StefH** [comment]
@DotNetNext 
Can you please provide a full working example / .net fiddle or demo project?

**Comment by DotNetNext** [comment]
Have already solved
Add:   x=>
