### ISSUE TITLE
System.Linq.Dynamic.Core: No applicable method 'ArrayLength' exists in type

### ISSUE THREAD

**Issue by tim-ilgiz** [zzzprojects/System.Linq.Dynamic.Core#749]
When parsing the expression I get the error “No applicable method 'ArrayLength' exists in type 'Product'”.

Here's the expression itself:

```
var experession = "p => (p.MarketingProduct!= null) AndAlso (ArrayLength(p.MarketingProduct.Categories) > 0)"
var result = DynamicExpressionParser.ParseLambda<Product, bool>(new ParsingConfig(), true, experession);
```
Is there any built-in solution to this problem in the System.Linq.Dynamic.Core library?

**Comment by StefH** [comment]
You can create an own static utils class with an (extension) method named `ArrayLength`.

See https://dynamic-linq.net/advanced-extending#examples
