### ISSUE TITLE
Getting exception the binder 'System.Linq.Dynamic.Core.DynamicGetMemberBinder' needs at least one restriction.

### ISSUE THREAD

**Issue by prchalla1** [zzzprojects/System.Linq.Dynamic.Core#753]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description
``` c#
  return data.AsQueryable().Select($"new ({string.Join(",", fields.Select(field => "@" + field + " as " + 
  field))})").ToDynamicList().Cast<dynamic>();
```
## 2. Exception

Exception Message:

> The result of the dynamic binding produced by the object with type <>f__AnonymousType0`40[System.Int32,System.String,System.Int32,System.String,System.Int32,System.Int32,System.Int32,System.String,System.Decimal,System.Decimal,System.Int64,System.Boolean,System.Int64,System.String,System.String,System.Int32,System.Int32,System.Decimal,System.String,System.String,System.Int32,System.String,System.String,System.String,System.String,System.Int64,System.String,System.String,System.String,System.Decimal,System.Int32,System.Decimal,System.String,System.Int64,System.String,System.Int32,System.Decimal,System.String,System.String,System.Int64]' for the binder 'System.Linq.Dynamic.Core.DynamicGetMemberBinder' needs at least one restriction.

## 3. Fiddle or Project
If you are able,

Provide a Fiddle that reproduce the issue: https://dotnetfiddle.net/qegOXK

Or provide a project/solution that we can run to reproduce the issue.
- Make sure the project compile
- Make sure to provide only the code that is required to reproduce the issue, not the whole project
- You can send private code here: info@zzzprojects.com

Otherwise, make sure to include as much information as possible to help our team to reproduce the issue.

## 4. Any further technical details
Add any relevant detail that can help us.

**Comment by StefH** [comment]
@prchalla1 
Can you please provide the correct fiddle?

**Comment by prchalla1** [comment]
> @prchalla1 Can you please provide the correct fiddle?

Fiddle Code: https://dotnetfiddle.net/qegOXK

In our code we are trying to access 40 properties and when running the code similar to fiddle link which is shared above getting exception at Line 25 as below: The result of the dynamic binding produced by the object with type <>f__AnonymousType0`40[System.Int32,System.String,System.Int32,System.String,System.Int32,System.Int32,System.Int32,System.String,System.Decimal,System.Decimal,System.Int64,System.Boolean,System.Int64,System.String,System.String,System.Int32,System.Int32,System.Decimal,System.String,System.String,System.Int32,System.String,System.String,System.String,System.String,System.Int64,System.String,System.String,System.String,System.Decimal,System.Int32,System.Decimal,System.String,System.Int64,System.String,System.Int32,System.Decimal,System.String,System.String,System.Int64]' for the binder 'System.Linq.Dynamic.Core.DynamicGetMemberBinder' needs at least one restriction.

**Comment by StefH** [comment]
In that provided fiddle, this exception is thrown:
```
Unhandled exception. System.InvalidOperationException: Unable to find property 'Capacity' on type '<>f__AnonymousType0`7
```

This because `Capacity` is a property from the **List**, not from the item in the list, so this cannot work.

**Comment by prchalla1** [comment]
Can you share details on how to resolve the exception:

**The result of the dynamic binding produced by the object with type** <>f__AnonymousType0`40[System.Int32,System.String,System.Int32,System.String,System.Int32,System.Int32,System.Int32,System.String,System.Decimal,System.Decimal,System.Int64,System.Boolean,System.Int64,System.String,System.String,System.Int32,System.Int32,System.Decimal,System.String,System.String,System.Int32,System.String,System.String,System.String,System.String,System.Int64,System.String,System.String,System.String,System.Decimal,System.Int32,System.Decimal,System.String,System.Int64,System.String,System.Int32,System.Decimal,System.String,System.String,System.Int64]' **for the binder 'System.Linq.Dynamic.Core.DynamicGetMemberBinder' needs at least one restriction.**

**Comment by StefH** [comment]
I'm sorry but I cannot help you unless you provide a fiddle or a unit test or a console app which demonstrates this specific problem.
