### ISSUE TITLE
Comparison on DateTime not accurate

### ISSUE THREAD

**Issue by ArnoKrohne** [zzzprojects/System.Linq.Dynamic.Core#768]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description
I am creating a where in which a datetime is compared like "TimeStamp > DateTime(ticks1) and TimeStamp < DateTime(ticks2)". This will return values where the TimeStamp > DateTime(ticks2) when the difference is in the seconds/milliseconds range.

## 2. Exception
No exception.

## 3. Fiddle or Project
Otherwise, make sure to include as much information as possible to help our team to reproduce the issue.

## 4. Any further technical details
The where is applied to an IQueryable which is created from an ordinary IEnumerable. EF Core is not used.

**Comment by StefH** [comment]
@ArnoKrohne 
Can you please prove a full working example unit-test or a dotnetfiddle?

**Comment by ArnoKrohne** [comment]
My apologies. After trying to recreate the issue in an example, I found out that there was a Local to UTC and vice versa problem in a string conversion which has nothing to do with dynamic linq.
