### ISSUE TITLE
try to call function inside select

### ISSUE THREAD

**Issue by mahdiyar021** [zzzprojects/System.Linq.Dynamic.Core#779]
im trying to call function inside select for get row number this work totally fine on  normal linq select like :

``` c# 
db.JsonWebTokens
               .Select(x=>new { Rank = Microsoft.EntityFrameworkCore.EF.Functions.RowNumber(EF.Functions.Over().OrderBy(x.Id)), x.Id }).ToArray();
```

but this not working on dynamic linq :
``` c#
 var res = db.JsonWebTokens
     .Select("x=>new { Microsoft.EntityFrameworkCore.EF.Functions.RowNumber(EF.Functions.Over().OrderBy(x.Id))  as Rank, x.Id }")
     .ToDynamicArray();
```
row number from extend library Zomp.EFCore.WindowFunctions.

exception  : Enum type 'Microsoft.EntityFrameworkCore.EF.Functions' not found

**Comment by StefH** [comment]
Probably related to https://github.com/zzzprojects/System.Linq.Dynamic.Core/issues/772

**Comment by StefH** [comment]
PR merged, a new NuGet will be released in some time

**Comment by mahdiyar021** [comment]
tnx
