### ISSUE TITLE
Question About Parameters

### ISSUE THREAD

**Issue by Mike-E-angelo** [zzzprojects/System.Linq.Dynamic.Core#784]
This is a question and not a bug report. :)  Your project works excellently and has been for many years for me.  I sent a PayPal donation to support the cause. 🙏

My question is about parameters.  I see that you support `@0` as input parameters for filtering.  I was wondering if that translates to -- or _can_ translate to -- parameterized in SQL when it gets compiled as a query to send to the database?

Thank you for any insight you can provide and thank you again for your efforts.

**Comment by Mike-E-angelo** [comment]
Thank you for that @mahdiyar021 but that looks different from what I am asking.  Mine is a general question that I have been too busy to investigate so I wanted to ask here to save me some time.  I guess we see where that got me. 😅

**Comment by Mike-E-angelo** [comment]
For further reference/context, I was running into an issue with Syncfusion `DataOperations` which does not (or did not, when I reported it) parameterize their queries.  They have since addressed this for a future release:
https://www.syncfusion.com/forums/186351/dataoperations-performfiltering-does-not-parameterize-values

At one point they were not going to address this, and my idea at the time was to use `System.Linq.Dynamic.Core` instead, but was unclear if the parameters made their way to SQL, too.  Now that Syncfusion has fixed this on their end this is no longer a priority/concern for me.

(It would be nice to know if parameters are still sent to SQL as designed, however :D )

**Comment by StefH** [comment]
Correct, you need to use the config:
``` C#
var config = new ParsingConfig
{
    UseParameterizedNamesInDynamicQuery = true
};

var result784 = context.Products.Where(config, "NullableInt = @0", 1).ToDynamicArray<ProductDynamic>();
```

This generates (e.g. Sqlite) this SQL:
``` sql
SELECT "p"."Key", "p"."NullableInt", "p"."Dict_Name"
      FROM "Products" AS "p"
      WHERE "p"."NullableInt" = @__Value_0
```

See ConsoleApp_net6.0_EF6_Sqlite for more details.
