### ISSUE TITLE
Parser interpreting the two consecutive escape sequences \"\" as a single escape sequence

### ISSUE THREAD

**Issue by brettwinters** [zzzprojects/System.Linq.Dynamic.Core#786]
Don't ask me why I'm doing this (but the output needs to be escaped json) but when I do the following: 

``` c#
DynamicExpressionParser
    .ParseLambda(typeof(object), "\"{\\\"PropertyA\\\":\\\"\\\"}\"")
    .Compile()
    .DynamicInvoke()
```

The parser outputs: `"{\"PropertyA\":\"}"`  vs `"{\"PropertyA\":\"\"}"` expected

The only thing that seems to work is if the string is as follows `"\"{\\\\\\\"PropertyA\\\\\\\":\\\\\\\"\\\\\\\"}\""`

Note: Parsing `"\"{\\\"PropertyA\\\":\\\"abc\\\"}\""` and `"\"{\\\"PropertyA\\\":\\\" \\\"}\""` (space) works correctly

**Comment by brettwinters** [comment]
#163 #307

**Comment by brettwinters** [comment]
BTW I'm using `System.Linq.Dynamic.Core` v1.3.10

**Comment by StefH** [comment]
#788

**Comment by StefH** [comment]
@brettwinters 
Can you please test preview version 1.3.11-preview-01?

From: https://www.myget.org/F/system-linq-dynamic-core/api/v3/index.json

**Comment by brettwinters** [comment]
Hi @StefH - I'm having some trouble using myget. Sorry about this but would you mind publishing to nuget? otherwise please could you point me to a online c# ide so I can write some tests?

**Comment by StefH** [comment]
This page describes how to use myget:
https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions

**Comment by brettwinters** [comment]
ok, got it.

When I run these tests using 1.3.10: 

```c#
[Theory]
[InlineData("\"{\\\"PropertyA\\\":\\\"abc\\\"}\"", "{\"PropertyA\":\"abc\"}")]
[InlineData("\"{\\\"PropertyA\\\":\\\" \\\"}\"", "{\"PropertyA\":\" \"}")]
[InlineData("\"{\\\"PropertyA\\\":\\\"\\\"}\"", "{\"PropertyA\":\"\"}")]
[InlineData("\"{\\\\\\\"PropertyA\\\\\\\":\\\\\\\"\\\\\\\"}\"", "{\\\"PropertyA\\\":\\\"\\\"}")]
public void GivenJsonString_WhenParseLambda_ThenShouldOutputEscapedJson(
	string jsonString,
	string expectedResult)
{
	var actualResult = DynamicExpressionParser
		.ParseLambda(typeof(object), jsonString)
		.Compile()
		.DynamicInvoke();
	
	Assert.Equal(
		expectedResult,
		actualResult?.ToString()
	);
}
```

They fail as originally described: 
<img width="334" alt="image" src="https://github.com/zzzprojects/System.Linq.Dynamic.Core/assets/26474006/b71976f1-3fa9-47b6-a31a-8a43066c4cd9">

Then when I run the same tests using 1.3.11-preview-01

<img width="278" alt="image" src="https://github.com/zzzprojects/System.Linq.Dynamic.Core/assets/26474006/c3d364ae-85ea-4a47-bcba-3a41e7057533">

All pass!

Thank you very much for your quick fix, I'll look out for 1.3.11

**Comment by StefH** [comment]
@brettwinters 
Some advice is needed.

I did introduce a new config enum like below to make sure that this solution is now the default, but if users want to use the old parsing, they can configure it.

Do you think it's a good naming?

``` C#
namespace System.Linq.Dynamic.Core.Config;

/// <summary>
/// Defines the types of string literal parsing that can be performed.
/// </summary>
public enum StringLiteralParsingType : byte
{
    /// <summary>
    /// Represents the default string literal parsing type. Double quotes should be escaped using the default escaping.
    /// E.G. var expression = "StaticHelper.Filter(\"UserName == \\\"x\\\"\")";
    /// 
    /// [Default]
    /// </summary>
    Default = 0,

    /// <summary>
    /// Represents a string literal parsing type where a double quotes should be escaped by two double quotes.
    /// E.G. var expression = "StaticHelper.Filter(\"UserName == "\"\"x\"\"\")";
    /// </summary>
    EscapeDoubleQuoteByTwoDoubleQuotes = 1
}
```

**Comment by brettwinters** [comment]
Hi @StefH  - escaping and unescaping serialised strings get really confusing quickly haha 

The rule I think is that each pair of backslashes `\\` turns into a single backslash `\` and `\"` turns into `"` right? so combining, like this `\\\"` turns into` \"` (i.e. " when deserialised again into memory). 

So `\"UserName == \\\"x\\\"\"` -> `"UserName == \"x\""` (i.e. UserName == "x" in memory)

But the `EscapeDoubleQuoteByTwoDoubleQuotes` `\"UserName == "\"\"x\"\"\"` -> `"UserName == "x""` (i.e. UserName == x" in memory) which to me looks wrong so I'd call it "Legacy" with an [Obsolete] attribute but I'm not sure who depends on this behaviour...

**Comment by brettwinters** [comment]
wait I just confused myself. You're right `\"UserName == "\"\"x\"\"\"` -> `UserName == "x" ` - its totally correct and valid considering the rules before right? Can your parser handle both scenarios without requiring a configuration setting?

**Comment by StefH** [comment]
The parser cannot handle both cases automatically. You need to use the config.
