### ISSUE TITLE
ExpressionParser finds Types from IEnumerable instead of IQueryable (breaks Code) (worked in 1.3.9)

### ISSUE THREAD

**Issue by jogibear9988** [zzzprojects/System.Linq.Dynamic.Core#801]
## 1. Description
I've the following Code:

                        var expression = DynamicExpressionParser.ParseLambda(qry.GetType(), null, complexQueryString, objs.ToArray());
                        Delegate del = expression.Compile();
                        var resultIv = del.DynamicInvoke(qry);
                        qry = resultIv as IQueryable;

where qry.GetType() is of type  Table<T> wich inherits from IQueryable<T>

My compleyQueryString looks like this:

      "it.GroupBy(MessageClassName).Select(it.Key).Where(it != null).Distinct().OrderBy(it).Take(1000)"

this results in the following Expression Tree (in 1.3.10 and later)
<img width="762" alt="image" src="https://github.com/zzzprojects/System.Linq.Dynamic.Core/assets/364896/6d2f998f-2425-47e2-b04f-4dab4bf278c9">

but in Version 1.3.9 it has the following Tree:

<img width="760" alt="image" src="https://github.com/zzzprojects/System.Linq.Dynamic.Core/assets/364896/1027d082-2f7d-4227-bb11-15b09ac5a739">

## 2. Exception

There is no exception, but the Query is no IQueryable after the Parsing any more, and so my code fails

**Comment by StefH** [comment]
@jogibear9988 Thank your for reporting this issue.
Fixed with #802
