### ISSUE TITLE
>= 1.3.3 Slow First Dynamic Select

### ISSUE THREAD

**Issue by alexhuzenhcicare** [zzzprojects/System.Linq.Dynamic.Core#812]
.NET Version: 8.0
Version: >= 1.3.3

The first dynamic select takes significantly long (> 20s) to be initialised on any version greater then 1.3.2.

**Comment by StefH** [comment]
@alexhuzenhcicare 
I think your issue is linked to https://github.com/zzzprojects/System.Linq.Dynamic.Core/issues/790

I'll close this one.

**Comment by StefH** [comment]
https://github.com/zzzprojects/System.Linq.Dynamic.Core/pull/807
