### ISSUE TITLE
FileLoadException: Could not load file or assembly 'Microsoft.EntityFrameworkCore.DynamicLinq, Version=1.4.3.0, Culture=neutral, PublicKeyToken=974e7e1b462f3693'. Invalid pointer (0x80004003 (E_POINTER))

### ISSUE THREAD

**Issue by MKI-Miro** [zzzprojects/System.Linq.Dynamic.Core#829]
Hi

I am getting error after upgrade to .NET8. 

I am only referencing this: <PackageReference Include="System.Linq.Dynamic.Core" Version="1.3.14" />
I also tried newest version. (same exception).
Error is thrown on gropBy on IQueryable<T>

FileLoadException: Could not load file or assembly 'Microsoft.EntityFrameworkCore.DynamicLinq, Version=1.4.3.0, Culture=neutral, PublicKeyToken=974e7e1b462f3693'. Invalid pointer (0x80004003 (E_POINTER))

TypeInitializationException: The type initializer for 'System.Linq.Dynamic.Core.Parser.PredefinedTypesHelper' threw an exception.

Any suggestions?

Thank you very much.

**Comment by StefH** [comment]
@MKI-Miro 
please provide a full working example project to show this error

**Comment by MKI-Miro** [comment]
This is extremly problematic because its realy big project :(

I hoped for any tip

**Comment by MKI-Miro** [comment]
Isnt it weird that it wants Microsoft.EntityFrameworkCore.DynamicLinq in version 1.4.3 ?

**Comment by StefH** [comment]
> This is extremly problematic because its realy big project :(
> 
> I hoped for any tip

In order to analyze this error, I really need an example project which shows this issue.

**Comment by StefH** [comment]
@MKI-Miro 
Can you provide a full working example?

**Comment by StefH** [comment]
@MKI-Miro
Can you provide a full working example?

**Comment by StefH** [comment]
Closing..
